### PR TITLE
generation example: print number of warmup iterations

### PR DESCRIPTION
**Pull request by mgonchar**
# What does this PR do?

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by emascarenhas** [comment]
@Miroslav,
Please run "pip install -U ruff; make style" in docker container and fix errors if any.
Also run the fast tests. I know this is just a print change, so don't expect to see any errors.
bash tests/ci/fast_tests.sh

If this is clean, should be good to merge.

**Comment by mgonchar** [comment]
@emascarenhas I've ran formatting and it shows that everything is fine. I also launched tests you've suggested (excluding distributed tests, since I have only 1 card reservation), no fails

**Comment by emascarenhas** [comment]
> @emascarenhas I've ran formatting and it shows that everything is fine. I also launched tests you've suggested (excluding distributed tests, since I have only 1 card reservation), no fails

@regisss , @libinta , This should be good to proceed with run-tests and merge.

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
