### PR TITLE
Fix bridgetower example (#312)

### PR DESCRIPTION
**Pull request by astachowiczhabana**
Description: Adding support for loading images stored directly in a JSON file (encoded using ISO-8859-1) into an image object.
 
It resolves an error: TypeError Unexpected type <class 'NoneType'> in BridgeTower model.
 
Command:
WANDB_DISABLED=true PT_HPU_MAX_COMPOUND_OP_SIZE=512 python3 run_bridgetower.py --model_name_or_path 'BridgeTower/bridgetower-large-itm-mlm-itc' --do_train --dataset_name 'jmhessel/newyorker_caption_contest' --dataset_config matching --image_column image --caption_column image_description --remove_unused_columns False --mediapipe_dataloader --output_dir /tmp/bridgetower-test --per_device_train_batch_size 40 --per_device_eval_batch_size 16 --learning_rate 1e-05 --overwrite_output_dir --use_habana --use_lazy_mode --use_hpu_graphs_for_inference --gaudi_config_name Habana/clip --save_strategy epoch --throughput_warmup_steps 3 --num_train_epochs 1 --logging_steps 10 --distribution_strategy fast_ddp

### CODE REVIEW

**Comment by astachowiczhabana** [comment]
will do

**Comment by vidyasiv** [comment]
@astachowiczhabana , thanks for the PR. 
Do you think its a good idea to include a line about the newly supported format in the [README](https://github.com/huggingface/optimum-habana/tree/main/examples/contrastive-image-text#readme) for better visibility to customers? 

will do another round of review after testing

**Review by vidyasiv — CHANGES_REQUESTED** [review]
#### Testing w/ given command : pass
```
WANDB_DISABLED=true PT_HPU_MAX_COMPOUND_OP_SIZE=512 python3 examples/contrastive-image-text/run_bridgetower.py \
--model_name_or_path 'BridgeTower/bridgetower-large-itm-mlm-itc' --do_train \
--dataset_name 'jmhessel/newyorker_caption_contest' --dataset_config matching \
--image_column image --caption_column image_description --remove_unused_columns False \
--mediapipe_dataloader --output_dir /tmp/bridgetower-test --per_device_train_batch_size 40 --per_device_eval_batch_size 16 \
--learning_rate 1e-05 --overwrite_output_dir --use_habana --use_lazy_mode --use_hpu_graphs_for_inference \
--gaudi_config_name Habana/clip --save_strategy epoch --throughput_warmup_steps 3 --num_train_epochs 1 \
--logging_steps 10 --distribution_strategy fast_ddp \
--do_eval
```
output
```
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =      63.55
  memory_allocated (GB)       =      10.63
  total_flos                  =  5699497GF
  total_memory_available (GB) =      94.62
  train_loss                  =     0.0919
  train_runtime               = 0:04:27.63
  train_samples_per_second    =      58.05
  train_steps_per_second      =      1.452
```

#### Testing with --do_eval : fail?
```
WANDB_DISABLED=true PT_HPU_MAX_COMPOUND_OP_SIZE=512 python3 examples/contrastive-image-text/run_bridgetower.py \
--model_name_or_path 'BridgeTower/bridgetower-large-itm-mlm-itc' --do_train \
--dataset_name 'jmhessel/newyorker_caption_contest' --dataset_config matching \
--image_column image --caption_column image_description --remove_unused_columns False \
--mediapipe_dataloader --output_dir /tmp/bridgetower-test --per_device_train_batch_size 40 --per_device_eval_batch_size 16 \
--learning_rate 1e-05 --overwrite_output_dir --use_habana --use_lazy_mode --use_hpu_graphs_for_inference \
--gaudi_config_name Habana/clip --save_strategy epoch --throughput_warmup_steps 3 --num_train_epochs 1 \
--logging_steps 10 --distribution_strategy fast_ddp \
--do_eval
```
```
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =      63.84
  memory_allocated (GB)       =      10.63
  total_flos                  =  5699497GF
  total_memory_available (GB) =      94.62
  train_loss                  =     0.0919
  train_runtime               = 0:04:19.70
  train_samples_per_second    =     59.687
  train_steps_per_second      =      1.493
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:1
11/15/2024 23:41:35 - WARNING - clip_mediapipe_dataloader - Using Pytorch native dataloader because: [Errno 2] No such file or directory: '118.jpeg'.
Exception ignored in: <function HPUGenericPytorchIterator.__del__ at 0x7fa4b0785090>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/mediapipe/plugins/iterator_pytorch.py", line 255, in __del__
    del self.pipe
AttributeError: pipe
```
@astachowiczhabana, pls clarify if I tested wrong

#### README run_bridgetower.py command test
```
python ../gaudi_spawn.py --use_mpi --world_size 8 run_bridgetower.py \
  --output_dir /tmp/bridgetower-test \
  --model_name_or_path BridgeTower/bridgetower-large-itm-mlm-itc \
  --dataset_name jmhessel/newyorker_caption_contest --dataset_config_name matching \
  --dataset_revision 3c6c4f6c0ff7e902833d3afa5f8f3875c2b036e6 \
  --image_column image --caption_column image_description \
  --remove_unused_columns=False \
  --do_train --do_eval --do_predict \
  --per_device_train_batch_size="40" --per_device_eval_batch_size="16" \
  --num_train_epochs 5 \
  --learning_rate="1e-5" \
  --overwrite_output_dir \
  --save_strategy no \
  --use_habana --use_lazy_mode --use_hpu_graphs_for_inference --gaudi_config_name Habana/clip \
  --throughput_warmup_steps 3 \
  --logging_steps 10 \
  --dataloader_num_workers 1 \
  --mediapipe_dataloader \
  --distribution_strategy fast_ddp \
  --trust_remote_code
  ```
  output
  ```
  ***** train metrics *****
  epoch                       =        5.0
  max_memory_allocated (GB)   =      83.18
  memory_allocated (GB)       =      66.14
  total_flos                  = 28846437GF
  total_memory_available (GB) =      94.62
  train_loss                  =     0.0741
  train_runtime               = 0:03:26.77
  train_samples_per_second    =    858.954
  train_steps_per_second      =       2.72
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:1
[INFO|trainer.py:1832] 2024-11-15 23:52:06,969 >> Using HPU graphs for inference.
[INFO|trainer.py:1850] 2024-11-15 23:52:06,969 >> 
***** Running Evaluation *****
[INFO|trainer.py:1852] 2024-11-15 23:52:06,969 >>   Num examples = 531
[INFO|trainer.py:1855] 2024-11-15 23:52:06,969 >>   Batch size = 16
  0%|          | 0/5 [00:00<?, ?it/s]MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
100%|██████████| 5/5 [00:00<00:00, 24.15it/s]
***** validation metrics *****
  epoch                       =        5.0
  eval_loss                   =     0.1136
  eval_runtime                = 0:00:05.90
  eval_samples_per_second     =    813.448
  eval_steps_per_second       =     11.067
  max_memory_allocated (GB)   =      83.18
  memory_allocated (GB)       =      66.74
  total_memory_available (GB) =      94.62
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:2
[INFO|trainer.py:1832] 2024-11-15 23:52:12,903 >> Using HPU graphs for inference.
[INFO|trainer.py:1850] 2024-11-15 23:52:12,903 >> 
***** Running Evaluation *****
[INFO|trainer.py:1852] 2024-11-15 23:52:12,903 >>   Num examples = 528
[INFO|trainer.py:1855] 2024-11-15 23:52:12,903 >>   Batch size = 16
100%|██████████| 5/5 [00:00<00:00, 20.57it/s]
***** test metrics *****
  epoch                       =        5.0
  eval_loss                   =     0.1178
  eval_runtime                = 0:00:00.26
  eval_samples_per_second     =    643.143
  eval_steps_per_second       =      8.933
  max_memory_allocated (GB)   =      83.18
  memory_allocated (GB)       =      66.75
  total_memory_available (GB) =      94.62
```

#### test_examples.py run_bridgetower test : pass

```
pytest -s -v tests/test_examples.py -k run_bridge
```
output
```
1 passed, 62 deselected in 253.85s (0:04:13)
```

**Comment by vidyasiv** [comment]
@astachowiczhabana , pls check on the --do_eval command I saw failing above..

**Comment by vidyasiv** [comment]
@astachowiczhabana If we don't see an update  by  wed, this will need to be part of 1.20 release.

**Comment by astachowiczhabana** [comment]
@vidyasiv can you please try with --dataset_revision 3c6c4f6c0ff7e902833d3afa5f8f3875c2b036e6 as specified in https://github.com/huggingface/optimum-habana/tree/main/examples/contrastive-image-text

**Comment by vidyasiv** [comment]
Thanks @astachowiczhabana -updated command for --do_eval. needed trust_remote_code and dataset_revision.
```
WANDB_DISABLED=true PT_HPU_MAX_COMPOUND_OP_SIZE=512 python3 examples/contrastive-image-text/run_bridgetower.py \
--model_name_or_path 'BridgeTower/bridgetower-large-itm-mlm-itc' --do_train \
--dataset_name 'jmhessel/newyorker_caption_contest' --dataset_config matching \
--image_column image --caption_column image_description --remove_unused_columns False \
--mediapipe_dataloader --output_dir /tmp/bridgetower-test --per_device_train_batch_size 40 --per_device_eval_batch_size 16 \
--learning_rate 1e-05 --overwrite_output_dir --use_habana --use_lazy_mode --use_hpu_graphs_for_inference \
--gaudi_config_name Habana/clip --save_strategy epoch --throughput_warmup_steps 3 --num_train_epochs 1 \
--logging_steps 10 --distribution_strategy fast_ddp \
--do_eval  \
--trust_remote_code \
--dataset_revision 3c6c4f6c0ff7e902833d3afa5f8f3875c2b036e6 
```
output
```
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =      94.49
  memory_allocated (GB)       =       15.6
  total_flos                  =  5699497GF
  total_memory_available (GB) =      94.62
  train_loss                  =     0.0919
  train_runtime               = 0:04:53.11
  train_samples_per_second    =     51.063
  train_steps_per_second      =      1.278
MediaPipe device legacy device_type legacy device_id 0 pipe_name ClipMediaPipe:1
[INFO|trainer.py:1832] 2024-11-26 19:03:56,223 >> Using HPU graphs for inference.
[INFO|trainer.py:1850] 2024-11-26 19:03:56,223 >> 
***** Running Evaluation *****
[INFO|trainer.py:1852] 2024-11-26 19:03:56,223 >>   Num examples = 531
[INFO|trainer.py:1855] 2024-11-26 19:03:56,223 >>   Batch size = 16
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:01<00:00, 21.78it/s]
***** validation metrics *****
  epoch                       =        1.0
  eval_loss                   =     0.1186
  eval_runtime                = 0:00:07.97
  eval_samples_per_second     =    324.361
  eval_steps_per_second       =     20.818
  max_memory_allocated (GB)   =      94.49
  memory_allocated (GB)       =      16.75
  total_memory_available (GB) =      94.62
```

**Review by vidyasiv — APPROVED** [review]
lgtm @regisss please take a look.

**Pull request merged**
