### PR TITLE
Flash attention enhancement of repeatKV

### PR DESCRIPTION
**Pull request by puneeshkhanna**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by puneeshkhanna** [comment]
@regisss  - Don't merge this yet. Let me add some testing results too in this week. 

Fused SDPA will internally handle repeat KV logic in 1.14 release hence we don't need repeat KV logic when flash attention is enabled.  We should see perf boost for some configs such as TP-4.

Can you please add tag of synapse 1.14 to this PR mean while.

**Review by dvarshney-habana — APPROVED** [review]

**Review by regisss — APPROVED** [review]
Very nice speedups!

So we have to wait for the release of SynapseAI v1.14 to merge this one right?

**Comment by puneeshkhanna** [comment]
Yes @regisss  - I think we l need to wait for it.

**Comment by schoi-habana** [comment]
@puneeshkhanna we tested the PR with a 4x finetuning, but no performance improvement was seen. is the perf improvement limited to inference, or did I miss something?

**Review by libinta — APPROVED** [review]

**Comment by puneeshkhanna** [comment]
@schoi-habana  - Just to double check that you did use "flash attention" for finetuning too right  and also finetuning 70B model right ? I m not sure how flash attention flag is passed for finetuning. Perf improvement surely for inference of 70B model. Change is not applicable for 7b and 13 b models as they don't use GQA.  We should also see some improvement in memory usage too.

**Comment by schoi-habana** [comment]
@puneeshkhanna yes i tested llama2-70b with --use_flash_attention. the sec/iter improvement is about 2-3% and the mem usage didn't improve.

**Comment by puneeshkhanna** [comment]
Thanks for the update @schoi-habana . 2-3% improvement in finetuning is good too I guess. We should be good to merge this with 1.14 synapse release. I will try to fix the non-flash attention path too in next week in separate PR.

**Comment by puneeshkhanna** [comment]
We should first merge this PR and then https://github.com/huggingface/optimum-habana/pull/639 to avoid any merge conflicts hopefully.

**Pull request merged**
