### PR TITLE
Fix eager mode in run_generation by removing graph logs

### PR DESCRIPTION
**Pull request by Vasud-ha**
# What does this PR do?
This PR removed GRAPH_VISUALIZATION=TRUE from run_generation.py script as it was generating thousands of logs files(.pbtxt) in eager mode.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by kausikmaiti — COMMENTED** [review]
Looks ok to me.

**Review by libinta — COMMENTED** [review]
@Vasud-ha  this only generates when it in lazy model, and we have stats to print the graph #. you can remove manually, right?

**Comment by Vasud-ha** [comment]
> @Vasud-ha this only generates when it in lazy model, and we have stats to print the graph #. you can remove manually, right?

This only generates in eager mode and since the number of generated log files is huge it is difficult to delete.

**Comment by vidyasiv** [comment]
@Vasud-ha , I too ran into this issue, what puzzles me is args.torch_compile must be true for eager though.
Can you test if you see the files generated if you set `ENABLE_CONSOLE=true`. In my case it just stopped generating them when I set that. I am not sure its a good solution necessarily as ENABLE_CONSOLE affects all logging.

**Comment by nngokhale** [comment]
> @Vasud-ha , I too ran into this issue, what puzzles me is args.torch_compile must be true for eager though. Can you share your command with us? Can you test if you see that the files generated if you set `ENABLE_CONSOLE=true` ?

Any run_generation script example will do this when in eager mode, our example is :
PT_HPU_LAZY_MODE=0 python run_generation.py --model_name_or_path google/gemma-2b-it --use_kv_cache --max_new_tokens 100 --bf16 --batch_size 1 --do_sample --prompt "Write a hello world program"

Always turning ON a debug env variable inside the script is a bad idea anyway.

**Comment by vidyasiv** [comment]
> > @Vasud-ha , I too ran into this issue, what puzzles me is args.torch_compile must be true for eager though. Can you share your command with us? Can you test if you see that the files generated if you set `ENABLE_CONSOLE=true` ?
> 
> Any run_generation script example will do this when in eager mode, our example is : PT_HPU_LAZY_MODE=0 python run_generation.py --model_name_or_path google/gemma-2b-it --use_kv_cache --max_new_tokens 100 --bf16 --batch_size 1 --do_sample --prompt "Write a hello world program"
> 
> Always turning ON a debug env variable inside the script is a bad idea anyway.

Agreed I wasn't suggesting to turn on the debug var as a solution, I was just trying to understand behavior.

**Comment by yeonsily** [comment]
LGTM.

**Review by regisss — COMMENTED** [review]
LGTM!
Please run `make style` and then I'll merge it.

**Comment by Vasud-ha** [comment]
> LGTM! Please run `make style` and then I'll merge it.

`make style` Done.

**Review by regisss — APPROVED** [review]

**Pull request merged**
