### PR TITLE
Updating LLama, Falcon sub graph tests according to transformers 4.37…

### PR DESCRIPTION
**Pull request by vineethanandh**
….2 (#184)

* Updating LLama sub graph tests according to transformers 4.37.2

* Updating Falcon sub graph tests according to transformers 4.37.2

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by imangohari1 — CHANGES_REQUESTED** [review]
Hi @vineethanandh 
Thanks for opening this PR. 
I have ran and compared this PR on 1.16 drivers. the current PR's pytest llama results are different than the `main` brach. 

Could you please rebase this to the top of the main branch, retest the changes as follow and share the outputs?
Thanks. 
```bash 
python -m pip install .[tests]
python -m pytest  tests/transformers/tests/models/falcon/test_modeling_falcon.py tests/transformers/tests/models/llama/test_modeling_llama.py
```

**Comment by imangohari1** [comment]
@vineethanandh Any updates on this?

**Comment by vineethanandh** [comment]
@imangohari1 

I missed this conversation. I will check and update.

**Comment by imangohari1** [comment]
> @imangohari1
> 
> I missed this conversation. I will check and update.

@vineethanandh 
Can we update this PR or close it if no longer needed? it has been stalled for a while. Tnx

**Comment by vineethanandh** [comment]
These changes are not required, since the test file needs to be updated with latest transformers

**Pull request closed without merging**
