### PR TITLE
Jinbh/gptj neox contiguous

### PR DESCRIPTION
**Pull request by BaihuiJin**
# What does this PR do?

Add contiguous fix to modeling_gptj and modeling_gpt_neox to reduce max mem allocation and improve perf.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by BaihuiJin** [comment]
GPTJ perf:
Baseline:
Throughput (including tokenization) = 1651.0043325445658 tokens/second
Memory allocated                    = 26.65 GB
Max memory allocated                = 50.39 GB
Total memory available              = 94.46 GB
Graph compilation duration          = 14.231710526975803 seconds
After:
Throughput (including tokenization) = 2251.854885296207 tokens/second
Memory allocated                    = 26.74 GB
Max memory allocated                = 43.64 GB
Total memory available              = 94.46 GB
Graph compilation duration          = 11.01004623901099 seconds

**Comment by BaihuiJin** [comment]
Neox perf:
Baseline:
Throughput (including tokenization) = 5557.131562899302 tokens/second
Memory allocated                    = 16.74 GB
Max memory allocated                = 94.18 GB
Total memory available              = 94.46 GB
Graph compilation duration          = 13.148631287971511 seconds

After:
Throughput (including tokenization) = 6526.11999284205 tokens/second
Memory allocated                    = 13.91 GB
Max memory allocated                = 17.68 GB
Total memory available              = 94.46 GB
Graph compilation duration          = 11.623883856984321 seconds

**Review by regisss — APPROVED** [review]
LGTM!
I'll let the final approval to @ZhaiFeiyue.

**Review by ZhaiFeiyue — APPROVED** [review]
LGTM!

**Pull request merged**
