### PR TITLE
Fixing the relative path in config read

### PR DESCRIPTION
**Pull request by vineethanandh**
# What does this PR do?
This change will fix the relative path in gaudi config. Instead uses the absolute path in the current execution env.

Fixes # (issue)
Errors caused by relative gaudi config path when test is triggered from a different path.

### CODE REVIEW

**Comment by vineethanandh** [comment]
@regisss  - Raising a new PR since I could find one more file to be changed. This time style is ran.
But it changed some files and showed
All done! ✨ 🍰 ✨
84 files reformatted, 96 files left unchanged.
ruff . setup.py --fix

I discarded all the changes.

**Comment by regisss** [comment]
@vineethanandh Looks weird, could you try the following?
```
pip install --upgrade black ruff
make style
```

**Comment by vineethanandh** [comment]
@regisss  - I think after the upgrade it worked correctly
reformatted /home/vineethanandh/qnpu/my_workspace/src/optimum-habana/tests/test_trainer.py

All done! ✨ 🍰 ✨
1 file reformatted, 180 files left unchanged.
ruff . setup.py --fix

Formatting is applied to one file. pushed the formatted version. Please review

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
