### PR TITLE
enable `paligemma`  model

### PR DESCRIPTION
**Pull request by kaixuanliu**

### CODE REVIEW

**Comment by kaixuanliu** [comment]
Cmd line: `python3 run_pipeline.py --model_name_or_path google/paligemma-3b-mix-224 --use_hpu_graphs --bf16`, this PR should work with [#1279](https://github.com/huggingface/optimum-habana/pull/1279)

**Comment by kaixuanliu** [comment]
Add throughput comparison with A100:
| throught(tokens/s) | A100 | Gaudi2 |
|----------|----------|----------|
| BF16 |  55.37 | 132.83 |
| FP32 | 39.36 | 81.29 |

**Comment by kaixuanliu** [comment]
@regisss , pls help review

**Comment by yeonsily** [comment]
LGTM. 
@kaixuanliu  Can you please rebase your code? And for your throughput test, which docker and setup did you use?

**Comment by kaixuanliu** [comment]
@yeonsily , Hi, I have rebased the code. For throughput test, I used docker image `vault.habana.ai/gaudi-docker/1.17.1/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest` and build the env for optimum-habana from source by `pip install .`. And for accuracy test, I checked the output text, it is aligned with the output in [HF model](https://huggingface.co/google/paligemma-3b-pt-224)

**Comment by yeonsily** [comment]
> @yeonsily , Hi, I have rebased the code. For throughput test, I used docker image `vault.habana.ai/gaudi-docker/1.17.1/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest` and build the env for optimum-habana from source by `pip install .`. And for accuracy test, I checked the output text, it is aligned with the output in [HF model](https://huggingface.co/google/paligemma-3b-pt-224)



> @yeonsily , Hi, I have rebased the code. For throughput test, I used docker image `vault.habana.ai/gaudi-docker/1.17.1/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest` and build the env for optimum-habana from source by `pip install .`. And for accuracy test, I checked the output text, it is aligned with the output in [HF model](https://huggingface.co/google/paligemma-3b-pt-224)



> @yeonsily , Hi, I have rebased the code. For throughput test, I used docker image `vault.habana.ai/gaudi-docker/1.17.1/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest` and build the env for optimum-habana from source by `pip install .`. And for accuracy test, I checked the output text, it is aligned with the output in [HF model](https://huggingface.co/google/paligemma-3b-pt-224)

Thanks. can you please double check if your rebased code is working fine?

I tried to run your https://github.com/kaixuanliu/optimum-habana/tree/paligemma-example on 1.17 docker but get this error.

```
Traceback (most recent call last):
  File "/work/optimum-habana/examples/image-to-text/run_pipeline.py", line 291, in <module>
    main()
  File "/work/optimum-habana/examples/image-to-text/run_pipeline.py", line 183, in main
    args.prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)
UnboundLocalError: local variable 'processor' referenced before assignment
```

**Comment by kaixuanliu** [comment]
@yeonsily , oops, there is conflict when doing the rebase work, have submitted new commit to fix it. And have checked the output. It is recommend to use cmd line: `python3 run_pipeline.py --model_name_or_path google/paligemma-3b-mix-224 --use_hpu_graphs --bf16 --use_kv_cache`

**Comment by kaixuanliu** [comment]
@yeonsily , there is a lot of update for the latest code. Can you help review it again?

**Pull request closed without merging**
