### PR TITLE
Ig/Diffusers timing

### PR DESCRIPTION
**Pull request by imangohari1**
# What does this PR do?
This PR addresses the followings:
- Fixes the controlnet pipeline to include `use_warmup_inference_steps`  adjustments 
- Fixed the `use_warmup_inference_steps` logic to include the warmup in all diffuser pipelines. 
  - issue: when `num_batches = throughput_warmup_steps` the `generation_samples_per_second` is almost 0.   
- Following the work @dsocek  and I did for SD3 ([here](https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py#L468)), updated the `steps_per_second` for all pipelines to represent average time for 1 `inference step`
   - 1 average inference step is a good measure because it is independent of numbers of steps per sample which can vary (i.e. 20, 50, etc). 
   - @regisss  @ssarkar2 WDYT on this? Any thoughts what was the original thoughts/ideas behind using only `num_batches`, and not include batch size and number of images per prompt and number of prompts?
      - I have not found an equivalent of this metric on HF upstream code.  
- Added a skip in 8x MPI tests in `tests/test_diffusers.py` when 8 cards are not avail 
   - Added value here is ability to run this tests on KVM systems with only 1card available. 

## Example of issue with SDXL

```
python text_to_image_generation.py     --model_name_or_path stabilityai/stable-diffusion-xl-base-1.0     --prompts "Sailing ship painting by Van Gogh"     --num_images_per_prompt 3     --batch_size 1     --image_save_dir /tmp/stable_diffusion_xl_images     --scheduler euler_discrete     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16
.
.
.
/usr/local/lib/python3.10/dist-packages/diffusers/models/unets/unet_2d_blocks.py:2628: FutureWarning: `scale` is deprecated and will be removed in version 1.0.0. The `scale` argument is deprecated and will be ignored. Please remove it, as passing it will raise an error in the future. `scale` should directly be passed while calling the underlying pipeline component i.e., via `cross_attention_kwargs`.
  deprecate("scale", "1.0.0", deprecation_message)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:33<00:00, 51.23s/it]
[INFO|pipeline_stable_diffusion_xl.py:829] 2024-08-27 16:57:50,077 >> Speed metrics: {'generation_runtime': 153.6776, 'generation_samples_per_second': 0.02, 'generation_steps_per_second': 0.02}
```

## Tests 
All the changed pipelines are tested for #prompts = #throughput_steps and the measured `samples_per_second` are compared with expected values. 

### stable diff 
```bash
python examples/stable-diffusion/text_to_image_generation.py     --model_name_or_path runwayml/stable-diffusion-v1-5     --prompts "An image of a squirrel in Picasso style"     --num_images_per_prompt 3     --batch_size 1     --image_save_dir /tmp/stable_diffusion_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16
```
```
[INFO|pipeline_stable_diffusion.py:608] 2024-08-16 20:45:32,560 >> Speed metrics: {'generation_runtime': 55.8091, 'generation_samples_per_second': 0.821, 'generation_steps_per_second': 41.071}
```
Expected=0.9. Matches measured. ✅ 

### sd-inpainting
```
python text_to_image_generation.py     --model_name_or_path  runwayml/stable-diffusion-inpainting     --base_image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint.png     --mask_image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint_mask.png     --prompts "concept art digital painting of an elven castle, inspired by lord of the rings, highly detailed, 8k"     --seed 0     --num_images_per_prompt 3     --batch_size 1     --image_save_dir /tmp/inpaiting_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16
```
```
[INFO|pipeline_stable_diffusion_inpaint.py:721] 2024-08-16 20:51:29,610 >> Speed metrics: {'inpainting_runtime': 49.0233, 'inpainting_samples_per_second': 0.827, 'inpainting_steps_per_second': 41.342}
```
Expected=0.9. Matches measured. ✅ 

### sdv2 
```
python text_to_image_generation.py     --model_name_or_path stabilityai/stable-diffusion-2-1     --prompts "An image of a squirrel in Picasso style"     --num_images_per_prompt 3     --batch_size 1     --height 768     --width 768     --image_save_dir /tmp/stable_diffusion_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion-2     --bf16
```
```
[INFO|pipeline_stable_diffusion.py:608] 2024-08-16 21:14:22,343 >> Speed metrics: {'generation_runtime': 88.7877, 'generation_samples_per_second': 0.352, 'generation_steps_per_second': 17.612}
```
Expected=0.36. Matches measured. ✅ 

### sdxl 
```
python text_to_image_generation.py     --model_name_or_path stabilityai/stable-diffusion-xl-base-1.0     --prompts "Sailing ship painting by Van Gogh"     --num_images_per_prompt 3     --batch_size 1     --image_save_dir /tmp/stable_diffusion_xl_images     --scheduler euler_discrete     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16
```
```
[INFO|pipeline_stable_diffusion_xl.py:827] 2024-08-16 21:12:07,058 >> Speed metrics: {'generation_runtime': 163.4171, 'generation_samples_per_second': 0.199, 'generation_steps_per_second': 9.938}
```
Expected=0.2. Matches measured. ✅ 

### sdxl-inpaint 
```
python text_to_image_generation.py     --model_name_or_path  diffusers/stable-diffusion-xl-1.0-inpainting-0.1    --base_image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint.png     --mask_image https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/inpaint_mask.png     --prompts "concept art digital painting of an elven castle, inspired by lord of the rings, highly detailed, 8k"     --seed 0     --scheduler euler_discrete     --num_images_per_prompt 3     --batch_size 1     --image_save_dir /tmp/xl_inpaiting_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16
```
```
[INFO|pipeline_stable_diffusion_xl_inpaint.py:926] 2024-08-16 21:25:01,668 >> Speed metrics: {'inpainting_runtime': 108.7956, 'inpainting_samples_per_second': 0.203, 'inpainting_steps_per_second': 9.942}
```
Expected=0.2. Matches measured. ✅ 

### ldm3d 
```
python text_to_image_generation.py     --model_name_or_path "Intel/ldm3d-4c"     --prompts "An image of a squirrel in Picasso style"     --num_images_per_prompt 3     --batch_size 1     --height 768     --width 768     --image_save_dir /tmp/stable_diffusion_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion-2     --ldm3d     --bf16
```
```
[INFO|pipeline_stable_diffusion_ldm3d.py:426] 2024-08-16 22:23:58,857 >> Speed metrics: {'generation_runtime': 92.824, 'generation_samples_per_second': 0.269, 'generation_steps_per_second': 13.472}
```
Expected=0.2754. Matches measured. ✅ 

### svd 
```
PT_HPU_MAX_COMPOUND_OP_SIZE=1 python image_to_video_generation.py     --model_name_or_path "stabilityai/stable-video-diffusion-img2vid-xt"     --image_path "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png"     --num_videos_per_prompt 3     --video_save_dir /tmp/stable_video_diffusion_xt     --save_frames_as_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16 
```
```
[INFO|pipeline_stable_video_diffusion.py:561] 2024-08-16 22:57:53,107 >> Speed metrics: {'generation_runtime': 491.712, 'generation_samples_per_second': 0.007, 'generation_steps_per_second': 0.174}
```
Expected=0.008. Matches measured. ✅ 

### controlnet 
```
python text_to_image_generation.py     --model_name_or_path stabilityai/stable-diffusion-2-1     --controlnet_model_name_or_path thibaud/controlnet-sd21-canny-diffusers     --control_image https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/bird_canny.png     --control_preprocessing_type "none"     --prompts "bird"     --seed 0     --num_images_per_prompt $numimg     --batch_size 1     --image_save_dir /tmp/controlnet-2-1_images     --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion-2     --bf16
````
Expected=0.04379.

`--num_images_per_prompt 2`
```
[INFO|pipeline_controlnet.py:643] 2024-08-16 22:45:04,991 >> Speed metrics: {'generation_runtime': 72.2782, 'generation_samples_per_second': 0.44, 'generation_steps_per_second': 21.982}
```
`--num_images_per_prompt 3`
```
[INFO|pipeline_controlnet.py:643] 2024-08-16 22:41:10,373 >> Speed metrics: {'generation_runtime': 85.7749, 'generation_samples_per_second': 0.439, 'generation_steps_per_second': 21.955}
```
`--num_images_per_prompt 4`
```
[INFO|pipeline_controlnet.py:643] 2024-08-16 22:43:18,312 >> Speed metrics: {'generation_runtime': 88.1551, 'generation_samples_per_second': 0.447, 'generation_steps_per_second': 89.366}
```
all measured checks ✅.

## CI tests 
The `GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/test_diffusers.py -s -v` produces the same results before/after this changes. 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by dsocek — APPROVED** [review]
LGTM

**Review by libinta — COMMENTED** [review]
can you remove HS-2418 and describe the issue?

**Comment by imangohari1** [comment]
> can you remove HS-2418 and describe the issue?

- HS-2418 is removed. 
- the summary of the issues are: 
  - controlnet pipeline timing to include warmup steps  are wrong. 
  - all the pipelines timing when `num_batches = throughput_warmup_steps ` are wrong. 
  - the generation sample per second does NOT include #interence_steps. 
 
 More description in fixes for these are given here. https://github.com/huggingface/optimum-habana/pull/1277#issue-2475998700

**Comment by imangohari1** [comment]
@libinta 
I updated the PR main comment with an example of issue using SDXL pipeline. 
All the rest are the same.

**Review by regisss — APPROVED** [review]
LGTM!

> @regisss @ssarkar2 WDYT on this? Any thoughts what was the original thoughts/ideas behind using only num_batches, and not include batch size and number of images per prompt and number of prompts?
I have not found an equivalent of this metric on HF upstream code.

There was no particular reason for doing it like this. Pipelines are a bit different here from Diffusers as we do batching and when I first implemented them, I didn't think much about it and defined a step as a batch. But I agree your approach makes more sense.

**Pull request merged**
