### PR TITLE
fix performance issue in mistral

### PR DESCRIPTION
**Pull request by xin3he**
# What does this PR do?

Fix performance issue in mistral

Without this fix, the first token generation will take more time and the performance is bad.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
@xin3he When I run 
```
GAUDI2_CI=1 pytest tests/test_text_generation_example.py -v -s -k "mistralai/Mistral-7B-v0.1" --token my_token
```
I get the following error:
```
File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/mistral/modeling_mistral.py", line 67, in update
    assert cur.shape[2] == 1, f"Cannot update kv-cache. Unsupported shapes. prev:{prev.shape} cur:{cur.shape}"
AssertionError: Cannot update kv-cache. Unsupported shapes. prev:torch.Size([1, 8, 108, 128]) cur:torch.Size([1, 8, 8, 128])
```

**Comment by xin3he** [comment]
Hi @regisss I have fixed the bug you mentioned. Thanks.

**Review by regisss — COMMENTED** [review]
LGTM!

> Without this fix, the first token generation will take more time and the performance is bad.

Can you provide some numbers to compare before and after the fix please?

cc @libinta

**Comment by xin3he** [comment]
Hi @regisss, I'd like to close this PR and follow the defined workflow to upstream this fix to HabanaAI/optimum-habana-fork. Thank you for your help.
https://github.com/HabanaAI/optimum-habana-fork/pull/181

**Pull request closed without merging**
