### PR TITLE
simplify the code for `cache_idx` calculation

### PR DESCRIPTION
**Pull request by Jing1Ling**
# What does this PR do?

Actually I think it’s better to handle `cache_idx` in `prepare_inputs_for_generation()`. But considering many models already implement `--bucket_internal`, I just simplified the implementation and tried to make it easier to understand.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by emascarenhas** [comment]
Please sync your PR with main/upstream and fix any merge conflicts. Thank you.

**Review by ssarkar2 — CHANGES_REQUESTED** [review]
1. Is this a fix, or just a code rewrite? if its a fix, can you please provide the failing command that is fixed with this PR
2. This change is in a critical path (generation/utils.py), used by many code paths. Could you please provide more details what this PR tries to do and how it does it, possible perf gains or any other relevant details
3. There is another section where we have same code, so if we update contrastive search we should update sample as well .. https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L2341

**Comment by Jing1Ling** [comment]
> 1. Is this a fix, or just a code rewrite? if its a fix, can you please provide the failing command that is fixed with this PR
> 2. This change is in a critical path (generation/utils.py), used by many code paths. Could you please provide more details what this PR tries to do and how it does it, possible perf gains or any other relevant details
> 3. There is another section where we have same code, so if we update contrastive search we should update sample as well .. https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L2341

This is a small rewrite of the code, trying to simplify the code logic for `cache_idx` calculation. `cache_idx` is used for kv_cache slice, which means upper boundary index of current kv_cache bucket. It will only be used when `bucket_internal` is enabled. 
I spent unnecessary time understanding this code earlier, so I simplified it.

**Comment by Jing1Ling** [comment]
And I updated _sample() and _contrastive_search().

**Pull request closed without merging**
