### PR TITLE
Revert "Fix T5 DeepSpeed ZeRO-3 (#393)"

### PR DESCRIPTION
**Pull request by sywangyi**
This reverts commit 12b652eab5a8625093dfce9b5fdb724108b9cb1a.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
Hi, regiss
 I tried to enable llama 7b ZERO3 deepspeed finetune.
I use the latest optimum and transformers(4.34.0),
I find the error like
Traceback (most recent call last):
  File "run_clm.py", line 689, in <module>
    main()
  File "run_clm.py", line 636, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/work/optimum-habana/optimum/habana/transformers/trainer.py", line 511, in train
    return inner_training_loop(
  File "/work/optimum-habana/optimum/habana/transformers/trainer.py", line 840, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/work/optimum-habana/optimum/habana/transformers/trainer.py", line 1356, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1504, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1808, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/work/optimum-habana/optimum/habana/transformers/models/llama/modeling_llama.py", line 533, in forward
    shift_logits = shift_logits.view(-1, self.config.vocab_size)
RuntimeError: shape '[-1, 0]' is invalid for input of size 32736000
Traceback (most recent call last):
  File "run_clm.py", line 689, in <module>
    main()
  File "run_clm.py", line 636, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/work/optimum-habana/optimum/habana/transformers/trainer.py", line 511, in train
    return inner_training_loop(
  File "/work/optimum-habana/optimum/habana/transformers/trainer.py", line 840, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/work/optimum-habana/optimum/habana/transformers/trainer.py", line 1356, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1504, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1808, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/work/optimum-habana/optimum/habana/transformers/models/llama/modeling_llama.py", line 533, in forward
    shift_logits = shift_logits.view(-1, self.config.vocab_size)
RuntimeError: shape '[-1, 0]' is invalid for input of size 32736000
and transformers have fixed such issue in resize_embedding and resize_lm_head. optimum-habana could enjoy the fix if not override the _get_resized_embeddings and _get_resized_lm_head. and also I try T5 Deepspeed Zero
it works in transformers 4.33 and 4.34.

**Comment by sywangyi** [comment]
the CI failure is not related to the PR, test in local, the failure case could pass

**Comment by sywangyi** [comment]
llama 7b zero3 could work with this PR and https://github.com/HabanaAI/DeepSpeed/pull/1

**Comment by sywangyi** [comment]
@libinta Hi, could you help review the PR. I have enabled llama 7b ZERO3 successfully.
Running Env
1)	Gaudi2 with 1.11 driver.
2)	Components version: (very important)
transformers            4.34.0
optimum-habana: commit id ca8ecde25b5508336173bcb92c0239683e39d0fc + https://github.com/huggingface/optimum-habana/pull/466
Deepspeed: https://github.com/HabanaAI/DeepSpeed/tree/1.11.0+https://github.com/HabanaAI/DeepSpeed/pull/1
3)	Test script:
https://github.com/huggingface/optimum-habana/blob/main/examples/language-modeling/run_clm.py
python ../gaudi_spawn.py \
    --world_size 8 --use_deepspeed run_clm.py \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --save_strategy no \
    --output_dir /tmp/test-clm-xl-1 \
    --gaudi_config_name Habana/gpt2 \
    --model_name_or_path huggyllama/llama-7b \
    --use_habana \
    --throughput_warmup_steps 3 \
    --deepspeed deepspeed.json \
    --overwrite_output_dir \
    --use_lazy_mode \
--torch_dtype bfloat16 \

      deepspeed.json
      {
                 "steps_per_print": 64,
                "train_batch_size": "auto",
                 "train_micro_batch_size_per_gpu": "auto",
                "gradient_accumulation_steps": "auto",
                "bf16": {
               "enabled": true
                },
                "gradient_clipping": 1.0,
                "zero_optimization": {
               "stage": 3,
               "overlap_comm": false,
               "reduce_scatter": false,
               "contiguous_gradients": false
                }
     }

**Review by regisss — COMMENTED** [review]
The issue here is that we get an embedding size of 0 with DS ZeRO-3 if we revert this commit: https://github.com/huggingface/optimum-habana/blob/9ad8d05fb14eb652cd104b6f8dc6d536963f5b03/examples/summarization/run_summarization.py#L504
It should be solved with Transformers v4.34 but it doesn't work on Gaudi and I don't know why at the moment.

**Comment by sywangyi** [comment]
Hi, @regisss  embedding_size is 0 if zero3 is enable but  model.resize_token_embeddings(len(tokenizer)) could work properly in transformers v4.34.
https://github.com/huggingface/optimum-habana/blob/9ad8d05fb14eb652cd104b6f8dc6d536963f5b03/examples/summarization/run_summarization.py#L505-L506 

I run the example in run_summarization.py .
PT_HPU_MAX_COMPOUND_OP_SIZE=512 python ../gaudi_spawn.py \
    --world_size 8 --use_deepspeed run_summarization.py \
    --model_name_or_path google/flan-t5-xxl \
    --do_train \
    --do_eval \
    --dataset_name cnn_dailymail \
    --dataset_config '"3.0.0"' \
    --source_prefix '"summarize: "' \
    --output_dir ./tst-summarization \
    --per_device_train_batch_size 22 \
    --per_device_eval_batch_size 22 \
    --learning_rate 1e-4 \
    --num_train_epochs 3 \
    --overwrite_output_dir \
    --predict_with_generate \
    --use_habana \
    --use_lazy_mode \
    --gaudi_config_name Habana/t5 \
    --ignore_pad_token_for_loss False \
    --pad_to_max_length \
    --generation_max_length 129 \
    --save_strategy epoch \
    --throughput_warmup_steps 3 \
    --max_step 40 \
    --max_eval_samples 40 \
    --gradient_checkpointing \
    --adam_epsilon 1e-08 --logging_steps 1 \
    --deepspeed ds_flan_t5_z3_config_bf16.json

and did not meet any issue with the PR.

**Comment by regisss** [comment]
Okay, I'll try it out today then :+1:

**Comment by regisss** [comment]
@sywangyi I just pushed a commit to fix the embedding size computation with DS ZeRO-3.

**Review by regisss — APPROVED** [review]

**Pull request merged**
