### PR TITLE
Temporary disable FusedRoPE for llama.

### PR DESCRIPTION
**Pull request by puneeshkhanna**
Batch size > 1 not working with FusedRoPE.
Graph compilation error.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by puneeshkhanna** [comment]
@regisss - please merge this. Once fusedRoPE works with batch size > 1, will enable fusedRoPE again.

**Comment by puneeshkhanna** [comment]
Thank you

**Comment by mandy-li** [comment]
@regisss  Please revert this PR ASAP. Fused RoPE doesn't have any problem with 1.11.0.

**Comment by puneeshkhanna** [comment]
https://github.com/huggingface/optimum-habana/pull/370 - raised a new PR to re-enable fused RoPE. Please merge that.

**Pull request merged**
