### PR TITLE
Simplify HQT config files

### PR DESCRIPTION
**Pull request by Tiefen-boop**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by emascarenhas** [comment]
Hi @Tiefen-boop ,
Why are these changes needed? How did you test these changes? Please confirm you tested with OH main. 

In addition, please run "tests/ci/fast_tests.sh" after installing ".[tests]" and any slow tests, e.g., the ones that do text generation with quantization.

Also do "pip install -U ruff; make style" and check for any issues.

**Comment by emascarenhas** [comment]
Fast tests passed, so this is good to merge.
LGTM.

**Comment by Tiefen-boop** [comment]
@regisss would you like to approve this? @emascarenhas gave his OK

**Comment by regisss** [comment]
@Tiefen-boop Is this compatible with SynapseAI 1.17 ?

**Comment by Tiefen-boop** [comment]
> @Tiefen-boop Is this compatible with SynapseAI 1.17 ?


@regisss no, only for 1.18

**Review by regisss — APPROVED** [review]
LGTM!
Let's wait for the release of SynapseAI 1.18 to merge it.

**Pull request merged**
