### PR TITLE
Added support for Stable Diffusion Inpaint and testcases

### PR DESCRIPTION
**Pull request by JoeyTPChou**
Joined work with @jedwards-habana @nraste

Adding `optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py` and corresponding testcases into CI

### CODE REVIEW

**Comment by JoeyTPChou** [comment]
@regisss  Please kindly review the PR and the testcases.

**Comment by vidyasiv** [comment]
Thanks for adding this pipeline @JoeyTPChou , could you rebase your changes to latest main and also update the [README](https://github.com/huggingface/optimum-habana/blob/main/examples/stable-diffusion/README.md)

**Comment by JoeyTPChou** [comment]
> Thanks for adding this pipeline @JoeyTPChou , could you rebase your changes to latest main and also update the [README](https://github.com/huggingface/optimum-habana/blob/main/examples/stable-diffusion/README.md)

I would love to but I thought you've decided to move forward with this PR instead - https://github.com/huggingface/optimum-habana/pull/869

If there is anything changed we could quickly put together and get this PR ready

**Comment by vidyasiv** [comment]
> > Thanks for adding this pipeline @JoeyTPChou , could you rebase your changes to latest main and also update the [README](https://github.com/huggingface/optimum-habana/blob/main/examples/stable-diffusion/README.md)
> 
> I would love to but I thought you've decided to move forward with this PR instead - #869
> 
> If there is anything changed we could quickly put together and get this PR ready

@JoeyTPChou, Thanks for pointing that out.
@libinta , could you clarify if this PR will be considered? Otherwise I recommend closing to avoid any confusion in future.

**Comment by libinta** [comment]
@JoeyTPChou  this is dup of https://github.com/huggingface/optimum-habana/pull/869 ? I think we can close it now.thanks

**Pull request closed without merging**
