### PR TITLE
fix(nltk): fixed the version to working one

### PR DESCRIPTION
**Pull request by imangohari1**
# What does this PR do?
Fixes the following error in `run_summarization.py` example
```
[12-08-24 19:39:03.412425 ] [rank4]:   File "/root/repos/optimum-habana/examples/summarization/run_summarization.py", line 737, in postprocess_text
[12-08-24 19:39:03.412430 ] [rank4]:     preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
[12-08-24 19:39:03.412435 ] [rank4]:   File "/root/repos/optimum-habana/examples/summarization/run_summarization.py", line 737, in <listcomp>
[12-08-24 19:39:03.412440 ] [rank4]:     preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
[12-08-24 19:39:03.412445 ] [rank4]:   File "/tmp/.tox/t5small/lib/python3.10/site-packages/nltk/tokenize/{}init{}.py", line 106, in sent_tokenize
[12-08-24 19:39:03.412450 ] [rank4]:     tokenizer = PunktTokenizer(language)
[12-08-24 19:39:03.412454 ] [rank4]:   File "/tmp/.tox/t5small/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1744, in {}init{}
[12-08-24 19:39:03.412459 ] [rank4]:     self.load_lang(lang)
[12-08-24 19:39:03.412463 ] [rank4]:   File "/tmp/.tox/t5small/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
[12-08-24 19:39:03.412467 ] [rank4]:     lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
[12-08-24 19:39:03.412472 ] [rank4]:   File "/tmp/.tox/t5small/lib/python3.10/site-packages/nltk/data.py", line 582, in find
[12-08-24 19:39:03.412476 ] [rank4]:     raise LookupError(resource_not_found)
[12-08-24 19:39:03.412481 ] [rank4]: LookupError:
[12-08-24 19:39:03.412485 ] [rank4]: **********************************************************************
[12-08-24 19:39:03.412489 ] [rank4]:   Resource [[93mpunkt_tab[[0m not found.
[12-08-24 19:39:03.412494 ] [rank4]:   Please use the NLTK Downloader to obtain the resource:
[12-08-24 19:39:03.412498 ]
[12-08-24 19:39:03.412502 ] [rank4]:   ^[[31m>>> import nltk
[12-08-24 19:39:03.412507 ] [rank4]:   >>> nltk.download('punkt_tab')
```
## Tests 
I have ran 3 failed CI tests, and all passed the error 
```

GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_encoder_decoder.py -s -v -k test_text_summarization_bf16[token0-facebook/bart-large-cnn-Habana/bart-3.9-28.9801-2-2]

============================================================================================= 1 passed, 5 deselected in 94.22s (0:01:34) ==============================================================================================

GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_encoder_decoder.py -s -v -k  test_text_summarization_bf16[token0-t5-3b-Habana/t5-2.955-21.8877-2-1] 

============================================================================================= 1 passed, 5 deselected in 146.54s (0:02:26) =============================================================================================

GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_examples.py -s -v -k test_run_summarization_t5-small_multi_card

======================================================================================================= short test summary info =======================================================================================================
FAILED tests/test_examples.py::MultiCardSummarizationExampleTester::test_run_summarization_t5-small_multi_card - AssertionError: 102.18 not greater than or equal to 110.65599999999999 : for metric eval_samples_per_second.
============================================================================================ 1 failed, 55 deselected in 362.99s (0:06:02) ======
```

Fixes # (issue)
Seems to be originated from https://github.com/Unstructured-IO/unstructured/pull/3512/files
SW_196667

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by imangohari1** [comment]
@shepark Could you do a quick sanity check on this?

**Comment by shepark** [comment]
> @shepark Could you do a quick sanity check on this?

done, it's working. thanks.

**Review by shepark — APPROVED** [review]

**Review by regisss — APPROVED** [review]

**Comment by regisss** [comment]
We'll have to upgrade `nltk` at some point: https://github.com/huggingface/optimum-habana/security/dependabot/22
We should probably add `nltk.download('punkt_tab')` to the summarization example, WDYT @imangohari1 ?

**Comment by imangohari1** [comment]
> We'll have to upgrade `nltk` at some point: https://github.com/huggingface/optimum-habana/security/dependabot/22 We should probably add `nltk.download('punkt_tab')` to the summarization example, WDYT @imangohari1 ?

I agree that we need to bump the version. 
Here is the changes based on that and adding `nltk.download('punkt_tab')
https://github.com/huggingface/optimum-habana/compare/main...imangohari1:optimum-habana:ig/sw_196667-nltk-part2?expand=1

I did a quick sanity check and it appears working.
```
python run_summarization.py --model_name_or_path t5-small --gaudi_config_name Habana/t5 --dataset_name cnn_dailymail --do_train --output_dir /tmp/tmpwm1nk3lh --overwrite_output_dir --learning_rate 0.0002 --per_device_train_batch_size 32 --per_device_eval_batch_size 4 --num_train_epochs 1 --use_habana --throughput_warmup_steps 3 --save_strategy no --use_lazy_mode --do_eval --dataset_config "3.0.0" --source_prefix "summarize: " --predict_with_generate --ignore_pad_token_for_loss False --pad_to_max_length --use_hpu_graphs_for_inference --save_strategy no --max_steps 500
```
```
{'train_runtime': 71.8138, 'train_samples_per_second': 251.176, 'train_steps_per_second': 7.849, 'train_loss': 1.2163092041015624, 'epoch': 0.06, 'memory_allocated (GB)': 8.68, 'max_memory_allocated (GB)': 94.62, 'total_memory_available (GB)': 94.62}
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [01:11<00:00,  6.96it/s]
[INFO|trainer.py:1658] 2024-08-14 23:50:37,054 >> Saving model checkpoint to /tmp/tmpwm1nk3lh
[INFO|configuration_utils.py:472] 2024-08-14 23:50:37,308 >> Configuration saved in /tmp/tmpwm1nk3lh/config.json
[INFO|configuration_utils.py:807] 2024-08-14 23:50:37,309 >> Configuration saved in /tmp/tmpwm1nk3lh/generation_config.json
[INFO|modeling_utils.py:2765] 2024-08-14 23:50:38,102 >> Model weights saved in /tmp/tmpwm1nk3lh/model.safetensors
[INFO|tokenization_utils_base.py:2702] 2024-08-14 23:50:38,104 >> tokenizer config file saved in /tmp/tmpwm1nk3lh/tokenizer_config.json
[INFO|tokenization_utils_base.py:2711] 2024-08-14 23:50:38,104 >> Special tokens file saved in /tmp/tmpwm1nk3lh/special_tokens_map.json
[INFO|tokenization_t5_fast.py:175] 2024-08-14 23:50:38,111 >> Copy vocab file to /tmp/tmpwm1nk3lh/spiece.model
[INFO|configuration_utils.py:125] 2024-08-14 23:50:38,118 >> Configuration saved in /tmp/tmpwm1nk3lh/gaudi_config.json
***** train metrics *****
  epoch                       =     0.0557
  max_memory_allocated (GB)   =      94.62
  memory_allocated (GB)       =       8.68
  total_flos                  =  4033500GF
  total_memory_available (GB) =      94.62
  train_loss                  =     1.2163
  train_runtime               = 0:01:11.81
  train_samples               =     287113
  train_samples_per_second    =    251.176
  train_steps_per_second      =      7.849
08/14/2024 23:50:38 - INFO - __main__ - *** Evaluate ***
[INFO|trainer.py:1812] 2024-08-14 23:50:38,123 >> Using HPU graphs for inference.
[INFO|trainer.py:1830] 2024-08-14 23:50:38,123 >>
***** Running Evaluation *****
[INFO|trainer.py:1832] 2024-08-14 23:50:38,123 >>   Num examples = 13368
[INFO|trainer.py:1835] 2024-08-14 23:50:38,123 >>   Batch size = 4
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3342/3342 [11:14<00:00,  4.88it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3342/3342 [18:51<00:00,  2.95it/s]
***** eval metrics *****
  epoch                       =     0.0557
  eval_gen_len                =    75.9402
  eval_loss                   =     1.1929
  eval_rouge1                 =    41.0229
  eval_rouge2                 =     18.655
  eval_rougeL                 =    28.9673
  eval_rougeLsum              =    38.1536
  eval_runtime                = 0:18:53.93
  eval_samples                =      13368
  eval_samples_per_second     =     11.812
  eval_steps_per_second       =      2.953
  max_memory_allocated (GB)   =      94.62
  memory_allocated (GB)       =       9.05
  total_memory_available (GB) =      94.62
```
if this works better, I can do more testing and open a followup PR. WDYT @regisss ?

**Comment by regisss** [comment]
Yep that sounds good to me @imangohari1

**Comment by imangohari1** [comment]
> Yep that sounds good to me @imangohari1

Perfect! I did more testings and they all looked fine. 
PR Opened: https://github.com/huggingface/optimum-habana/pull/1258

**Pull request merged**
