### PR TITLE
Set KV Cache update as static method

### PR DESCRIPTION
**Pull request by ulivne**
This solves torch compile issue related to using self argument in HQT patched module

### CODE REVIEW

**Comment by yafshar** [comment]
@ulivne can you point to the issue if it is filed. Or provide more details on how to reproduce the issue?

**Comment by ulivne** [comment]
> @ulivne can you point to the issue if it is filed. Or provide more details on how to reproduce the issue?

The issue was internal to Habana SW stack during enablement of torch.compile usage.
The issue is that the HQT uses  different module for KVCache quantization, and torch.compile triggers graph break due to usage in different 'self' argument (log - "... mismatch for bound method.. ").
Setting the update method as static solved this, and also there is no need for this method to be  non-static as it not uses any class members.

**Comment by yafshar** [comment]
@ulivne thanks. I pointed out your comment in this [PR 1148](https://github.com/huggingface/optimum-habana/pull/1148) 
Does it makes sense to close this PR and have everything there?

**Comment by ulivne** [comment]
> @ulivne thanks. I pointed out your comment in this [PR 1148](https://github.com/huggingface/optimum-habana/pull/1148) Does it makes sense to close this PR and have everything there?

Yes it make sense to me.
i will close this PR once the PR 1148 is merged

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
