### PR TITLE
Add load_meta_device option to reduce host RAM

### PR DESCRIPTION
**Pull request by jiminha**
# What does this PR do?
Add --load_meta_device option to reduce host RAM for falcon40b

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
Nice! Would that work for Llama too?

**Comment by jiminha** [comment]
> Nice! Would that work for Llama too?

**Comment by regisss** [comment]
Perf degradation is weird, that should not happen. I'm going to take a look at it, I'm suspecting something with PEFT.

**Review by libinta — APPROVED** [review]

**Comment by regisss** [comment]
Actually perf degradation is expected. What happens here, when using `device_map`, is that the model is split across devices and then naive pipeline parallelism is performed. Hence the drop in performance.
@jiminha Have you tried other device map policies like `"balanced"` and `"sequential"`?

**Comment by regisss** [comment]
"balanced" and "sequential" both gives better throughput but I didn't monitor the host memory usage

**Comment by regisss** [comment]
Hmm okay nevermind, using "balanced" and "sequential" doesn't help in terms of memory

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
