### PR TITLE
In peft, only the trainable parameters need to be saved

### PR DESCRIPTION
**Pull request by sywangyi**
to reduce the storage size and also save the time of checkpoint saving while using deepspeed for training

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
https://github.com/huggingface/transformers/pull/27825

**Comment by regisss** [comment]
It looks good to me! Let's wait for it to be merged into Transformers before merging here in case some modifications are needed.

**Review by libinta — COMMENTED** [review]
@sywangyi  how do you validate the saved checkpoint?

**Comment by sywangyi** [comment]
I usually track the wandb log, comparing with the result from A100. DPO is simple, For PPO, I do find some issue and fix it in TRL for habana

**Review by regisss — APPROVED** [review]

**Pull request merged**
