### PR TITLE
unset length penalty in summarization example

### PR DESCRIPTION
**Pull request by malkomes**
# What does this PR do?

It unsets the `length_penalty` value from the `generation_config`. 

Fixes # (issue)

When using the model `csebuetnlp/mT5_multilingual_XLSum` the user might see the following error:

```
ValueError: [UserWarning('`num_beams` is set to 1. However, `length_penalty` is set to `0.6` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.')]
```

Since  `length_penalty` is not an input for this example, we are going to unset it to avoid the conflict with  `num_beams`.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by ssarkar2 — COMMENTED** [review]
can u post the cmd line or test that exhibited the error that this PR is fixing, thanks

**Comment by malkomes** [comment]
Something like: 
```
python ../gaudi_spawn.py         --world_size 8 --use_mpi run_summarization.py         --model_name_or_path  csebuetnlp/mT5_multilingual_XLSum         --do_train         --do_eval         --dataset_name cnn_dailymail         --dataset_config 3.0.0         --source_prefix summarize:          --output_dir /tmp/tst-summarization         --per_device_train_batch_size 4         --per_device_eval_batch_size 4         --overwrite_output_dir         --predict_with_generate         --use_habana         --use_lazy_mode         --use_hpu_graphs_for_inference         --gaudi_config_name Habana/t5         --ignore_pad_token_for_loss False         --pad_to_max_length         --save_strategy epoch         --throughput_warmup_steps 3         --max_train_samples 100         --max_eval_samples 100         --do_predict         --num_beams 1         --max_predict_samples 100         --bf16
``` 
would have this issue.

**Review by ssarkar2 — APPROVED** [review]

**Comment by regisss** [comment]
@malkomes I think this has now been fixed by PR #1083 : https://github.com/huggingface/optimum-habana/blob/5660db6b21a123cd2d88805b5a2c1b7578b75173/examples/summarization/run_summarization.py#L768

Can you confirm it solves this issue?

**Comment by malkomes** [comment]
correct @regisss
This PR is now obsolete. Closing it

**Pull request closed without merging**
