### PR TITLE
add mistral support for generation

### PR DESCRIPTION
**Pull request by sywangyi**
add mistral static shape support for generation

### CODE REVIEW

**Comment by sywangyi** [comment]
based the implementation of mistral in transformers v4.34.1

**Comment by regisss** [comment]
Thanks for adding support for this popular model! I'll review this in the beginning of next week :slightly_smiling_face:

**Review by regisss — COMMENTED** [review]
LGTM!
Could you check if the model runs faster when removing all mentions to `padding_mask` please? I observed that with Llama.

**Comment by sywangyi** [comment]
Hi, @regisss , I use https://huggingface.co/mistralai/Mistral-7B-v0.1 for test, and _flash_attn_2_enabled is not set in config, so padding_mask is not used.

**Review by regisss — APPROVED** [review]
@sywangyi I just added CI baselines for Gaudi and Gaudi2 and I'll merge once the CI is done

**Pull request merged**
