### PR TITLE
Revert common KVCache not to check token_idx

### PR DESCRIPTION
**Pull request by jiminha**
# What does this PR do?

Fixed common KVCache code NOT to have token_idx check to fix lm_eval with reuse_cache. (Readme validation). 
Added LlamaKVCache to have token_idx check handle llama prompt finetuning. 

Fixes # (issue)
Command for Falcon180b, Phi lm_Eval from Readme(https://github.com/huggingface/optimum-habana/blob/main/examples/text-generation/README.md#running-with-fp8) is failing
Command:
```
python run_lm_eval.py -o falcon.eval --model_name_or_path tiiuae/falcon-7B --use_hpu_graphs --use_kv_cache --trim_logits --batch_size 1 --bf16 --reuse_cache --use_flash_attention --flash_attention_recompute --flash_attention_causal_mask
```
Error 
```
2024-12-12 17:55:48.844] [COMPLEXGUID_LIB] [error] 'tpckernel.sdpa_recomp_core_fwd' op Broadcast of shape [1, 1, 384, 384] not possible at index 3. Dimension 384 incompatible with output shape dimension 769Broadcast of shape [1, 1, 384, 384] not possible at index 3. Dimension 384 incompatible with output shape dimension 769
[17:55:48.845182][SYN_RECIPE    ][error][tid:3635] compileGraph: Can not compile graph
[17:55:48.845204][SYN_RECIPE    ][error][tid:3635] addRecipeHandleAndCompileGraph: Can not compile
[17:55:48.845215][SYN_API       ][error][tid:3635] compileGraph: Failed to add recipe handle into Recipe-Singleton status 26[synFail]
[17:55:48.845224][SYN_API       ][error][tid:3635] synGraphCompile: SYN_API_CALL failed status: 26[synFail]. graphHandle 0x55812f4a6ce0
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by jiminha** [comment]
@ssarkar2  @sywangyi  @regisss  Please review. I'm running a few more test, but if there is better way to do it, please also comment here.

**Comment by regisss** [comment]
A couple of questions:
- Why not checking if we are currently training instead of checking if the index is None?
- If Llama also raises an error, how does that PR solve it? Since the implementation for Llama would still be the same

**Comment by sywangyi** [comment]
I will file a PR to fix llama case in lm eval.
there are three cases needed consideration
1.lm_eval case. not use model.generate. use model.forward. so token idx is None. if reuse_cache is used. self.cache is not None. prev.copy_(cur) should be used
2. generate case. token idx is not None.prev.copy_(cur) should be used as well.
3. other case. should use torch.cat (prefix tuning finetune and eval)

**Comment by jiminha** [comment]
> A couple of questions:
> 
> * Why not checking if we are currently training instead of checking if the index is None?
> * If Llama also raises an error, how does that PR solve it? Since the implementation for Llama would still be the same

Original commit was to solve all the issue(checking self.training), but we found further issue that's not working for all case(ex. eval during prompt finetuning), discussed further with Libin/Yi last night and decided that we will put the same code as v1.14 back to minimize the risk, and have Yi further look and fix all the cases.

**Comment by jiminha** [comment]
> @jiminha If you want a specific implementation for Llama, you could just define a new class that inherits from `KVCache` and overrides the right method:
> 
> ```python
> class LlamaKVCache(KVCache);
>     @staticmethod
>     def update(...)
>         ...
> ```
> 
> That way there is less duplicated code.

will update.

**Review by regisss — APPROVED** [review]

**Pull request merged**
