### PR TITLE
enable `paligemma` model for image-to-text example

### PR DESCRIPTION
**Pull request by kaixuanliu**
replace #1304 as messed rebase history and file diffs

### CODE REVIEW

**Comment by kaixuanliu** [comment]
@yeonsily , @regisss pls help review. Related info pls refer to #1304

**Comment by kaixuanliu** [comment]
@libinta @mandy-li  , Can you help review? Thx~

**Comment by kaixuanliu** [comment]
@regisss , can you help review and merge it? I validated it just now again

**Comment by yao-matrix** [comment]
@libinta , Libing, this is originally for 1.18, pls help review, thx.

**Comment by kaixuanliu** [comment]
Verified with habana-1.19.0-410 build. 
Throughput comparison with A100:
| throught(tokens/s) | A100 | Gaudi2 |
|----------|----------|----------|
| BF16 |  55.37 | 132.83 |
| FP32 | 39.36 | 81.29 |

cmd line: 
`python3 run_pipeline.py --model_name_or_path google/paligemma-3b-mix-224 --use_hpu_graphs --bf16 --use_kv_cache`

**Review by ssarkar2 — APPROVED** [review]

**Pull request merged**
