### PR TITLE
Add the Llava_next support

### PR DESCRIPTION
**Pull request by yuanwu2017**
# What does this PR do?
Add the llava_next model support.

### llava-hf/llava-v1.6-mistral-7b-hf
**use_hpu_graphs is false** 
```
cd examples/image-to-text
python3 run_pipeline.py  \
          --model_name_or_path "llava-hf/llava-v1.6-mistral-7b-hf" \
          --image_path "https://github.com/haotian-liu/LLaVA/blob/1a91fc274d7c35a9b50b3cb29c4247ae5837ce39/images/llava_v1_5_radar.jpg?raw=true" \
          --prompt "[INST] <image>\nWhat is shown in this image? [/INST]" \
          --max_new_tokens 40  \
         --bf16
```
06/09/2024 03:54:14 - INFO - __main__ - result = [[{'generated_text': '[INST]  \\nWhat is shown in this image? [/INST] The image appears to be a radar chart, which is a type of multi-dimensional plot that displays data in the form of a two-dimensional chart of three or more quantitative variables represented on ax'}]], time = 1801.0545656085014ms, Throughput (including tokenization) = 22.20921051688718 tokens/second

`
**use_hpu_graphs is True** 
```
cd examples/image-to-text
python3 run_pipeline.py  \
          --model_name_or_path "llava-hf/llava-v1.6-mistral-7b-hf" \
          --image_path "https://github.com/haotian-liu/LLaVA/blob/1a91fc274d7c35a9b50b3cb29c4247ae5837ce39/images/llava_v1_5_radar.jpg?raw=true" \
          --prompt "[INST] <image>\nWhat is shown in this image? [/INST]" \
          --max_new_tokens 40  \
         --use_hpu_graphs \
         --bf16
```
06/09/2024 03:46:11 - INFO - __main__ - result = [[{'generated_text': '[INST]  \\nWhat is shown in this image? [/INST] The image appears to be a radar chart, which is a type of multi-dimensional plot that displays data in the form of a two-dimensional chart of three or more quantitative variables represented on ax'}]], time = 717.138490267098ms, Throughput (including tokenization) = 55.77723207284832 tokens/second
`

**A100**
```
python3 run_pipeline.py  \
          --model_name_or_path "llava-hf/llava-v1.6-mistral-7b-hf" \
          --image_path "https://github.com/haotian-liu/LLaVA/blob/1a91fc274d7c35a9b50b3cb29c4247ae5837ce39/images/llava_v1_5_radar.jpg?raw=true" \
          --prompt "[INST] <image>\nWhat is shown in this image? [/INST]" \
          --max_new_tokens 40
```
output:
`06/05/2024 18:36:18 - INFO - __main__ - result = [[{'generated_text': '[INST]  \\nWhat is shown in this image? [/INST] The image appears to be a radar chart, which is a type of multi-dimensional plot that displays data in the form of a two-dimensional chart of three or more quantitative variables represented on ax'}]], time = 4069.289055466652ms, Throughput (including tokenization) = 9.829726877294279 tokens/second`

### llava-hf/llava-v1.6-vicuna-13b-hf
```
cd examples/image-to-text
python3 run_pipeline.py  \
          --model_name_or_path "llava-hf/llava-v1.6-vicuna-13b-hf" \
          --image_path "https://github.com/haotian-liu/LLaVA/blob/1a91fc274d7c35a9b50b3cb29c4247ae5837ce39/images/llava_v1_5_radar.jpg?raw=true" \
          --prompt "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER: <image>\nWhat is shown in this image? ASSISTANT:" \
          --max_new_tokens 40  \
         --use_hpu_graphs \
         --bf16
```
output:
`06/09/2024 03:47:15 - INFO - __main__ - result = [[{'generated_text': "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER:  \\nWhat is shown in this image? ASSISTANT: The image appears to be a radar chart, also known as a spider chart or star chart, which is a graphical method of displaying multivariate data in the form of a two-"}]], time = 1155.8929964900017ms, Throughput (including tokenization) = 34.605279313452435 tokens/second
`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
@yuanwu2017 Nice! Is this PR still a draft or can I start reviewing it?

**Comment by yuanwu2017** [comment]
It is draft. Currently it outputs an eos at begin. I am debugging.

**Comment by yuanwu2017** [comment]
@regisss  Done. Please help to review.

**Comment by yuanwu2017** [comment]
@regisss Please help to review.

**Comment by regisss** [comment]
When I run
```
python3 /root/workspace/fork/examples/image-to-text/run_pipeline.py --model_name_or_path llava-hf/llava-v1.6-vicuna-13b-hf --batch_size 1 --max_new_tokens 20 --use_hpu_graphs --bf16 --output_dir /tmp/tmph1tuw7hl
```
I get this output:
```
result = [[{'generated_text': '[INST]  \nWhat is shown in this image? [/INST]'}]], time = 548.7263014540076ms, Throughput (including tokenization) = 36.44804330866639 tokens/second
```
It seems no output was generated after the question :thinking:

**Comment by yuanwu2017** [comment]
@regisss  The issue is caused by the different default prompt for llava-hf/llava-v1.6-vicuna-13b-hf. Previously I used the defualt prompt of llava-hf/llava-v1.6-mistral-7b-hf for llava-hf/llava-v1.6-vicuna-13b-hf. It outputs an eos at begin. After changing the default prompt . The output is ok.

`python3 run_pipeline.py --model_name_or_path llava-hf/llava-v1.6-vicuna-13b-hf --batch_size 1 --max_new_tokens 20 --use_hpu_graphs --bf16 --output_dir /tmp/tmph1tuw7hl`

output:
`06/11/2024 01:20:42 - INFO - __main__ - result = [[{'generated_text': "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER:  \nWhat is shown in this image? ASSISTANT: The image appears to be a radar chart, also known as a spider chart or star chart"}]], time = 843.9947042614222ms, Throughput (including tokenization) = 23.696831151922872 tokens/second`

**Review by regisss — APPROVED** [review]
LGTM!
You moved the process of merging images into inputs_embeds to not compute it in every forward call right?

**Pull request merged**
