### PR TITLE
revert of #411

### PR DESCRIPTION
**Pull request by kalyanjk**
Llama inference:temp fix for deepspeed@1.11.0 didn't enable num_key_v…

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
@kalyanjk Shouldn't we also remove the injection policy for Llama [here](https://github.com/huggingface/optimum-habana/blob/ca8ecde25b5508336173bcb92c0239683e39d0fc/examples/text-generation/checkpoint_utils.py#L129)?

**Comment by puneeshkhanna** [comment]
> @kalyanjk Shouldn't we also remove the injection policy for Llama [here](https://github.com/huggingface/optimum-habana/blob/ca8ecde25b5508336173bcb92c0239683e39d0fc/examples/text-generation/checkpoint_utils.py#L129)?

@regisss  - we will still need the injection policy for tensor parallelism.

**Comment by puneeshkhanna** [comment]
> > @kalyanjk Shouldn't we also remove the injection policy for Llama [here](https://github.com/huggingface/optimum-habana/blob/ca8ecde25b5508336173bcb92c0239683e39d0fc/examples/text-generation/checkpoint_utils.py#L129)?
> 
> @regisss - we will still need the injection policy for tensor parallelism.

https://github.com/HabanaAI/DeepSpeed/blob/main/deepspeed/module_inject/replace_module.py has the change now: child.num_key_value_heads = child.num_key_value_heads // mp_size

**Review by puneeshkhanna — APPROVED** [review]

**Review by regisss — APPROVED** [review]
LGTM!
This works only with DeepSpeed v1.12 right?

**Comment by regisss** [comment]
@kalyanjk Can you also run the following to get the code style check right please?
```
pip install --upgrade black ruff
make style
```

**Comment by kalyanjk** [comment]
> @kalyanjk Can you also run the following to get the code style check right please?
> 
> ```
> pip install --upgrade black ruff
> make style
> ```

Done

**Comment by regisss** [comment]
Let's wait for #453 to be merged (if DS 1.12 is needed) before merging this one

**Review by libinta — APPROVED** [review]

**Pull request merged**
