### PR TITLE
Optimized inference of XGLM model on HPU

### PR DESCRIPTION
**Pull request by XinyuYe-Intel**
# What does this PR do?

Optimized inference of XGLM model on HPU.

## Before submitting
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by libinta** [comment]
@XinyuYe-Intel  can you provide gaudi2 test on latest 1/17/1.18 docker RUN_SLOW=true GAUDI2_CI test and gaudi1 test result?

**Comment by XinyuYe-Intel** [comment]
> @XinyuYe-Intel can you provide gaudi2 test on latest 1/17/1.18 docker RUN_SLOW=true GAUDI2_CI test and gaudi1 test result?

perf on gaudi2 on 1.17.1 with RUN_SLOW=true is as below:
image

For gaudi1, I don't have the machine, so I can't provide the result.

**Review by ssarkar2 — COMMENTED** [review]
@XinyuYe-Intel could you please resolve the conflicts on this PR, looks good otherwise

**Comment by XinyuYe-Intel** [comment]
> @XinyuYe-Intel could you please resolve the conflicts on this PR, looks good otherwise

Resolved conflicts.

**Review by ssarkar2 — APPROVED** [review]

**Comment by libinta** [comment]
@XinyuYe-Intel  can you rebase?

**Comment by XinyuYe-Intel** [comment]
Tested this PR on FW 1.18.0
image

**Review by regisss — APPROVED** [review]

**Pull request merged**
