### PR TITLE
unify_measurements.py script support to unify PCQ 70B 8x

### PR DESCRIPTION
**Pull request by Yantom1**
Change-Id: Ia23b3049bd54dd18c8ae779e027901cf0cd1de8b

This PR supports a case we have measurements in PCQ mode and we have multi weights and outputs values

### CODE REVIEW

**Comment by regisss** [comment]
Please add a description to this PR to explain a bit its purpose as the title is not very explicit.

**Comment by Yantom1** [comment]
> Please add a description to this PR to explain a bit its purpose as the title is not very explicit.

done

**Comment by regisss** [comment]
Is this compatible with Synapse 1.17 ?
And sorry for my ignorance, what's PCQ mode?

**Comment by Yantom1** [comment]
> Is this compatible with Synapse 1.17 ? And sorry for my ignorance, what's PCQ mode?

it's not. PCQ is per channel quantization that means that each channel have its own quantization info.

**Review by regisss — APPROVED** [review]
LGTM!
Let's wait for the release of SynapseAI 1.18 to merge it.

**Pull request merged**
