### PR TITLE
Upgrade to diffusers 0.24

### PR DESCRIPTION
**Pull request by skavulya**
Upgrade to diffusers v0.24. Needed to add support for stable video diffusion. 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
@skavulya I'm actually working on enabling the latest versions of Transformers and Diffusers, I'll open the PR in the next few days and these changes will be there too. I'll try to push the branch today so that you can use it :slightly_smiling_face:

**Comment by skavulya** [comment]
Thanks @regisss I'm happy to hear that. I look forward to your PR.

**Comment by regisss** [comment]
@skavulya #651 was merged a couple of days ago so you should be able to use the latest stable release of Diffusers now

**Comment by skavulya** [comment]
Thanks @regisss

**Pull request closed without merging**
