### PR TITLE
Update the repo with changes brought by Transformers 4.19.1

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

Make the repo up to date with Transformers 4.19.1.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by libinta — COMMENTED** [review]
Regis, what's the test result? can we have sth like shared document to track test result for each release?

**Comment by regisss** [comment]
> Regis, what's the test result? can we have sth like shared document to track test result for each release?

I'm going to launch the regression tests manually on this branch to be sure that we keep the same performance. You'll be able to see if these tests have passed here (in the "Actions" tab).

**Comment by regisss** [comment]
@libinta You can see [here](https://github.com/huggingface/optimum-habana/actions/runs/2334625142) that all the regression tests passed.

**Review by libinta — COMMENTED** [review]
@regisss  is albert xxl running over saturday? what's the result?

**Review by libinta — APPROVED** [review]

**Comment by regisss** [comment]
> @regisss is albert xxl running over saturday? what's the result?

The CI run of Saturday skipped all regression tests since examples are not up to date in the main branch (checking if examples are up to date is the first test and if it fails all the following tests are skipped). But I ran it manually and it gave me the exact same results as before. Actually you can check it in the log files I sent you on Slack.

**Pull request merged**
