### PR TITLE
Fix setting of reuse cache

### PR DESCRIPTION
**Pull request by puneeshkhanna**
Reuse cache is independent of HPU graphs enablement. 
Remove forcefully setting reuse cache to False when HPU graphs is disabled.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by ssarkar2 — APPROVED** [review]

**Review by regisss — COMMENTED** [review]
LGTM!
Not sure why, but the code style check failed. Could you run the following to see if that helps?
```
pip install --upgrade black ruff
make style
```

**Comment by puneeshkhanna** [comment]
> pip install --upgrade black ruff

make style passes on my setup. Very strange with just removal of one line that it is failing in CI.

my setup results below:
All done! ✨ 🍰 ✨
196 files left unchanged

**Review by regisss — APPROVED** [review]
That's not the 1st time it produces different results on different setups, although that's rare. Weird. Anyway, I'll merge it once the tests have completed!

**Comment by puneeshkhanna** [comment]
Thanks @regisss  ; will check once more with the merged code.

**Comment by regisss** [comment]
I think there were some trailing spaces after `args.limit_hpu_graphs = False` that `black` didn't remove and that made the check fail.

**Pull request merged**
