### PR TITLE
Add Deepspeed zero3 configuration to run bloom-7b on Gaudi1

### PR DESCRIPTION
**Pull request by yeonsily**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by regisss — COMMENTED** [review]
Is this supposed to work with SynapseAI 1.13?
I just tried with 1.12 and I got a memory allocation error.

**Comment by yeonsily** [comment]
> Is this supposed to work with SynapseAI 1.13? I just tried with 1.12 and I got a memory allocation error.

Yes, we will have a fix for 1.13. I tested the code with the candidate fix so it works for 1.12 yet. I'm sorry to forget to mention it.
I think we should hold to merge this until 1.13 out? @libinta What do you think of it?

**Comment by regisss** [comment]
Sounds good to me, let's wait for the release of 1.13 to merge this PR :slightly_smiling_face:

**Comment by regisss** [comment]
@yeonsily @libinta Could you run this example with 1.13 and let me know the following metrics please so that I had it to the set of regression tests?
- Throughput
- Train runtime
- Perplexity

**Review by libinta — APPROVED** [review]

**Comment by yeonsily** [comment]
> @yeonsily @libinta Could you run this example with 1.13 and let me know the following metrics please so that I had it to the set of regression tests?
> 
> * Throughput
> * Train runtime
> * Perplexity

@regisss  This the batch 8 result.
train_runtime               = 0:25:53.70
train_samples_per_second    =      4.755

**Review by regisss — APPROVED** [review]
LGTM!
I also added a regression test to CI for Gaudi1 only.

**Pull request merged**
