### PR TITLE
Updating to avoid hardcoding tests in CI framework

### PR DESCRIPTION
**Pull request by vidyasiv**
# What does this PR do?
Updating script so it can be directly used by CI.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by vidyasiv** [comment]
@regisss , can you clarify why this was closed or was it a side effect of branch closure?
(cc: @libinta , @imangohari1 , @ZhengHongming888)

**Comment by regisss** [comment]
Arf I guess it was automatically closed by Github because the target branch (synapse_1.17) was deleted when I merged it into main.
Let me reopen.

**Comment by regisss** [comment]
@vidyasiv I reopened and changed the target branch to main.

**Comment by vidyasiv** [comment]
@ZhengHongming888 , please review

**Comment by ZhengHongming888** [comment]
yes it's passed from my side based on the updated script. So please move forward. Thanks.

**Review by ZhengHongming888 — APPROVED** [review]
Approved!

**Comment by vidyasiv** [comment]
@regisss , could you please take a look. @ZhengHongming888 helped update the tests and it has been tested to pass with transformers update.

**Review by regisss — APPROVED** [review]

**Pull request merged**
