### PR TITLE
Enable FusedRoPE for training in GPT-NeoX modeling

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

This PR enables FusedRoPE for training in GPT-NeoX modeling and FusedRMSNorm for training in T5 modeling.
It also adds a comment about OFI in the README of the multi-node example.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
I need to confirm that GPT-NeoX and T5 trainings work with these changes.

@mandy-li I updated the README of the multi-node example to make it clearer that OFI should only be used on DL1 instances. Let me know if that looks good to you.

**Comment by regisss** [comment]
Actually, is `HCCL_OVER_OFI` still needed since I see there is auto-detection? https://docs.habana.ai/en/latest/API_Reference_Guides/HCCL_APIs/Scale_Out_via_Host_NIC.html?highlight=nic#scale-out-auto-detection

**Comment by regisss** [comment]
Fine-tuning GPT-NeoX and Flan-T5-XXL on Gaudi2 work fine with these changes.
Cc @libinta

**Review by mandy-li — APPROVED** [review]
LGTM

**Comment by mandy-li** [comment]
> Actually, is `HCCL_OVER_OFI` still needed since I see there is auto-detection? https://docs.habana.ai/en/latest/API_Reference_Guides/HCCL_APIs/Scale_Out_via_Host_NIC.html?highlight=nic#scale-out-auto-detection

No, i don't think it is needed. Setting it will disable the auto-detection instead.

**Pull request merged**
