### PR TITLE
Support mixtral long sequence 32k with bs 2

### PR DESCRIPTION
**Pull request by jychen-habana**
# What does this PR do?

Support long sequences like 32000 with max **bs as 2** (slicing Q in attention).

**Short sequences**

**Comand**
```
QUANT_CONFIG=./quantization_config/maxabs_quant_mixtral.json python run_generation.py --model_name_or_path mistralai/Mixtral-8x7B-v0.1 --use_hpu_graphs --use_kv_cache --reuse_cache --bucket_internal --bucket_size 128 --max_new_tokens 256 --bf16 --fp8 --batch_size 32--max_input_tokens 128
```
**Before**
Stats:
Throughput (including tokenization) = **1221.6872883013737 tokens/second**
Number of HPU graphs                = 180
Memory allocated                    = 52.36 GB
Max memory allocated                = 52.45 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 216.56420183897717 seconds
**After**
Stats:
Throughput (including tokenization) = **1221.660746767456 tokens/second**
Number of HPU graphs                = 180
Memory allocated                    = 52.36 GB
Max memory allocated                = 52.45 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 336.15665312699275 seconds

**Long sequences (take 32000 as an example)**

**Comand (with --limit_hpu_graphs, --reuse_cache, --bucket_internal, --max_new_tokens 256)**
```
QUANT_CONFIG=./quantization_config/maxabs_quant_mixtral.json python run_generation.py --model_name_or_path ${MODEL_PATH} --use_hpu_graphs --limit_hpu_graphs --use_kv_cache --reuse_cache --bucket_internal --bucket_size 128 --max_new_tokens 256 --bf16 --fp8 --batch_size 2 --max_input_tokens 32000
```
**Before**
Out of Memory
**After**
input 2: ('He is working on',)
output 1: ('He is working on a new album, which is expected to be released in 2019.\n\n## Some Related Sentences\n\nHe and is\namazingly light on his feet for a big man ( six-two, 195 ) and has the balance of a cat.\nsaid that he would be making no more statements regarding their marriage until after the trial.\nhad stood up the best man anyone could have had for the job.\nsaid he had no objection to the plan as long as it provided for fair competition.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed',)
Stats:
Throughput (including tokenization) = **14.180683031899964 tokens/second**
Number of HPU graphs                = 435
Memory allocated                    = 72.93 GB
Max memory allocated                = 94.52 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 357.83802619494963 seconds

**Comand (with --limit_hpu_graphs --max_new_tokens 128)**
```
QUANT_CONFIG=./quantization_config/maxabs_quant_mixtral.json python run_generation.py --model_name_or_path ${MODEL_PATH} --use_hpu_graphs --limit_hpu_graphs --use_kv_cache --bucket_size 128 --max_new_tokens 128 --bf16 --fp8 --batch_size 2 --max_input_tokens 32000
```
**Before**
Out of Memory
**After**
input 2: ('He is working on',)
output 1: ('He is working on a new album, which is expected to be released in 2019.\n\n## Some Related Sentences\n\nHe and is\namazingly light on his feet for a big man ( six-two, 195 ) and has the balance of a cat.\nsaid that he would be making no more statements regarding their marriage until after the trial.\nhad stood up the best man anyone could have had for the job.\nsaid he had no objection to the plan as long as it provided for fair competition.\nhad been there when the first shot was fired, when the first man',)
Stats:
Throughput (including tokenization) = **7.876224914194412 tokens/second**
Number of HPU graphs                = 401
Memory allocated                    = 72.98 GB
Max memory allocated                = 94.53 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 332.56908493704395 seconds

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by jychen-habana** [comment]
Break PR https://github.com/huggingface/optimum-habana/pull/836 into small pieces, based on PR https://github.com/huggingface/optimum-habana/pull/898

**Comment by jychen-habana** [comment]
**Add test case input_32000 output_700**

**Command (with --limit_hpu_graphs, --reuse_cache, --bucket_internal, --bucket_size 256 --max_new_tokens 700)**
```
QUANT_CONFIG=./quantization_config/maxabs_quant_mixtral.json python run_generation.py --model_name_or_path mistralai/Mixtral-8x7B-v0.1 --use_hpu_graphs --limit_hpu_graphs --use_kv_cache --reuse_cache --bucket_internal --bucket_size 256 --max_new_tokens 700 --bf16 --fp8 --batch_size 2 --max_input_tokens 32000
```
input 2: ('He is working on',)
output 1: ('He is working on a new album, which is expected to be released in 2019.\n\n## Some Related Sentences\n\nHe and is\namazingly light on his feet for a big man ( six-two, 195 ) and has the balance of a cat.\nsaid that he would be making no more statements regarding their marriage until after the trial.\nhad stood up the best man anyone could have had for the job.\nsaid he had no objection to the plan as long as it provided for fair competition.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired, when the first man fell, and when the first woman screamed.\nhad been there when the first shot was fired,',)

Stats:
Throughput (including tokenization) = **28.744503090968127 tokens/second**
Number of HPU graphs                = 467
Memory allocated                    = 73.04 GB
Max memory allocated                = 94.59 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 395.94316271401476 seconds

**Comment by regisss** [comment]
@jychen-habana Is this PR different from #903 ?

**Review by libinta — COMMENTED** [review]
@jychen-habana can you abandon this if not needed?

**Comment by jychen-habana** [comment]
close

> @jychen-habana Is this PR different from #903 ?

#903 is the latest, I will close this PR

**Comment by jychen-habana** [comment]
close since #903 is merged

**Pull request closed without merging**
