### PR TITLE
Optimized inference of Cohere model on HPU

### PR DESCRIPTION
**Pull request by XinyuYe-Intel**
# What does this PR do?

Optimized inference of Cohere model on HPU.

## Before submitting
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by jiminha** [comment]
Can you provide the perf diff and accuracy value before/after this patch?

**Comment by XinyuYe-Intel** [comment]
> Can you provide the perf diff and accuracy value before/after this patch?

Below is the perf before the optimization:
image

and after  the optimization:
image

The command is:
```
python run_generation.py --model_name_or_path CohereForAI/c4ai-command-r-v01 --batch_size 1 --use_hpu_graphs  --bf16  --do_sample --use_kv_cache --token ...
```

**Comment by libinta** [comment]
@XinyuYe-Intel  can you rebase?

**Comment by XinyuYe-Intel** [comment]
> @XinyuYe-Intel can you rebase?

rebased.

**Comment by XinyuYe-Intel** [comment]
> @XinyuYe-Intel could you please resolve the conflicts on this PR, looks good otherwise

Resolved conflicts.

**Review by ssarkar2 — APPROVED** [review]

**Pull request merged**
