### PR TITLE
Fixed missing override _reorder_cache function

### PR DESCRIPTION
**Pull request by kplau1128**

### CODE REVIEW

**Comment by kplau1128** [comment]
This PR fixed missing `LlamaForCausalLM._reorder_cache` function caused CI test failed: (https://habana.atlassian.net/browse/HS-2931)

**Comment by regisss** [comment]
@kplau1128 We need to add it now because it was removed from Transformers right?

**Comment by kplau1128** [comment]
> @kplau1128 We need to add it now because it was removed from Transformers right?

Yes, looks like missing or removed from Transformers.

**Comment by kplau1128** [comment]
@regisss Is this PR okay for merge?

**Comment by libinta** [comment]
@kplau1128  we can close this PR as it's the same as https://github.com/huggingface/optimum-habana/pull/1233/files

**Pull request closed without merging**
