### PR TITLE
Enable fused rmsnorm in bf16 for llama

### PR DESCRIPTION
**Pull request by puneeshkhanna**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by puneeshkhanna** [comment]
@regisss  - please review. We can enable fused rmsnorm in lower precision too and this gives a boost in performance too.
See below table for improved perf results:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/puneeshk/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/puneeshk/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


70B 8x | BS | Max new tokens | Default Perf | Perf with rmsnorm fix | % Improvement over default perf
-- | -- | -- | -- | -- | --
  | 1 | 100 | 55.7 | 57.995 | 3.68
  | 40 | 100 | 1893.22 | 1969.95 | 3.5
  | 1 | 2048 | 60.53 | 62.19 | 2.58
  | 40 | 2048 | 1686.35 | 1726.47 | 2.5
  | 60 | 2048 | 2207.2 | 2256.79 | 2.2
  | 1 | 4096 | 59.825 | 61.4 | 2.48
  | 40 | 4096 | 1366.72 | 1393.36 | 1.95
  | 60 | 4096 | 1688.21 | 1716.64 | 1.74
7B 1x | 1 | 4096 | 124.147 | 126.8 | 2.15
  | 4 | 4096 | 354.48 | 357.28 | 0.8
13B 1x | 1 | 4096 | 68.86 | 69.79 | 1.37
  | 4 | 4096 | 203.77 | 204.89 | 0.56



</body>

</html>

**Comment by bgoldberg-habana** [comment]
LGTM, was also verified in FP8 runs.

**Review by bgoldberg-habana — APPROVED** [review]

**Review by dvarshney-habana — APPROVED** [review]

**Review by regisss — APPROVED** [review]
Nice! Does it generate the same outputs as before?

**Comment by mandy-li** [comment]
@regisss , let me check finetuning as well for perf and accuracy.

**Review by mandy-li — APPROVED** [review]

**Comment by puneeshkhanna** [comment]
@mandy-li - thanks for checking finetuning. I guess there were no issues there too. Did perf also improve in finetuning too ?
@regisss  - thanks for merging.

**Pull request merged**
