### PR TITLE
Update PEFT model example

### PR DESCRIPTION
**Pull request by jiminha**
# What does this PR do?
model trl-lib/llama-7b-se-rm-peft(one of example in text_generation example) is not compatible with peft v.0.6.0.
Change the example model to other llama-7b-peft model which doesn't use old config parameter. 

https://huggingface.co/trl-lib/llama-7b-se-rm-peft/discussions/3

### CODE REVIEW

**Review by libinta — APPROVED** [review]

**Comment by jiminha** [comment]
Instead of downgrading peft to v.0.5.0, just keep it to the latest, but modified the example peft model to other one which doesn't use old config parameters(enable_lora).

**Comment by regisss** [comment]
@jiminha I get the same error on Gaudi1 and Gaudi2 on SynapseAI 1.12 when using PEFT with Llama1-7b (I tried with other PEFT checkpoints too):
```
Traceback (most recent call last):
  File "run_generation.py", line 483, in <module>
    main()
  File "run_generation.py", line 287, in main
    generate()
  File "run_generation.py", line 268, in generate
    outputs = model.generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/generation/utils.py", line 797, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/generation/utils.py", line 1373, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 632, in forward
    return wrapped_hpugraph_forward(cache, stream, orig_fwd, args, kwargs, disable_tensor_cache, asynchronous, dry_run, max_graphs)
  File "/usr/local/lib/python3.8/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 516, in wrapped_hpugraph_forward
    graph.capture_end()
  File "/usr/local/lib/python3.8/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 41, in capture_end
    _hpu_C.capture_end(self.hpu_graph)
RuntimeError: synNodeCreateWithId failed for node: batch_gemm with synStatus 26 [Generice failure]. .
```

Does it work on 1.13?

**Comment by jiminha** [comment]
@regisss  I am seeing the same error that you are seeing on 1.12.  However it's working on 1.13.  Will check the error on 12 and update.

**Comment by jiminha** [comment]
1.12 + optimum_habana 1.8 - > no error 
1.13 + optimum_habana latest -> no error 
1.12 + optimum_habana latest + fp32 -> no error 
1.12 + optimum_habana latest + bf16 -> error seen with type mismatch(with batch_gemm arg1 not feed in as bf16, but as fp32). I'm still debugging to see what may cause this issue, but it might take a while to root-cause and have a fix. 

@regisss  if you want to try other model with 1.12 with latest optimum-habana branch, could you remove --bf16 and try it out?

**Comment by regisss** [comment]
@jiminha After rebasing this branch on main, it works!
However, this PEFT checkpoint produces nonsense (probably because it was made for Llama2 and not Llama1).
So I switched to Llama2 because most PEFT checkpoints are based on Llama2.
Let me know if that looks good to you :slightly_smiling_face:

**Comment by jiminha** [comment]
@regisss  Good to know that it's working!  yes your change looks good.

**Pull request merged**
