### PR TITLE
text-generation: improve output printing

### PR DESCRIPTION
**Pull request by mgonchar**
Improve numeration of output

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by mgonchar** [comment]
This makes output more logical.

before:
```
Input/outputs:
input 1: ('def print_hello_world():',)
output 1: ('def print_hello_world():\n    print("Hello, world!")\n\nprint_hello_world()\n,)

input 2: ('def print_hello_world():',)
output 1: ('def print_hello_world():\n    print("Hello, world!")\n\nprint_hello_world()\n,)

```

after (see the number for output):

```
Input/outputs:
input 1: ('def print_hello_world():',)
output 1.1: ('def print_hello_world():\n    print("Hello, world!")\n\nprint_hello_world()\n,)

input 2: ('def print_hello_world():',)
output 2.1: ('def print_hello_world():\n    print("Hello, world!")\n\nprint_hello_world()\n,)

```

**Comment by vidyasiv** [comment]
> @vidyasiv Would this impact the text generation accuracy test?

I don't think so.
@mgonchar can you please run `python -m pytest test_functional_text_generation_example.py` w/ your change to check?

**Comment by mgonchar** [comment]
@vidyasiv @jiminha this PR should not affect any test, I've only changed printing string inside script and doesn't touch real output from model

**Comment by mgonchar** [comment]
> > @vidyasiv Would this impact the text generation accuracy test?
> 
> I don't think so. @mgonchar can you please run `python -m pytest test_functional_text_generation_example.py` w/ your change to check?

Tested, everything worked fine, see output
```
============================================================================================================================================= test session starts =============================================================================================================================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /var/work/optimum-habana
configfile: setup.cfg
collected 7 items                                                                                                                                                                                                                                                                                             

test_functional_text_generation_example.py .......                                                                                                                                                                                                                                                      [100%]

============================================================================================================================================== warnings summary ===============================================================================================================================================
tests/test_functional_text_generation_example.py::test_text_generation_bf16_1x[token0-bigcode/starcoder]
  /usr/lib/python3.10/inspect.py:288: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
    return isinstance(object, types.FunctionType)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================================================================== 7 passed, 1 warning in 317.17s (0:05:17) ===================================================================================================================================
```

**Review by regisss — APPROVED** [review]

**Pull request merged**
