### PR TITLE
Change the device_id for FSDP plugin

### PR DESCRIPTION
**Pull request by ckvermaAI**
# What does this PR do?

1) Return a ``torch.device`` for the specified ``device_id`` (This change is required for FSDP).
2) Similar to CUDA variant [_get_device_from_device_id](https://github.com/pytorch/pytorch/blob/main/torch/distributed/fsdp/_init_utils.py#L795).  

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by vivekgoe** [comment]
@regisss @libinta This PR is needed for FSDP to work with Synapse 1.17.  Added new label "Synapse 1.17_dependency".

**Comment by yafshar** [comment]
@ckvermaAI @vivekgoe how do you test this PR. Is "hpu:X" notation is working as expected on 1.17.0?

**Comment by ckvermaAI** [comment]
@yafshar I've tested this PR for MPT (1B & 70B) in both eager & torch.compile **with FSDP**. I don't know the behavior of this API in allocating the tensor on a particular rank.

cc @vivekgoe

**Comment by vivekgoe** [comment]
@yafshar This change is applicable only for FSDP related code where some parts of the code expect hpu:X notation. For any other use-case, such as example you are trying, correct way is to use 'hpu' or 'hpu:0' irrespective of device id.

**Comment by yafshar** [comment]
> @yafshar I've tested this PR for MPT (1B & 70B) in both eager & torch.compile **with FSDP**. I don't know the behavior of this API in allocating the tensor on a particular rank.
> 
> cc @vivekgoe

@ckvermaAI can you add your testing command.

**Comment by yafshar** [comment]
> @yafshar This change is applicable only for FSDP related code where some parts of the code expect hpu:X notation. For any other use-case, such as example you are trying, correct way is to use 'hpu' or 'hpu:0' irrespective of device id.

@vivekgoe if the functionality is not available yet, then what difference does it make to use `device = torch.device("hpu", torch.hpu.current_device())` or `device = torch.device("hpu")`. It makes the current PR not useful for the current stack. Later you are right, it is necessary for FSDP, but now it does not use it! Am I missing st here?

**Comment by vivekgoe** [comment]
@yafshar Change in this PR is required to align with changes done to FSDP code changes in SynapseAI 1.17.0 release. I have added a label "Synapse 1.17_dependency" indicating the same, which means this should be merged only after SynapseAI 1.17.0 is available. Without these changes FSDP test-cases (such as https://github.com/huggingface/optimum-habana/blob/59d182dfa9a4c0ba068a1fd118b96b8ff0057c96/tests/test_examples.py#L793) will break. You can check this test with the PR once Synapse AI 1.17.0 is available.

**Comment by yafshar** [comment]
@vivekgoe I checked my simple example on 1.17.0 and it did not work, but will check this PR in the test FSDP and will update here

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
