### PR TITLE
Allocate KV cache in contiguous memory for HPU performance

### PR DESCRIPTION
**Pull request by puneeshkhanna**
Also update repeat KV logic when number of KV heads is 1 as the hidden states can be broadcasted during matmuls.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by polisettyvarma — APPROVED** [review]

**Review by dvarshney-habana — APPROVED** [review]

**Comment by mandy-li** [comment]
@puneeshkhanna , please provide performance measurement before/after this PR.

**Review by regisss — APPROVED** [review]
LGTM!

I ran a quick benchmark:
- Gaudi1 Llama-2 7B bf16
  - before: 44.10 tokens/s
  - after: 44.88 tokens/s
- Gaudi2 Llama-2 7B bf16
  - before: 140.80 tokens/s
  - after: 142.15 tokens/s
- Gaudi2 Llama-2 70B DS-inference 2 cards
  - before: 25.32 tokens/s
  - after: 25.75 tokens/s

Outputs are the same before and after in every case.

**Comment by puneeshkhanna** [comment]
@regisss  - thanks for merging. There will be very good performance boost with batch size scaling for all llama variants. Please check those cases too whenever you get a chance. 

Some numbers of 7B and 13B on 1x as below:
Llama 7B 
             baseline-> KV cache fix   -> KV cache fix + attn softmax BF16
BS-32   2460 -> 3137 tokens/sec -> 3243.76 tokens/sec
BS-64   3382 -> 4801 tokens/sec -> 5112 tokens/sec

Llama 13B
             baseline->  KV cache fix  -> KV cache fix + attn softmax BF16
BS-32   1416      -> 1760 tokens/sec -> 1812.85 tokens/sec

Please also review/merge https://github.com/huggingface/optimum-habana/pull/396.

**Comment by puneeshkhanna** [comment]
@regisss  - Just to add further, llama2 70b with 8x will also show considerable improvements with batching. Btw the fix which I did in repeat kv, maybe applicable generally to actual repeat kv code in transformers. What do you think ? I can push there too. If approved there, we can remove from here later.

**Comment by regisss** [comment]
@puneeshkhanna Sure, I think you can open a PR there and remove it from here when it is merged :slightly_smiling_face:

**Pull request merged**
