### PR TITLE
Include HF transformer model tests for gaudi devices

### PR DESCRIPTION
**Pull request by ankurneog**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by ankurneog** [comment]
This PR includes the model test cases found in : https://github.com/huggingface/transformers/tree/main/tests/models
and adapts them to run on Gaudi devices. Following models are included as part of this PR, the other supported models will be added in subsequent runs. This TCs runs the basic model functionality on a scaled down model which enables faster execution.
The eventual goal is to include these as part of our internal promote jobs so that regressions can be avoided.
Models Included in this PR : 
1. T5
2. GPT2
3. GPTJ
4. GPTNEOX
5. Bridgetower

Here is the current status of the run ( Ran on Gaudi coral simulator):
Optimum Habana Transformers : 

1. T5 : 
================================================================================== short test summary info ==================================================================================
FAILED test_modeling_t5.py::T5ModelTest::test_beam_sample_generate - NotImplementedError: Beam search sampling is not supported by optimum-habana yet.
FAILED test_modeling_t5.py::T5ModelTest::test_beam_sample_generate_dict_output - NotImplementedError: Beam search sampling is not supported by optimum-habana yet.
FAILED test_modeling_t5.py::T5ModelTest::test_beam_search_generate - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_beam_search_generate_dict_output - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_beam_search_generate_dict_outputs_use_cache - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_constrained_beam_search_generate - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_constrained_beam_search_generate_dict_output - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_generate_with_head_masking - RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_BRIDGE Exception in acc thread pool task has been thrown: Got a non-HPU tensor, expecting an HPU tensor
FAILED test_modeling_t5.py::T5ModelTest::test_generate_with_past_key_values - NotImplementedError: Beam search sampling is not supported by optimum-habana yet.
FAILED test_modeling_t5.py::T5ModelTest::test_greedy_generate - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_greedy_generate_dict_outputs - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_greedy_generate_dict_outputs_use_cache - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_group_beam_search_generate - NotImplementedError: Group beam search is not supported by optimum-habana yet.
FAILED test_modeling_t5.py::T5ModelTest::test_group_beam_search_generate_dict_output - NotImplementedError: Group beam search is not supported by optimum-habana yet.
FAILED test_modeling_t5.py::T5ModelTest::test_model_fp16_forward - RuntimeError: float16/half is not supported on Gaudi.
FAILED test_modeling_t5.py::T5ModelTest::test_resize_tokens_embeddings - AssertionError: ValueError not raised
FAILED test_modeling_t5.py::T5ModelTest::test_sample_generate - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5ModelTest::test_sample_generate_dict_output - KeyError: 'limit_hpu_graphs'
FAILED test_modeling_t5.py::T5EncoderOnlyModelTest::test_model_fp16_forward - RuntimeError: float16/half is not supported on Gaudi.
============================================================ 19 failed, 109 passed, 60 skipped, 31 warnings in 102.49s (0:01:42) ============================================================


2. GPT2

=================================================================================== short test summary info ====================================================================================
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_assisted_decoding_sample - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_beam_sample_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_beam_sample_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_beam_search_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_constrained_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_constrained_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_contrastive_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_contrastive_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_contrastive_generate_low_memory - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_generate_from_inputs_embeds_decoder_only - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_generate_without_input_ids - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_gpt2_token_classification_model - NameError: name 'GPT2ForTokenClassification' is not defined
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_greedy_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_greedy_generate_dict_outputs - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_greedy_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_group_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_group_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_pipeline_text_generation - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_resize_tokens_embeddings - AssertionError: ValueError not raised
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_sample_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_sample_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_torch_fx - AssertionError: Couldn't trace module: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.f...
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_torch_fx_output_loss - AssertionError: Couldn't trace module: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.f...
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_training - RuntimeError: Function torch::autograd::CppNode<LinearFunction> returned an invalid gradient at index 1 - expected device cpu but got hpu:0
FAILED test_modeling_gpt2.py::GPT2ModelTest::test_training_gradient_checkpointing - RuntimeError: Function torch::autograd::CppNode<LinearFunction> returned an invalid gradient at index 1 - expected device cpu but got hpu:0
============================================================== 27 failed, 49 passed, 51 skipped, 8 warnings in 113.34s (0:01:53) ==============================================================

3. GPTJ 

=================================================================================== short test summary info ====================================================================================
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_assisted_decoding_sample - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_beam_sample_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_beam_sample_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_beam_search_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_constrained_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_constrained_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_contrastive_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_contrastive_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_contrastive_generate_low_memory - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_generate_from_inputs_embeds_decoder_only - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_generate_without_input_ids - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_greedy_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_greedy_generate_dict_outputs - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_greedy_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_group_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_group_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_resize_tokens_embeddings - AssertionError: ValueError not raised
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_sample_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_sample_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_torch_fx - AssertionError: Couldn't trace module: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_torch_fx_output_loss - AssertionError: Couldn't trace module: 'len' is not supported in symbolic tracing by default. If you want this call to be recorded, please call torch.fx.wrap('len') at module scope
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_training - AttributeError: 'NoneType' object has no attribute 'backward'
FAILED gptj/test_modeling_gptj.py::GPTJModelTest::test_training_gradient_checkpointing - AttributeError: 'NoneType' object has no attribute 'backward'
=================================================================== 25 failed, 49 passed, 42 skipped, 14 warnings in 44.87s ====================================================================


4. GPTNEOX:

=================================================================================== short test summary info ====================================================================================
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_assisted_decoding_sample - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_beam_sample_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_beam_sample_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_beam_search_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_constrained_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_constrained_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_contrastive_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_contrastive_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_contrastive_generate_low_memory - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_decoder_model_past_large_inputs - RuntimeError: synNodeCreateWithId failed for node: rotary_pos_embedding_fwd_f32 with synStatus 26 [Generice failure]. .
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_generate_from_inputs_embeds_decoder_only - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_generate_without_input_ids - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_greedy_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_greedy_generate_dict_outputs - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_greedy_generate_dict_outputs_use_cache - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_group_beam_search_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_group_beam_search_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_model_rope_scaling_0_linear - RuntimeError: synNodeCreateWithId failed for node: rotary_pos_embedding_fwd_f32 with synStatus 26 [Generice failure]. .
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_model_rope_scaling_1_dynamic - RuntimeError: synNodeCreateWithId failed for node: rotary_pos_embedding_fwd_f32 with synStatus 26 [Generice failure]. .
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_resize_tokens_embeddings - AssertionError: ValueError not raised
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_sample_generate - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_sample_generate_dict_output - TypeError: pad(): argument 'pad' must be tuple of ints, but found element of type NoneType at pos 2
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_training - AttributeError: 'NoneType' object has no attribute 'backward'
FAILED gpt_neox/test_modeling_gpt_neox.py::GPTNeoXModelTest::test_training_gradient_checkpointing - AttributeError: 'NoneType' object has no attribute 'backward'
=================================================================== 26 failed, 52 passed, 37 skipped, 12 warnings in 32.90s ====================================================================

5. Bridgetower :
=================================================================================== short test summary info ====================================================================================
FAILED bridgetower/test_modeling_bridgetower.py::BridgeTowerModelTest::test_for_image_and_text_retrieval - RuntimeError: Input type (torch.FloatTensor) and weight type (HPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
FAILED bridgetower/test_modeling_bridgetower.py::BridgeTowerModelTest::test_for_masked_language_modeling - RuntimeError: Input type (torch.FloatTensor) and weight type (HPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
FAILED bridgetower/test_modeling_bridgetower.py::BridgeTowerModelTest::test_hidden_states_output - RuntimeError: Input type (torch.FloatTensor) and weight type (HPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
FAILED bridgetower/test_modeling_bridgetower.py::BridgeTowerModelTest::test_model - RuntimeError: Input type (torch.FloatTensor) and weight type (HPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
FAILED bridgetower/test_modeling_bridgetower.py::BridgeTowerModelTest::test_retain_grad_hidden_states_attentions - RuntimeError: Input type (torch.FloatTensor) and weight type (HPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
FAILED bridgetower/test_modeling_bridgetower.py::BridgeTowerModelTest::test_save_load - RuntimeError: Input type (torch.FloatTensor) and weight type (HPUFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
==================================================================== 6 failed, 33 passed, 48 skipped, 8 warnings in 26.39s =====================================================================

@regisss  , @ZhaiFeiyue  : please check and help with merging these, Thank you.

**Comment by regisss** [comment]
@ankurneog @ZhaiFeiyue Sure, it would be great to be able to run all the tests from Transformers. That being said, it will require a lot of time to adapt them to Optimum Habana as we cannot copy-paste them and expect them to pass as it is done in this PR (otherwise I would have done it a long time ago).

A few remarks after taking a quick look at the PR:
- Most errors reported here are not related to Optimum Habana. We cannot use Transformers on Gaudi as it is otherwise Optimum Habana would be pointless.
- I don't understand why TF and Flax tests were copy-pasted here, Optimum Habana doesn't support these frameworks.
- Pipelines are not officially supported. While they should work, they should not be part of the CI as it is not a priority to support them at the moment.
- Tests should not be implemented in `optimum/habana/` as they are not part of the source code.

So, while having all these tests here would be nice, I don't think that's a priority at the moment. Besides, I don't have an ETA for when we can enable them. As I said before, making sure tests are correctly implemented for Gaudi will take some time, and even more time to maintain for each Transformers release.
The best would be to have a PR open here (not from a fork) where we could be several to push so that we can advance faster. Let me discuss that with Sree and I'll give you an update.

**Comment by regisss** [comment]
> The intention was to take the content as is from the HF transformer repo , so that we can check the coverage in Gaudi, so instead of changing the TCs , we can mark them as skipped with a comment.

Okay, that sounds good. But I would still remove the test files with names that include `fp16` (not supported on Gaudi and never will be I guess) or `tf` and `flax` (not supported in Optimum Habana and it's not planned). Otherwise, users may think that we will add support for that later.

> Pipelines was copied as the test files uses it and it would need unnecessary refactoring.

At least the files in `tests/pipelines` should be removed, this should not require any refactoring.

> The directory structure was made similar to the HF transformer repo, so there is one to one match between the directory in the HF transformers/tests and optimum-habana transformers. Again the intention is to keep a single reference point ( HF transformers)

I understand that, but we cannot have these tests in the source code of the lib. Otherwise, users will be able to import from `optimum.habana.transformers.tests` and we don't want that.
To explain more:
- [`transformers/src/transformers`](https://github.com/huggingface/transformers/tree/main/src/transformers) corresponds to `optimum-habana/optimum/habana/transformers`
- [`transformers/tests`](https://github.com/huggingface/transformers/tree/main/tests) (note that these tests are not in `src` and thus are not part of the source code of the package) should correspond to `optimum-habana/tests/transformers` (there is currently no repo called `transformers` in `tests` but let's create it).

> We believe that this will greatly add value , since the runs are fast on the strip down model and we get to evaluate regressions in the ops. For eg: recent regression of segv in the GPTNeox model.

I'm sure it will, but I'm mainly saying that adding all those tests is not that straightforward and requires some time to maintain.

**Comment by ankurhabana** [comment]
Thanks @regisss on the details. 

Let me see if I can move the Content to optimum-habana/tests

As

optimum-habana/tests/transformers/tests/models

I will also check how I can address your other comments.

**Pull request closed without merging**
