### PR TITLE
BERT training migrated to torch.compile (#203)

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
README update for migrating to torch.compile

### CODE REVIEW

**Review by libinta — COMMENTED** [review]
@ANSHUMAN87  can you update https://github.com/huggingface/optimum-habana/blob/main/tests/test_examples.py with new added arguments and test result?

**Review by regisss — COMMENTED** [review]
Changes look good to me.
+1 with Libin's comment, please update the test accordingly.

**Comment by ANSHUMAN87** [comment]
I have updated the test case. Please review. Thanks!

JH...!

**Review by regisss — APPROVED** [review]

**Comment by ANSHUMAN87** [comment]
JH...!

**Pull request merged**
