### PR TITLE
Fix Starcoder2 language modeling support

### PR DESCRIPTION
**Pull request by vidyasiv**
# What does this PR do?

- Fixes support for Starcoder2 with language-modeling task that fails with:
     ```
      ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token`   `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
     ```

#### Test details (Multi Card run)
- Command:
```
mpirun -n 8 --bind-to core --map-by socket:PE=10 --rank-by core --report-bindings --allow-run-as-root \
/usr/bin/python3 <>/examples/language-modeling/run_lora_clm.py --model_name_or_path bigcode/starcoder2-3b \
--gaudi_config_name Habana/gpt2 \
--dataset_name timdettmers/openassistant-guanaco \
--do_train --output_dir /tmp/tmp8vbupg6u \
--overwrite_output_dir \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 4 \
--num_train_epochs 2 \
--use_habana \
--throughput_warmup_steps 3 \
--save_strategy no \
--use_lazy_mode \
--do_eval \
--dataset_concatenation \
--gradient_accumulation_steps 4 \
--bf16 True \
--num_train_epochs 2 \
--per_device_train_batch_size 2 \
--per_device_eval_batch_size 2 \
--gradient_accumulation_steps 4 \
--learning_rate 1e-4 \
--dataset_concatenation \
--use_habana \
--use_lazy_mode \
--throughput_warmup_steps 0 \
--lora_target_modules q_proj o_proj k_proj v_proj gate_proj up_proj down_proj \
--validation_split_percentage 10
```
- Output:
```
***** train metrics *****
  epoch                       =      1.9928
  max_memory_allocated (GB)   =       22.75
  memory_allocated (GB)       =       11.56
  total_flos                  = 145745136GF
  total_memory_available (GB) =       94.62
  train_loss                  =      2.4956
  train_runtime               =  0:04:27.67
  train_samples_per_second    =      66.208
  train_steps_per_second      =       1.031
06/10/2024 16:35:11 - INFO - __main__ -   *** Evaluate ***
[INFO|trainer.py:1779] 2024-06-10 16:35:11,651 >> ***** Running Evaluation *****
[INFO|trainer.py:1781] 2024-06-10 16:35:11,651 >>   Num examples = 518
[INFO|trainer.py:1784] 2024-06-10 16:35:11,651 >>   Batch size = 2
100%|██████████| 33/33 [00:01<00:00, 19.33it/s]***** eval metrics *****
  epoch                       =     1.9928
  eval_accuracy               =      0.429
  eval_loss                   =     1.5961
  eval_runtime                = 0:00:07.32
  eval_samples                =        518
  eval_samples_per_second     =     70.738
  eval_steps_per_second       =      4.506
  max_memory_allocated (GB)   =      22.75
  memory_allocated (GB)       =      11.56
  perplexity                  =     4.9335
  total_memory_available (GB) =      94.62
100%|██████████| 33/33 [00:03<00:00,  9.33it/s]
```
- Test result:
```
1 passed, 45 deselected in 325.10s (0:05:25) 
```

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
I cannot reproduce this error. Have you tried with an up-to-date main branch?

**Comment by vidyasiv** [comment]
> I cannot reproduce this error. Have you tried with an up-to-date main branch?

@regisss ,

ON main: commit 93f1fcf934d7b3b24cf0a0b9cac8e232af6ccc27

Command:
```
 python run_lora_clm.py \
    --model_name_or_path bigcode/starcoder2-7b \
    --dataset_name timdettmers/openassistant-guanaco \
    --bf16 True \
    --output_dir ./model_lora_starcoder2 \
    --num_train_epochs 2 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no"    \
    --save_strategy "steps"    \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 1e-4 \
    --logging_steps 1 \
    --dataset_concatenation \
    --do_train \
    --use_habana \
    --use_lazy_mode \
    --throughput_warmup_steps 0 \
    --lora_target_modules q_proj o_proj k_proj v_proj gate_proj up_proj down_proj
```

I see error
```
<snip>
[INFO|trainer.py:766] 2024-06-10 20:22:50,635 >> ***** Running training *****
[INFO|trainer.py:767] 2024-06-10 20:22:50,636 >>   Num examples = 6,663
[INFO|trainer.py:768] 2024-06-10 20:22:50,636 >>   Num Epochs = 2
[INFO|trainer.py:769] 2024-06-10 20:22:50,636 >>   Instantaneous batch size per device = 2
[INFO|trainer.py:772] 2024-06-10 20:22:50,636 >>   Total train batch size (w. parallel, distributed & accumulation) = 8
[INFO|trainer.py:773] 2024-06-10 20:22:50,636 >>   Gradient Accumulation steps = 4
[INFO|trainer.py:774] 2024-06-10 20:22:50,636 >>   Total optimization steps = 1,666
[INFO|trainer.py:775] 2024-06-10 20:22:50,641 >>   Number of trainable parameters = 7,340,032
  0%|                                                                                                                                                                                | 0/1666 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/vidyasiv_oh/examples/language-modeling/run_lora_clm.py", line 804, in <module>
    main()
  File "/root/vidyasiv_oh/examples/language-modeling/run_lora_clm.py", line 777, in main
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/root/vidyasiv_oh/optimum/habana/transformers/trainer.py", line 545, in train
    return inner_training_loop(
  File "/root/vidyasiv_oh/optimum/habana/transformers/trainer.py", line 910, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.10/dist-packages/transformers/data/data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "/usr/local/lib/python3.10/dist-packages/transformers/data/data_collator.py", line 761, in torch_call
    batch = pad_without_fast_tokenizer_warning(
  File "/usr/local/lib/python3.10/dist-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3315, in pad
    padding_strategy, _, max_length, _ = self._get_padding_truncation_strategies(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2763, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
```

**Comment by regisss** [comment]
With the 7b checkpoint, I can reproduce. That's a mistake in the generation config of the model, let me open a PR on the hub to fix it: https://huggingface.co/bigcode/starcoder2-7b/discussions/15

Can you confirm that it works with the 3b checkpoint?

**Comment by vidyasiv** [comment]
> With the 7b checkpoint, I can reproduce. That's a mistake in the generation config of the model, let me open a PR on the hub to fix it: https://huggingface.co/bigcode/starcoder2-7b/discussions/15
> 
> Can you confirm that it works with the 3b checkpoint?

@regisss , Yes it works with `bigcode/starcoder2-3b` and also `bigcode/starcoder2-15b`, thanks for the fix for 7b model!
I will close out this PR

**Comment by regisss** [comment]
@vidyasiv It should work now with the 7b checkpoint, let me know if you encounter any issue

**Pull request closed without merging**
