### PR TITLE
fix nan loss of gemma and crash if dataset_concatenation is not set

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
reproduce command:
HABANA_VISIBLE_MODULES="0,1,2,3" python ../gaudi_spawn.py --world_size 4 --use_mpi run_lora_clm.py --model_name_or_path google/gemma-7b-it --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --do_train --do_eval --num_train_epochs 15 --output_dir ./output/7b_4hpu_16bs_15ep --save_total_limit 1 --gaudi_config_name Habana/gpt2 --use_habana --gradient_checkpointing --throughput_warmup_steps 3 --bf16 --logging_strategy epoch --evaluation_strategy epoch --lora_target_modules "q_proj" "o_proj" "k_proj" "v_proj" "gate_proj" "up_proj" "down_proj" --lora_rank=8 --lora_alpha=16 --lora_dropout=0.05 --dataset_name mamamiya405/finred

**Comment by sywangyi** [comment]
Traceback (most recent call last):
  File "/optimum-habana/examples/language-modeling/run_lora_clm.py", line 837, in <module>
    main()
  File "/optimum-habana/examples/language-modeling/run_lora_clm.py", line 810, in main
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/optimum-habana/optimum/habana/transformers/trainer.py", line 545, in train
    return inner_training_loop(
  File "/optimum-habana/optimum/habana/transformers/trainer.py", line 910, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.10/dist-packages/transformers/data/data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "/usr/local/lib/python3.10/dist-packages/transformers/data/data_collator.py", line 760, in torch_call
    batch = pad_without_fast_tokenizer_warning(
  File "/usr/local/lib/python3.10/dist-packages/transformers/data/data_collator.py", line 65, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3355, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 224, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 775, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`labels` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
  0%|          | 0/2355 [00:00<?, ?it/s]

**Review by vidyasiv — CHANGES_REQUESTED** [review]
Suggest adding a test to capture this fix.

**Review by vidyasiv — APPROVED** [review]
Tests run for me but values are off, will defer to @regisss on this.

**Review by regisss — APPROVED** [review]

**Comment by regisss** [comment]
> Thank you @sywangyi . Tests run for me but values are off, will defer to @regisss on this.

What do you mean by "values are off"? High perplexity values?

**Comment by vidyasiv** [comment]
> > Thank you @sywangyi . Tests run for me but values are off, will defer to @regisss on this.
> 
> What do you mean by "values are off"? High perplexity values?

Yes the results I get are different:
```
tests/test_examples.py:598: in assert_no_regression
    assert_function(
E   AssertionError: 684.8237139522856 not less than or equal to 4.130192999999999 : for metric perplexity.
E   ===== Assessed metrics (measured vs thresholded baseline) =====
E   perplexity: 684.8237139522856 vs 4.130192999999999
E   train_runtime: 1155.3813 vs 1228.5
E   train_samples_per_second: 29.004 vs 26.753899999999998
tests/test_examples.py:598: in assert_no_regression
    assert_function(
E   AssertionError: 102781851684452.52 not less than or equal to 2.3901649999999997 : for metric perplexity.
E   ===== Assessed metrics (measured vs thresholded baseline) =====
E   perplexity: 102781851684452.52 vs 2.3901649999999997
E   train_runtime: 241.858 vs 309.299235
E   train_samples_per_second: 160.582 vs 140.68834999999999
====================================================================================== short test summary info =======================================================================================
FAILED tests/test_examples.py::MultiCardCausalLanguageModelingLORAExampleTester2::test_run_lora_clm_falcon-40b_multi_card - AssertionError: 684.8237139522856 not less than or equal to 4.130192999999999 : for metric perplexity.
FAILED tests/test_examples.py::MultiCardCausalLanguageModelingLORAExampleTester2::test_run_lora_clm_llama-7b_multi_card - AssertionError: 102781851684452.52 not less than or equal to 2.3901649999999997 : for metric perplexity.
```

**Comment by regisss** [comment]
That's weird :thinking: 
I got the expected values on my Gaudi2 instance with Synapse 1.16.0. Going to merge it and will revisit if I can reproduce such numbers :slightly_smiling_face:

**Comment by vidyasiv** [comment]
> That's weird 🤔 I got the expected values on my Gaudi2 instance with Synapse 1.16.0. Going to merge it and will revisit if I can reproduce such numbers 🙂

Thanks, if you see the tests pass it should be good. I need to figure why/when I get differing performance as this has happened before.

**Pull request merged**
