### PR TITLE
Add DynamicMoE support for Mixtral

### PR DESCRIPTION
**Pull request by kwisniewski98**
Add DynamicMoE support for Mixtral

### CODE REVIEW

**Comment by astachowiczhabana** [comment]
@libinta  this commit is required with next OH release

**Comment by Wei-Lin-Intel** [comment]
Please consider not to use such API with combined w1 and w3. In the future the dynamic MoE can also support for training, such method would change the weights ordering when saving the checkpoints.
The dynamic MoE can also support the separate call of w1, w2 and w3. It is not necessary to align with vLLM Mixtral.
`        
       final_hidden_states = torch.ops.hpu.mixture_of_experts(
                hidden_states=hidden_states,
                expert_routing_table=selected_experts,
                router_weights=routing_weights,
                w1=w1_list,
                w2=w3_list,
                w3=w2_list,
                permuted_weights=True,
                activation=act_fn,
                experts_min=0,
                experts_max=self.num_experts - 1
        )
`

**Comment by astachowiczhabana** [comment]
this is duplicate, sorry, my mistake

**Comment by kwisniewski98** [comment]
> Please consider not to use such API with combined w1 and w3. In the future the dynamic MoE can also support for training, such method would change the weights ordering when saving the checkpoints. The dynamic MoE can also support the separate call of w1, w2 and w3. It is not necessary to align with vLLM Mixtral. ` final_hidden_states = torch.ops.hpu.mixture_of_experts( hidden_states=hidden_states, expert_routing_table=selected_experts, router_weights=routing_weights, w1=w1_list, w2=w3_list, w3=w2_list, permuted_weights=True, activation=act_fn, experts_min=0, experts_max=self.num_experts - 1 )`

Done, I've used an op that you've suggested

**Comment by Wei-Lin-Intel** [comment]
LGTM, thanks

**Review by regisss — APPROVED** [review]
LGTM!
Have you checked if the Mixtral tests in https://github.com/huggingface/optimum-habana/blob/main/tests/test_text_generation_example.py all pass?

**Comment by hsubramony** [comment]
verified on 1.15-release branch with pytests for mixtral and all the tests passed

**Pull request merged**
