### PR TITLE
Upgrade to Transformers v4.31

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

Following #306 since it was accidentally merged.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by ZhaiFeiyue** [comment]
@regisss when will you merge this PR?

**Comment by fxmarty** [comment]
Hi @ZhaiFeiyue, @skaulintel, do you know why https://github.com/huggingface/optimum-habana/pull/306 was reverted? This PR looks identical. @regisss is away until 8th August, but I'm happy to have a look in the meantime.

**Comment by skaulintel** [comment]
@fxmarty Was not sure if it was adequately tested, so I reverted.

**Comment by regisss** [comment]
> @regisss when will you merge this PR?

@ZhaiFeiyue Will fix the merge conflicts and re-test, I think it should be merged by the beginning of next week

**Comment by regisss** [comment]
There are slight throughput regressions in distributed mode: https://github.com/huggingface/optimum-habana/actions/runs/5842182092/job/15843308550
Let's merge it first to have support for Transformers v4.31 and I'll investigate these regressions after.

**Pull request merged**
