### PR TITLE
Remove top_k_top_p_filtering funtion test as it's removed from

### PR DESCRIPTION
**Pull request by yeonsily**
transformer 4.40.0 release

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by MohitIntel — APPROVED** [review]
LGTM!

**Comment by regisss** [comment]
@yeonsily Is it the same as #1007 ?

**Comment by yeonsily** [comment]
> @yeonsily Is it the same as #1007 ?

Yes, @libinta wanted to have two separate PR for transformer_4.40 and transformer_4.40_fixes.

**Comment by yeonsily** [comment]
Merged by https://github.com/huggingface/optimum-habana/pull/1007

**Pull request closed without merging**
