### PR TITLE
Add transformers model tests for gaudi

### PR DESCRIPTION
**Pull request by ankurneog**
This PR adds the HF  transformers models tests found under :  
https://github.com/huggingface/transformers/tree/main/tests/models
to optimum-habana after adaptions to run on Gaudi devices.
The unsupported tests are marked as SKIPPED.
Some of the valid failed cases will be analyzed and will be skipped or fixed subsequently.
The intention is to include this tests as part of the Software CI promote jobs so that we could catch regressions.

These tests are intended to be housed in : 
https://github.com/huggingface/optimum-habana/tree/main/tests/transformers/tests/models

As part of this PR, the following models are included 
1. GPT2
2. GPTJ
3. GPTNEOX
4. Bridgetower
5. LLAMA
6. T5

Logs of the test runs are attached for reference.

This PR builds upon concerns pointed out  by @regisss in this PR : https://github.com/huggingface/optimum-habana/pull/420#issuecomment-1733556606

We will incrementally try to improve the content.
[bridgetower_modelling_tests_after_refactor.txt](https://github.com/huggingface/optimum-habana/files/12726754/bridgetower_modelling_tests_after_refactor.txt)
[gpt2_modelling_tests_after_refactor.txt](https://github.com/huggingface/optimum-habana/files/12726755/gpt2_modelling_tests_after_refactor.txt)
[gptj_modelling_tests_after_refactor.txt](https://github.com/huggingface/optimum-habana/files/12726757/gptj_modelling_tests_after_refactor.txt)
[gptneox_modelling_tests_after_refactor.txt](https://github.com/huggingface/optimum-habana/files/12726758/gptneox_modelling_tests_after_refactor.txt)
[llama_modelling_tests_after_refactor.txt](https://github.com/huggingface/optimum-habana/files/12726759/llama_modelling_tests_after_refactor.txt)
[t5_modelling_tests_after_refactor.txt](https://github.com/huggingface/optimum-habana/files/12726760/t5_modelling_tests_after_refactor.txt)

@regisss  : Could you have a look and provide your feedback.

### CODE REVIEW

**Comment by regisss** [comment]
@ankurneog I see there are as many files in this PR as in the other one. Could you remove all the fp16, TF, Flax and `tests/pipelines` tests as pointed out in [this comment](https://github.com/huggingface/optimum-habana/pull/420#issuecomment-1733556606) please?

**Comment by ankurneog** [comment]
@regisss  : sorry i missed that, Have addressed in the latest upload. thank you

**Review by regisss — COMMENTED** [review]
It looks good to me @ankurneog ! Let's just get the code style check right before merging please:
```
pip install --upgrade black ruff
make style
```

Also, I guess I can close this former PR right? https://github.com/huggingface/optimum-habana/pull/420

**Comment by ankurneog** [comment]
@regisss  : Thanks, Have reuploaded after addressing code style check errors.  
https://github.com/huggingface/optimum-habana/compare/1aa8ee918370cc600db23d394c44e00af767179b..e2957fe4e7b80f3316b737eef2073ebe79cc705a
Yes we can close 
https://github.com/huggingface/optimum-habana/pull/420

**Pull request merged**
