### PR TITLE
[wav2vec2] Remove tensor.item and dynamic slicing operations in the loop that cause graph break

### PR DESCRIPTION
**Pull request by chaojun-zhang**
# What does this PR do?

Remove tensor.item and dynamic slicing operations in the loop that cause graph break

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by astachowiczhabana** [comment]
@libinta  this commit is required with next OH release

**Comment by imangohari1** [comment]
@chaojun-zhang  CC: @astachowiczhabana 
Can you please run the following tests with and without these changes so we can make sure these are not introducing regressions? Thanks. 
```
GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/wav2vec2/ -s -v
```
```
GAUDI2_CI=1 RUN_SLOW=true python -m  pytest tests/test_examples.py -v -s -k  python -m pytest tests/test_examples.py -v -s -k  test_run_audio_classification_wav2vec2-base_multi_card
```
```
GAUDI2_CI=1 RUN_SLOW=true python -m  python -m pytest tests/test_examples.py -v -s -k test_run_speech_recognition_ctc_wav2vec2-large-lv60_multi_card
```

**Review by imangohari1 — CHANGES_REQUESTED** [review]
> @chaojun-zhang CC: @astachowiczhabana Can you please run the following tests with and without these changes so we can make sure these are not introducing regressions? Thanks.
> 
> ```
> GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/wav2vec2/ -s -v
> ```
> 
> ```
> GAUDI2_CI=1 RUN_SLOW=true python -m  pytest tests/test_examples.py -v -s -k  test_run_audio_classification_wav2vec2-base_multi_card
> ```
> 
> ```
> GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/test_examples.py -v -s -k test_run_speech_recognition_ctc_wav2vec2-large-lv60_multi_card
> ```

@chaojun-zhang 
I ran these tests and one of them is failing compared to main. 
`GAUDI2_CI=1 RUN_SLOW=true python -m  pytest tests/test_examples.py -v -s -k  test_run_audio_classification_wav2vec2-base_multi_card` 
with current changes shows
```
E   eval_accuracy: 0.7394701086956522 vs 0.715572
E   train_runtime: 201.5022 vs 66.578295
E   train_samples_per_second: 703.581 vs 2827.0517999999997
E   eval_samples_per_second: 308.74 vs 3458.01995
```
and without shows:
```
E   eval_accuracy: 0.7338654891304348 vs 0.715572
E   train_runtime: 79.2719 vs 66.578295
E   train_samples_per_second: 2731.957 vs 2827.0517999999997
E   eval_samples_per_second: 2812.678 vs 3458.01995
```

We need to understand what is casuing the perf desegregation on this.

**Comment by jiminha** [comment]
@astachowiczhabana  Could you also check above?

**Comment by chaojun-zhang** [comment]
> GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/test_examples.py -v -s -k test_run_audio_classification_wav2vec2-base_multi_card

@imangohari1 , i have run this test, you can see train perf is better than the main.
- with change :

***** train metrics *****
  epoch                       =          5.0
  max_memory_allocated (GB)   =        90.68
  memory_allocated (GB)       =        14.32
  total_flos                  = 7533391360GF
  total_memory_available (GB) =        94.62
  train_loss                  =       1.5733
  train_runtime               =   0:01:03.22
  train_samples_per_second    =     3226.165
  train_steps_per_second      =       12.647
[INFO|trainer.py:1880] 2024-11-28 07:49:32,852 >> Using HPU graphs for inference.
[INFO|trainer.py:1898] 2024-11-28 07:49:32,852 >>
***** Running Evaluation *****
[INFO|trainer.py:1900] 2024-11-28 07:49:32,852 >>   Num examples = 5888
[INFO|trainer.py:1903] 2024-11-28 07:49:32,852 >>   Batch size = 64
100%|██████████| 12/12 [00:01<00:00, 11.80it/s]
***** eval metrics *****
  epoch                           =        5.0
  eval_accuracy                   =       0.74
  eval_graph_compliation_duration =    13.4721
  eval_loss                       =      1.047
  eval_runtime                    = 0:00:14.37
  eval_samples_per_second         =   4849.252
  eval_steps_per_second           =     10.028
  max_memory_allocated (GB)       =      90.68
  memory_allocated (GB)           =       16.7
  total_memory_available (GB)     =      94.62


- without change 

***** train metrics *****
  epoch                       =          5.0
  max_memory_allocated (GB)   =        92.54
  memory_allocated (GB)       =        14.42
  total_flos                  = 7533391360GF
  total_memory_available (GB) =        94.62
  train_loss                  =       1.6052
  train_runtime               =   0:01:01.27
  train_samples_per_second    =     3189.578
  train_steps_per_second      =       12.503
[INFO|trainer.py:1880] 2024-11-28 07:54:54,032 >> Using HPU graphs for inference.
[INFO|trainer.py:1898] 2024-11-28 07:54:54,032 >>
***** Running Evaluation *****
[INFO|trainer.py:1900] 2024-11-28 07:54:54,032 >>   Num examples = 5888
[INFO|trainer.py:1903] 2024-11-28 07:54:54,032 >>   Batch size = 64
 92%|█████████▏| 11/12 [00:00<00:00, 14.99it/s]***** eval metrics *****
  epoch                           =        5.0
  eval_accuracy                   =     0.7286
  eval_graph_compliation_duration =    13.4677
  eval_loss                       =     1.0738
  eval_runtime                    = 0:00:14.26
  eval_samples_per_second         =   5439.068
  eval_steps_per_second           =     11.248
  max_memory_allocated (GB)       =      92.54
  memory_allocated (GB)           =      16.79
  total_memory_available (GB)     =      94.62

**Review by astachowiczhabana — APPROVED** [review]

**Review by regisss — APPROVED** [review]
LGTM!

@imangohari1 The test where you saw degradation was performed with SynapseAI v1.18 right? I'll probably wait till v1.19 is released to merge this one.

**Comment by regisss** [comment]
I merged it into the release branch so that it doesn't affect the main branch.
@chaojun-zhang Any insights on the results @imangohari1 got?

**Comment by imangohari1** [comment]
> I merged it into the release branch so that it doesn't affect the main branch. @chaojun-zhang Any insights on the results @imangohari1 got?

 reran this on another server and still failed. @chaojun-zhang  Please share what exact 1.19 build this is supposed to pass on. Tnx.

**Pull request merged**
