### PR TITLE
Remove unnecessary neural compressor fix for 1.19 release

### PR DESCRIPTION
**Pull request by jiminha**
# What does this PR do?

Remove temporary fixes on neural compressor logic that we added to support Synapse 1.18
This code no longer needed for Synapse1.19

### CODE REVIEW

**Comment by jiminha** [comment]
Test in progress, do not merge yet.

**Comment by jiminha** [comment]
@xin3he  Please review.

**Review by xin3he — APPROVED** [review]
Great, thanks.

**Comment by xin3he** [comment]
@HolyFalafel Do you know the status of these variables to be removed? [link](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation#:~:text=Additionally%2C%20the%20below%20env%20vars%20are%20used%20for%20performance%20optimizations%2C%20and%20are%20planned%20to%20be%20removed%20in%20future%20version%3A%20SRAM_SLICER_SHARED_MME_INPUT_EXPANSION_ENABLED%3Dfalse%20ENABLE_EXPERIMENTAL_FLAGS%3D1)

**Comment by jiminha** [comment]
> Hi @HolyFalafel, @astachowiczhabana Do you know the status of these variables to be removed? [link](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation#:~:text=Additionally%2C%20the%20below%20env%20vars%20are%20used%20for%20performance%20optimizations%2C%20and%20are%20planned%20to%20be%20removed%20in%20future%20version%3A%20SRAM_SLICER_SHARED_MME_INPUT_EXPANSION_ENABLED%3Dfalse%20ENABLE_EXPERIMENTAL_FLAGS%3D1)


It seems it's validated. It seems Mohit pushed readme change directly to 1.15 branch. 
https://github.com/huggingface/optimum-habana/commit/8969de6946e078f26653659ed9887527e978e5c3

**Comment by jiminha** [comment]
@regisss  this is tested and ready to merge.

**Review by regisss — APPROVED** [review]

**Pull request merged**
