### PR TITLE
fix fsdp lora torch compile issue

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
PT_HPU_LAZY_MODE=0 python3 ../gaudi_spawn.py --use_mpi --world_size 2 run_lora_clm.py --model_name_or_path meta-llama/Llama-2-7b-hf --do_train --per_device_eval_batch_size 2 --per_device_train_batch_size 2 --fsdp_config fsdp_config.json --fsdp 'auto_wrap' --torch_compile_backend hpu_backend --torch_compile --use_habana --dataset_name tatsu-lab/alpaca --bf16 True --gradient_accumulation_steps 2 --save_strategy 'no' --evaluation_strategy 'no' --learning_rate 0.0003 --warmup_ratio 0.03 --max_grad_norm 0.3 --lr_scheduler_type 'constant' --logging_steps 1 --use_lazy_mode False --pipelining_fwd_bwd False --throughput_warmup_steps 3 --lora_rank 8 --lora_alpha 16 --lora_dropout 0.05 --lora_target_modules 'q_proj' 'v_proj' --dataset_concatenation --max_seq_length 512 --adam_epsilon 1e-08 --low_cpu_mem_usage True --attn_softmax_bf16 True --num_train_epochs 3 --output_dir ./temp


crash log:
[2024-05-09T02:08:43.024Z]   File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/llama/modeling_llama.py", line 832, in resume_in_forward
[2024-05-09T02:08:43.024Z]     if id(method.__code__) in self._nn_module_method_ids():
[2024-05-09T02:08:43.025Z] torch._dynamo.exc.InternalTorchDynamoError: 'NoneType' object has no attribute '__code__'

**Review by yeonsily — APPROVED** [review]

**Comment by regisss** [comment]
@sywangyi It runs fine on my instance. Are you using Synapse 1.16?

**Comment by sywangyi** [comment]
I am using synapse 1.15.1, @yeonsily report this issue to me, and I reproduce it.

**Comment by regisss** [comment]
I cannot reproduce it on my instance. When does the error happen? before training starts? After a few iterations?

**Comment by sywangyi** [comment]
image
image

**Review by regisss — APPROVED** [review]

**Pull request merged**
