### PR TITLE
Fixes in unify_measurements

### PR DESCRIPTION
**Pull request by HolyFalafel**
- [Remove scale calculation from unify_measurements script](https://github.com/huggingface/optimum-habana/commit/105adfd454a362a186cc7be1cf16ba8aea7d0f73) 

- [fixed measurement path bug](https://github.com/huggingface/optimum-habana/commit/d45d58b603ae0be4cc01a32fd76884d753ab3a71) 

- [Fix multi output unification in npz stage in unify_measur…](https://github.com/huggingface/optimum-habana/commit/89862dd4cdaaa0c91bf9ba88c09580b8d396b0e3) 

- [Update readme in ohf to the new unify_measurement script usage](https://github.com/huggingface/optimum-habana/pull/1496/commits/4fc881753ab7de8abe2ff1a407559626bda5e522)

### CODE REVIEW

**Review by hsubramony — APPROVED** [review]

**Review by regisss — APPROVED** [review]

**Comment by regisss** [comment]
@HolyFalafel Is this compatible with SynapseAI v1.18?

**Comment by HolyFalafel** [comment]
> @HolyFalafel Is this compatible with SynapseAI v1.18?

No, it requires a change done in v1.19

**Comment by HolyFalafel** [comment]
> The code quality check failed, please run `make style`.

@regisss , the result of `make style` are many files that have nothing to do with this change, what do you suggest to do?

**Comment by regisss** [comment]
> > The code quality check failed, please run `make style`.
> 
> @regisss , the result of `make style` are many files that have nothing to do with this change, what do you suggest to do?

Can you rebase your branch on main? I had to push a specific commit to fix the code style yesterday

**Comment by regisss** [comment]
@HolyFalafel Can you try to merge main into your branch? Rebasing is messing up with the history of the repo

**Comment by HolyFalafel** [comment]
> @HolyFalafel Can you try to merge main into your branch? Rebasing is messing up with the history of the repo

Done

**Pull request merged**
