### PR TITLE
enable checkpoint loading for llama, which will benefit llama2 70b an…

### PR DESCRIPTION
**Pull request by sywangyi**
…d greatly save host memory

### CODE REVIEW

**Comment by sywangyi** [comment]
should work with https://github.com/microsoft/DeepSpeed/pull/4206 for llama2 70b

**Comment by regisss** [comment]
Isn't it a duplicate of #359 ?

**Comment by sywangyi** [comment]
yes. duplicated, I have not noticed that, I will close this PR.

**Comment by sywangyi** [comment]
but https://github.com/microsoft/DeepSpeed/pull/4206 should be ported to habana deepspeed, or else llama 70b output is incorrect after enabling the shard load

**Comment by sywangyi** [comment]
also is_safetensors_available() should be removed which stop the download of *.bin, since allow_patterns is set to ["*.safetensors"]

**Comment by regisss** [comment]
> but [microsoft/DeepSpeed#4206](https://github.com/microsoft/DeepSpeed/pull/4206) should be ported to habana deepspeed, or else llama 70b output is incorrect after enabling the shard load

I think @mandy-li is looking into it

**Comment by regisss** [comment]
> also is_safetensors_available() should be removed which stop the download of _.bin, since allow_patterns is set to ["_.safetensors"]

Can you provide a command to reproduce it?
If `safetensors` is not installed, it should download the `.bin` checkpoint. Or do you want to download the `.bin` checkpoint even though `safetensors` is installed?

**Comment by regisss** [comment]
> [https://github.com/huggingface/optimum-habana/blob/main/examples/text-generation/checkpoint_utils.py#L63，](https://github.com/huggingface/optimum-habana/blob/main/examples/text-generation/checkpoint_utils.py#L63%EF%BC%8C) this line only filter the *.bin, and write it to checkpoint.json

Good catch! Can you keep just this change in this PR so that we merge it while @mandy-li can keep investigating Llama meta loading with DeepSpeed?

**Comment by sywangyi** [comment]
> > [https://github.com/huggingface/optimum-habana/blob/main/examples/text-generation/checkpoint_utils.py#L63，](https://github.com/huggingface/optimum-habana/blob/main/examples/text-generation/checkpoint_utils.py#L63%EF%BC%8C) this line only filter the *.bin, and write it to checkpoint.json
> 
> Good catch! Can you keep just this change in this PR so that we merge it while @mandy-li can keep investigating Llama meta loading with DeepSpeed?

done

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
