### PR TITLE
Fix beam search output

### PR DESCRIPTION
**Pull request by puneeshkhanna**
Also update cur_len with token_idx.item() and use that to slice the input_ids when calling beam_scorer.process(). The logic will work when token idx is None too.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by puneeshkhanna** [comment]
@regisss - can you please review ?

**Comment by puneeshkhanna** [comment]
@regisss  - any idea why CI is failing ?

**Comment by regisss** [comment]
@puneeshkhanna CI must be triggered by internal contributors.

I'll review your PR in the next few days (for sure this week) :slightly_smiling_face:

**Comment by regisss** [comment]
The code quality check failed, you can run the following from the root of the repo to solve it:
```bash
pip install black ruff
make style
```

**Comment by puneeshkhanna** [comment]
I will raise a new PR. Some conflicts in my branch.

**Pull request closed without merging**
