### PR TITLE
Add cagliostrolab/animagine-xl-3.1 to list of known XL models

### PR DESCRIPTION
**Pull request by mgonchar**
Added support of cagliostrolab/animagine-xl-3.1

Tested with following command:

python text_to_image_generation.py \
    --model_name_or_path cagliostrolab/animagine-xl-3.1 \
    --prompts "1girl, souryuu asuka langley, neon genesis evangelion, solo, upper body, v, smile, looking at viewer, outdoors, night" \
    --negative_prompts "nsfw, lowres, (bad), text, error, fewer, extra, missing, worst quality, jpeg artifacts, low quality, watermark, unfinished, displeasing, oldest, early, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract]" \
    --num_inference_steps 50 \
    --guidance_scale 7 \
    --num_images_per_prompt 50 \
    --batch_size 5 \
    --height 1216 \
    --width 832 \
    --image_save_dir /var/work/optimum-habana-clean/examples/stable-diffusion/stable_diffusion_images_animagine \
    --scheduler euler_discrete \
    --use_habana \
    --use_hpu_graphs \
    --gaudi_config Habana/stable-diffusion-2

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by dsocek — APPROVED** [review]
Looks good to me

**Review by kplau1128 — APPROVED** [review]
Looks good

**Comment by atakaha** [comment]
LGTM.

**Review by atakaha — APPROVED** [review]
looks good.

**Comment by mgonchar** [comment]
@regisss can you please provide your review here?

**Comment by mgonchar** [comment]
Not needed right now

**Pull request closed without merging**
