### PR TITLE
fix scikit-learn to 1.5.2 to fix f1 evaluation crash in 1.6.0

### PR DESCRIPTION
**Pull request by sywangyi**
python3 ../gaudi_spawn.py --world_size 8 --use_mpi run_multitask_prompt_tuning.py \
    --model_name_or_path google/flan-t5-base \
    --do_train \
    --report_to=none \
    --num_train_epochs 3 \
    --output_dir out_multi_peft \
    --use_habana \
    --use_lazy_mode \
    --evaluation_strategy "steps" \
    --eval_steps 500 \
    --save_strategy "no" \
    --learning_rate 1e-4  \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --use_hpu_graphs_for_inference \
    --use_hpu_graphs_for_training \
    --bf16 \

crash like
[rank1]: Traceback (most recent call last):
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/examples/language-modeling/run_multitask_prompt_tuning.py", line 421, in <module>
[rank1]:     main()
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/examples/language-modeling/run_multitask_prompt_tuning.py", line 379, in main
[rank1]:     train_result = trainer.train()
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/optimum/habana/transformers/trainer.py", line 554, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/optimum/habana/transformers/trainer.py", line 1074, in _inner_training_loop
[rank1]:     self._maybe_log_save_evaluate(tr_loss, _grad_norm, model, trial, epoch, ignore_keys_for_eval)
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/optimum/habana/transformers/trainer.py", line 1288, in _maybe_log_save_evaluate
[rank1]:     metrics = self._evaluate(trial, ignore_keys_for_eval)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2872, in _evaluate
[rank1]:     metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/optimum/habana/transformers/trainer_seq2seq.py", line 181, in evaluate
[rank1]:     return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/optimum/habana/transformers/trainer.py", line 1771, in evaluate
[rank1]:     output = eval_loop(
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/optimum/habana/transformers/trainer.py", line 2092, in evaluation_loop
[rank1]:     metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
[rank1]:   File "/yyoon/huggingface/optimum-habana/release/optimum-habana/examples/language-modeling/run_multitask_prompt_tuning.py", line 319, in compute_metrics
[rank1]:     return metric.compute(predictions=pred_ids, references=label_ids, pos_label=POSITIVE_TOKEN_ID)
[rank1]:   File "/usr/local/lib/python3.10/dist-packages/evaluate/module.py", line 467, in compute
[rank1]:     output = self._compute(**inputs, **compute_kwargs)
[rank1]:   File "/root/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--f1/0ca73f6cf92ef5a268320c697f7b940d1030f8471714bffdb6856c641b818974/f1.py", line 130, in _compute
[rank1]:     return {"f1": float(score) if score.size == 1 else score}
[rank1]: AttributeError: 'float' object has no attribute 'size'

### CODE REVIEW

**Comment by sywangyi** [comment]
actually, you do not need to run the example
just some simple code could produce it in scikit-learn 1.6.0
```
from sklearn.metrics import f1_score
import evaluate
f1_metric = evaluate.load("f1")
results = f1_metric.compute(references=[0, 1, 0, 1, 0], predictions=[0, 0, 1, 1, 0], pos_label=0)
```

**Comment by sywangyi** [comment]
check the pip env, the evaluate is the latest version evaluate==0.4.3

**Comment by sywangyi** [comment]
@yeonsily

**Comment by regisss** [comment]
@sywangyi It seems some other metrics are also affected: https://github.com/huggingface/evaluate/issues/655
Can you do a search on "scikit-learn" in the repo and update the requirements every time it appears please? It's used in other examples than the LM one.

**Review by regisss — APPROVED** [review]

**Pull request merged**
