### PR TITLE
Enable eager mode training for DETR

### PR DESCRIPTION
**Pull request by splotnikv**
# What does this PR do?
This PR is based on https://github.com/huggingface/optimum-habana/pull/1046 and additionally enables eager mode training for DETR. It does not support lazy mode training.

## Before submitting
- [n/a] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [no] Did you make sure to update the documentation with your changes?
- [no] Did you write any new necessary tests?

### CODE REVIEW

**Comment by emascarenhas** [comment]
Please sync your PR with main/upstream and fix any merge conflicts. Thank you.

**Comment by imangohari1** [comment]
hi @splotnikv 
Thanks for the PR. 
This PR needs some work as below. Please address these and ping us when it is done. 
- pls. rebase/sync on top of main OH. 
- run `make style` 
- Pls. share the results of this test on g2 machines. 
- we need to add README file for this in examples
- pls. add the appropriate CI tests for this.

**Comment by sandeep-maddipatla** [comment]
@imangohari1 - I have added further changes (for lazy mode execution) and addressed some of the feedback here in #1334 . Pls continue the review in that PR.

**Comment by imangohari1** [comment]
> @imangohari1 - I have added further changes (for lazy mode execution) and addressed some of the feedback here in #1334 . Pls continue the review in that PR.

Alright. 
Does it mean this PR is no longer needed? If so, we should close it.

**Pull request closed without merging**
