### PR TITLE
add warmup arg and move stats printing to the end

### PR DESCRIPTION
**Pull request by polisettyvarma**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by polisettyvarma** [comment]
please review this @regisss @vivekgoe @libinta

**Review by regisss — COMMENTED** [review]
@polisettyvarma Why moving memory stats and the graph compilation duration to the end far from the throughput? They should all be in the same place IMO.

**Comment by polisettyvarma** [comment]
> @polisettyvarma Why moving memory stats and the graph compilation duration to the end far from the throughput? They should all be in the same place IMO.

@regisss reason for keeping throughput there is for separator variable used in multiple places for alignment mostly. we created/updated the string but not printing throughput there.

**Comment by regisss** [comment]
> > @polisettyvarma Why moving memory stats and the graph compilation duration to the end far from the throughput? They should all be in the same place IMO.
> 
> @regisss reason for keeping throughput there is for separator variable used in multiple places for alignment mostly. we created/updated the string but not printing throughput there.

Okay, but I maintain that throughput, graph compilation duration and memory stats should all be printed together and before the outputs. Otherwise it may be very misleading and some users will just not see the throughput.

**Comment by polisettyvarma** [comment]
please review now @regisss

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
