### PR TITLE
Update README to Include Information on Performance Degradation and Mitigation Options

### PR DESCRIPTION
**Pull request by astachowiczhabana**
This Pull Request updates the README file for the optimum-habana repository to inform users about potential performance degradation due to the PyTorch 2.5 upgrade and provides options to mitigate this issue. Additionally, it includes information about an upcoming Gaudi-specific safe_softmax implementation that will improve performance in the next release of Optimum Habana.

### CODE REVIEW

**Comment by regisss** [comment]
@astachowiczhabana I think we should just put this message in the main README of the repo: https://github.com/huggingface/optimum-habana/blob/main/README.md
Also @libinta was telling me that it would be helpful to link to the Gaudi doc as there will be a similar message there once SynapseAI 1.19 is released.

**Comment by mlapinskix** [comment]
I've checked following files, and they dont contain models requiring adding **sdp_on_bf16** param:
/examples/zero-shot-object-detection/README.md
./examples/summarization/README.md
./examples/text-classification/README.md
./examples/text-to-speech/README.md
./examples/translation/README.md
./examples/image-to-text/README.md

**Comment by regisss** [comment]
@astachowiczhabana Please merge the `v1.15-release` into your branch. We'll merge this one directly there as it shouldn't go to main before SynpaseAI v1.19 is released.

**Comment by astachowiczhabana** [comment]
@regisss it's ready, since this is only readme changes I don't think it needs any additional testing

**Comment by libinta** [comment]
> @regisss it's ready, since this is only readme changes I don't think it needs any additional testing

@astachowiczhabana  as you are updating the readme, we do need ci test update. to speedup, we will provide patch for that today.

**Review by regisss — APPROVED** [review]

**Pull request merged**
