### PR TITLE
Hpu graph changes

### PR DESCRIPTION
**Pull request by vivekgoe**
# What does this PR do?
Modifies modeling_wav2vec2.py code to get it ready for enabling HPU graphs during training phase. Performance of Wav2Vec2 AC and ASR tasks on HPU are currently limited by Host time (more visible on 1x configurations), this also results in run to run performance variations (depending on loading of Host if it is shared by other processes). Enabling HPU graphs will improve performance and give more stable results.   

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
Very nice! I see it's still a draft, let me know when the PR is ready for review @vivekgoe :slightly_smiling_face:

**Comment by vivekgoe** [comment]
@regisss PR is ready for review now. Please note that there are some changes required to enable HPU graphs that shall be available only in 1.13.0 synapse release, so for now this PR is only to keep model changes ready to enable HPU graphs in near future.

**Review by regisss — APPROVED** [review]
LGTM!
So, if I understand correctly, we should merge this PR only after SynapseAI 1.13 is released right?

**Comment by vivekgoe** [comment]
@regisss in my opinion we can merge it now itself, however flag to enable HPU graphs can be added to wav2vec2 (audio-classification & ASR) README files and model tests after Synapse 1.13 release.

**Pull request merged**
