### PR TITLE
use fast softmax only on prefill

### PR DESCRIPTION
**Pull request by jaygala223**
use fast softmax only on prefill

### CODE REVIEW

**Review by dvarshney-habana — APPROVED** [review]

**Comment by yafshar** [comment]
@jaygala223 can you point to the source for this change? or is there an issue? From literature, fast softmax can be used in prefill

**Comment by yafshar** [comment]
If there is an accuracy issue raised by using fast softmax, can you point out to the issue, or bring it up here for the reference. It could be beneficial for other models and prevent others to root causing in similar cases.

**Comment by jaygala223** [comment]
@yafshar apologies for the delayed response. There was a performance regression which got introduced in a patch revert for context manager. This PR fixes it

**Comment by yafshar** [comment]
> @yafshar apologies for the delayed response. There was a performance regression which got introduced in a patch revert for context manager. This PR fixes it

@jaygala223 thanks, does this affect other models? Should we consider the same change for other models?

**Review by yafshar — APPROVED** [review]
LGTM!

@regisss please look at this PR

**Comment by yafshar** [comment]
@libinta please correct the PR label

**Comment by jaygala223** [comment]
> @jaygala223 thanks, does this affect other models? Should we consider the same change for other models?

No, it does not affect other models

**Review by regisss — APPROVED** [review]

**Comment by regisss** [comment]
Please run `make style`

**Review by regisss — APPROVED** [review]

**Pull request merged**
