### PR TITLE
fix opt bug

### PR DESCRIPTION
**Pull request by ZhaiFeiyue**
# What does this PR do?
as title

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by ZhaiFeiyue** [comment]
@regisss  please help to review if available. And should we add UT for text-generation?

**Review by regisss — APPROVED** [review]
LGTM!

**Comment by regisss** [comment]
> @regisss please help to review if available. And should we add UT for text-generation?

What is UT?

I just re-launched the CI, not sure why but it was stuck.

**Comment by regisss** [comment]
Okay I think the CI failed because of the release of Transformers v4.32. I'll try to release a patch ASAP.

**Comment by ZhaiFeiyue** [comment]
> 

I noticed that you have add `test_text_generation` into CI, which is what I want. 👍

**Comment by regisss** [comment]
@ZhaiFeiyue Could you update your branch with the patch I just merged to make sure CI pass?

**Pull request merged**
