### PR TITLE
pad to max_total_tokens in case max_new_token changes per request and…

### PR DESCRIPTION
**Pull request by sywangyi**
… new hpu graph will be created

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by regisss — COMMENTED** [review]
So the idea is to compile the model once for size 2048 to avoid extra compilations when different lengths are requested right?

**Comment by sywangyi** [comment]
> So the idea is to compile the model once for size 2048 to avoid extra compilations when different lengths are requested right?

yes.

**Comment by regisss** [comment]
Okay, no extra compilation will be needed for all sequences > 2048 tokens? Or just for some multiples of 8 (or another number) that are smaller than 2048?
Do we have an idea of how much slower latency is with this change for 7B models for instance?

Just trying to understand if this is good enough to keep this for a while or if it is just meant to be a short-term fix.

**Comment by sywangyi** [comment]
@regisss , I see there's  `--max-total-tokens` in the text-generation-launcher command line. whose description is" This is the most important value to set as it defines the "memory budget" of running clients requests. Clients will send input sequences and ask to generate `max_new_tokens` on top. with a value of `1512` users can send either a prompt of `1000` and ask for `512` new tokens, or send a prompt of `1` and ask for `1511` max_new_tokens. The larger this value, the larger amount each request will be in your RAM and the less effective batching can be [env: MAX_TOTAL_TOKENS=] [default: 2048]", currently this parameter is not passed to python, as what I describe in the code. I would like to utilize this parameter and set the padding length. so that if we set max-total-tokens in launcher to 2048. the sequence > 2048 will not passed to server python code.
for 7B llama. I test the perf. when max-new-tokens set to 64, if pad out length to 1024 (2048-1024(input pad to 1024)), the time_per_token is 44ms, if not pad to 1024, just pad to new token number(64), the time_per_token is 33ms. I test it in AWS DL1 instance.

**Comment by sywangyi** [comment]
The change of three dims could lead to the hpu graph recompile. one is input length, one is output length, one is batch number. the https://github.com/huggingface/optimum-habana/pull/386 is for input length. this PR is for output length. the most complicated is for batch dim. Should we get the max batch in warmup and use the max batch for each inference？ generating too much graph may lead to memory problem.

**Comment by regisss** [comment]
> @regisss , I see there's `--max-total-tokens` in the text-generation-launcher command line. whose description is" This is the most important value to set as it defines the "memory budget" of running clients requests. Clients will send input sequences and ask to generate `max_new_tokens` on top. with a value of `1512` users can send either a prompt of `1000` and ask for `512` new tokens, or send a prompt of `1` and ask for `1511` max_new_tokens. The larger this value, the larger amount each request will be in your RAM and the less effective batching can be [env: MAX_TOTAL_TOKENS=] [default: 2048]", currently this parameter is not passed to python, as what I describe in the code. I would like to utilize this parameter and set the padding length. so that if we set max-total-tokens in launcher to 2048. the sequence > 2048 will not be passed to server python code. for 7B llama. I test the perf. when max-new-tokens set to 64, if pad out length to 1024 (2048-1024(input pad to 1024)), the time_per_token is 44ms, if not pad to 1024, just pad to new token number(64), the time_per_token is 33ms. I test it in AWS DL1 instance.

Okay, could you link to this comment about `--max-total-tokens` in the comment you added at line 95 please?

**Comment by regisss** [comment]
> The change of three dims could lead to the hpu graph recompile. one is input length, one is output length, one is batch number. the #386 is for input length. this PR is for output length. the most complicated is for batch dim. Should we get the max batch in warmup and use the max batch for each inference？some batch contains dummy data that's not a valid request. however generating too much graph may lead to memory problem. Or shall we generate graph for each batch num (< max_batch) in warmup. Any idea?

IMO it depends whether we have more or less constant latency with max_batch (which we probably don't).
Generating several graphs for various batch sizes during warmup could make sense, but this may require a lot of memory no? I don't know the memory taken by a static graph for such a model.

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
