### PR TITLE
add trl example for mistral/mixtral.

### PR DESCRIPTION
**Pull request by lkk12014402**
# What does this PR do?

add more training examples for trl-dpo, like MoE structure mistralai/Mixtral-8x7B-v0.1, mistralai/Mistral-7B-v0.1

### CODE REVIEW

**Comment by yao-matrix** [comment]
@lkk12014402 , pls 1) provide performance and convergence comparisons btw A100 and Gaudi2 2) pls add ci, thx.

**Comment by lkk12014402** [comment]
> @lkk12014402 , pls 1) provide performance and convergence comparisons btw A100 and Gaudi2 2) pls add ci, thx.

yes, I will add these soon.

**Comment by lkk12014402** [comment]
hi @regisss  can we add these examples as MoE model is popular?

**Review by libinta — COMMENTED** [review]
@lkk12014402 how is the GPU performance comparison?

**Comment by lkk12014402** [comment]
> @lkk12014402 how is the GPU performance comparison?

hi @libinta I will update these in the next two days

**Pull request closed without merging**
