### PR TITLE
Enable DeepSpeed for image-to-text example

### PR DESCRIPTION
**Pull request by schoi-habana**
DeepSpeed init_distributed() and init_inference() were pulled from the text-generation example. 
Clip model change is required because DeepSpeed updates hidden_size

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by mandy-li** [comment]
@regisss  CI tests failed. Pls check what is the root cause. Seems not related to this PR

**Review by tthakkal — CHANGES_REQUESTED** [review]
Please add commands to run multi card in readme and also the requirement to set setting `PT_HPU_ENABLE_LAZY_COLLECTIVES=true` for multi card run

**Review by mandy-li — APPROVED** [review]
LGTM

**Comment by mandy-li** [comment]
@regisss , pls merge if this PR looks good to you.

**Review by tthakkal — APPROVED** [review]

**Review by regisss — APPROVED** [review]

**Pull request merged**
