### PR TITLE
Enable asynchronous data copy to get a better performance

### PR DESCRIPTION
**Pull request by jychen-habana**
# What does this PR do?
Improve Habana HPU performance, especially the host side performance by enabling 
asynchronous data copy from host to device with arg `non_blocking_data_copy`.

Before setting `non_blocking_data_copy` to True
image

After setting `non_blocking_data_copy` to True
image

Here is the overall performance before and after enabling `non_blocking_data_copy` (take Swin as an example):

Gaudi2
| non_blocking_data_copy | 1x | 8x |
|----------|:-------------:|------:|
| True | 374 | 1894 |
| False | 354 | 1857 |

Gaudi
| non_blocking_data_copy | 1x | 8x |
|----------|:-------------:|------:|
| True | 183 | 1060 |
| False | 183 | 1061 |

Both 1x and 8x performance get improvement on Gaudi2 but on Gaudi, none of them get any improvement. The reason is that the device computing on Gaudi2 is faster than Gaudi, when asynchronous data copy is enabled, the host can continue to execute other tasks like graph building, then we can get a better pipelining between the host and the device.  But on Gaudi, the device executing time is much longer which already hides the host time, so this optimization is more appropriate for Gaudi2.

Test command
```
# Single-HPU
python ../gaudi_spawn.py \
    --world_size 8 --use_mpi run_image_classification.py \
    --model_name_or_path microsoft/swin-base-patch4-window7-224-in22k \
    --dataset_name cifar10 \
    --output_dir /tmp/outputs/ \
    --remove_unused_columns False \
    --do_train \
    --learning_rate 2e-4 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 64 \
    --evaluation_strategy no \
    --save_strategy no \
    --load_best_model_at_end False \
    --save_total_limit 3 \
    --seed 1337 \
    --use_habana \
    --use_lazy_mode \
    --use_hpu_graphs \
    --gaudi_config_name Habana/swin \
    --throughput_warmup_steps 2 \
    --ignore_mismatched_sizes True \
    --overwrite_output_dir \
    --dataloader_num_workers 1 \
    --non_blocking_data_copy True
```

```
# Multi-HPU
python run_image_classification.py \
    --model_name_or_path microsoft/swin-base-patch4-window7-224-in22k \
    --dataset_name cifar10 \
    --output_dir /tmp/outputs/ \
    --remove_unused_columns False \
    --do_train \
    --learning_rate 3e-5 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 64 \
    --evaluation_strategy no \
    --save_strategy no \
    --load_best_model_at_end False \
    --save_total_limit 3 \
    --seed 1337 \
    --use_habana \
    --use_lazy_mode \
    --use_hpu_graphs \
    --gaudi_config_name Habana/swin \
    --throughput_warmup_steps 2 \
    --ignore_mismatched_sizes True \
    --overwrite_output_dir \
    --dataloader_num_workers 1 \
    --non_blocking_data_copy True
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by regisss — COMMENTED** [review]
All tests passed!

Also, I forgot it, but we should document this new argument here: https://github.com/huggingface/optimum-habana/blob/main/docs/source/usage_guides/accelerate_training.mdx

Based on the explanation you wrote in the other PR, I would put the following right before the section called "Custom Operators":

```markdown
## Non-Blocking Data Copy

This optimization is well-suited for models with a high cost of copying data from the host to the device. You can enable it with the argument `non_blocking_data_copy`.

**We recommend to use it on Gaudi2** where the host can continue to execute other tasks (e.g. graph building) to get a better pipelining between the host and the device. On first-generation Gaudi, the device executing time is longer so one should not expect to get any speedup.
```

**Comment by jychen-habana** [comment]
Hi @regisss, is there anything left I need to do for this PR?

**Comment by regisss** [comment]
> Hi @regisss, is there anything left I need to do for this PR?

Ah I thought you would add the paragraph above to the documentation. But it's okay, I can do it in another PR.
I'm just going to run some tests locally because for now GitHub cannot trigger them when the PR comes from a fork. And I let you know when it's good.

**Review by regisss — APPROVED** [review]

**Comment by jychen-habana** [comment]
> > Hi @regisss, is there anything left I need to do for this PR?
> 
> Ah I thought you would add the paragraph above to the documentation. But it's okay, I can do it in another PR.
> 
> edit: I already ran the tests before and they all passed, so it's good to merge 🙂

Oh, sorry, I misunderstood. Thanks!

**Pull request merged**
