### PR TITLE
Update FusedSDPA calling method as Gaudi documentation

### PR DESCRIPTION
**Pull request by yeonsily**
# What does this PR do?
According to the https://docs.habana.ai/en/latest/PyTorch/Reference/Python_Packages.html#hpex-kernels-fusedsdpa , 
we should pass 'recompute_mode' as API parameters.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by yafshar** [comment]
@yeonsily can you add more info on the issue? according to the document if you do not pass recompute_mode in the interface it reads it from the context API variable and it is given here.

**Review by libinta — APPROVED** [review]

**Comment by regisss** [comment]
> @yeonsily can you add more info on the issue? according to the document if you do not pass recompute_mode in the interface it reads it from the context API variable and it is given here.

I agree, there is
```py
with ht.sdp_kernel(enable_recompute=enable_recompute):
```
currently in the codebase, so the behavior should be the same no?

**Comment by yeonsily** [comment]
> > @yeonsily can you add more info on the issue? according to the document if you do not pass recompute_mode in the interface it reads it from the context API variable and it is given here.
> 
> I agree, there is
> 
> ```python
> with ht.sdp_kernel(enable_recompute=enable_recompute):
> ```
> 
> currently in the codebase, so the behavior should be the same according to the documentation no?

@yafshar  @regisss  We have an internal ticket which the current method causes performance degradation in torch.compile run as there will be graph breaks. This issue is torch.compile specific but I think we can pass recompute_mode as a parameter regardless of mode to keep the topology code same.
Please let me know if you want to have this change only for torch.compile mode.

**Comment by regisss** [comment]
> > > @yeonsily can you add more info on the issue? according to the document if you do not pass recompute_mode in the interface it reads it from the context API variable and it is given here.
> > 
> > 
> > I agree, there is
> > ```python
> > with ht.sdp_kernel(enable_recompute=enable_recompute):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > currently in the codebase, so the behavior should be the same according to the documentation no?
> 
> @yafshar @regisss We have an internal ticket which the current method causes performance degradation in torch.compile run as there will be graph breaks. This issue is torch.compile specific but I think we can pass recompute_mode as a parameter regardless of mode to keep the topology code same. Please let me know if you want to have this change only for torch.compile mode.

Thanks for the exaplanation, let's merge it then :slightly_smiling_face:

**Review by regisss — APPROVED** [review]

**Pull request merged**
