### PR TITLE
Scope out autocast for mult in extended atten mask gen

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
This PR addresses nan issue appeared in loss computation for BERT family.

JH...!

### CODE REVIEW

**Review by regisss — COMMENTED** [review]
@ANSHUMAN87 Nice PR to solve this issue with PyTorch Autocast!

It looks good to me, could you also do the same [here](https://github.com/huggingface/optimum-habana/blob/82f8622e51a508f105ad6dd30f7af290add88efe/optimum/habana/transformers/models/albert/modeling_albert.py#L72) for ALBERT please since it does not rely on the same method as other BERT-like models?

**Comment by ANSHUMAN87** [comment]
@regisss Thank you very much for your review. Your comment is addressed now. Please help review and merge. Thanks!

JH...!

**Review by regisss — APPROVED** [review]
LGTM!

**Comment by regisss** [comment]
Tests failed because this PR was open from a fork. Merging.

**Pull request merged**
