### PR TITLE
Readme Update for FSDP

### PR DESCRIPTION
**Pull request by hlahkar**
Updating Readme to  indicate flash attention support for LLama2 70b with FSDP. This improves performance as well as memory footprint

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by vivekgoe — APPROVED** [review]
LGTM.

**Comment by vivekgoe** [comment]
@regisss please review this readme change and merge this change when we transition to Synapse 1.16.0. We have tested this change on G2 with Synapse 1.16.0, this gives a small boost in performance.

**Comment by hlahkar** [comment]
@regisss This is for 1.16; it does not work properly for 1.15

**Review by regisss — APPROVED** [review]

**Comment by hlahkar** [comment]
@regisss Can we merge this now?

**Pull request merged**
