### PR TITLE
Fix GPT-NeoX training

### LINKED ISSUE #403: gpt neox finetuning does not work(segmentaion fault) since 1.7.0
### System Info

```shell
optimum-habana version >1.7.0
deepspeed 1.11.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
python3 /root/repos/optimum-habana/examples/gaudi_spawn.py   --hostfile /root/repos/hostsfile --world_size 8 --use_deepspeed /root/repos/optimum-habana/examples/language-modeling/run_clm.py --deepspeed /root/repos/optimum-habana/tests/configs/deepspeed_zero_2.json --model_name_or_path 'EleutherAI/gpt-neox-20b' --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 2 --per_device_eval_batch_size 2 --num_train_epochs 1 --do_train --output_dir ~/gpt-neox-20b --gaudi_config_name Habana/gpt2 --gradient_checkpointing --use_habana --use_lazy_mode --throughput_warmup_steps 3 --overwrite_output_dir --use_hpu_graphs_for_inference
```
crash log
```
10.233.250.163: Loading extension module utils...
10.233.250.163: [INFO|trainer.py:680] 2023-09-12 09:11:29,269 >> ***** Running training *****
10.233.250.163: [INFO|trainer.py:681] 2023-09-12 09:11:29,269 >>   Num examples = 2,334
10.233.250.163: [INFO|trainer.py:682] 2023-09-12 09:11:29,269 >>   Num Epochs = 1
10.233.250.163: [INFO|trainer.py:683] 2023-09-12 09:11:29,269 >>   Instantaneous batch size per device = 2
10.233.250.163: [INFO|trainer.py:686] 2023-09-12 09:11:29,269 >>   Total train batch size (w. parallel, distributed & accumulation) = 32
10.233.250.163: [INFO|trainer.py:687] 2023-09-12 09:11:29,269 >>   Gradient Accumulation steps = 1
10.233.250.163: [INFO|trainer.py:688] 2023-09-12 09:11:29,269 >>   Total optimization steps = 73
10.233.250.163: [INFO|trainer.py:689] 2023-09-12 09:11:29,274 >>   Number of trainable parameters = 20,554,567,680
10.233.168.102: Time to load utils op: 0.0013871192932128906 seconds
10.233.168.102: Using /root/.cache/torch_extensions/py38_cpu as PyTorch extensions root...
10.233.168.102: No modifications detected for re-loaded extension module utils, skipping build step...
10.233.168.102: Loading extension module utils...
10.233.168.102: Time to load utils op: 0.00066375732421875 seconds
10.233.168.102: Using /root/.cache/torch_extensions/py38_cpu as PyTorch extensions root...
10.233.168.102: No modifications detected for re-loaded extension module utils, skipping build step...
10.233.168.102: Loading extension module utils...
10.233.168.102: Time to load utils op: 0.0005764961242675781 seconds
10.233.168.102: Using /root/.cache/torch_extensions/py38_cpu as PyTorch extensions root...
10.233.168.102: No modifications detected for re-loaded extension module utils, skipping build step...
10.233.168.102: Loading extension module utils...
10.233.250.163: [2023-09-12 09:11:30,324] [INFO] [checkpointing.py:605:forward] Activation Checkpointing Information
10.233.250.163: [2023-09-12 09:11:30,324] [INFO] [checkpointing.py:606:forward] ----Partition Activations False, CPU CHECKPOINTING False
10.233.250.163: [2023-09-12 09:11:30,324] [INFO] [checkpointing.py:607:forward] ----contiguous Memory Checkpointing False with None total layers
10.233.250.163: [2023-09-12 09:11:30,324] [INFO] [checkpointing.py:609:forward] ----Synchronization False
10.233.250.163: [2023-09-12 09:11:30,324] [INFO] [checkpointing.py:610:forward] ----Profiling time in checkpointing False
10.233.168.102: Internal Error: Received signal - Segmentation fault
10.233.168.102: Internal Error: Received signal - Segmentation fault
10.233.250.163: 
  0%|          | 0/73 [00:00<?, ?it/s]Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.168.102: Internal Error: Received signal - Segmentation fault
10.233.168.102: Internal Error: Received signal - Segmentation fault
10.233.168.102: Internal Error: Received signal - Segmentation fault
10.233.168.102: Internal Error: Received signal - Segmentation fault
10.233.250.163: Internal Error: Received signal - Segmentation fault
10.233.168.102: Internal Error: Received signal - Segmentation fault 
```

### Expected behavior

same with 1.6.1

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

Fixes #403.
Same fix for Llama and Falcon.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by ZhaiFeiyue — APPROVED** [review]
LGTM! 👍

**Comment by ankurneog** [comment]
@regisss  : The fix seems to be working , Both fine tuning and evaluation seems to be running fine (gaudi2, 16X) : 
10.233.188.88: ***** train metrics *****
10.233.188.88:   epoch                       =        3.0
10.233.188.88:   max_memory_allocated (GB)   =      94.22
10.233.188.88:   memory_allocated (GB)       =      53.73
10.233.188.88:   total_memory_available (GB) =      94.46
10.233.188.88:   train_loss                  =      1.545
10.233.188.88:   train_runtime               = 0:10:11.98
10.233.188.88:   train_samples               =       2334
10.233.188.88:   train_samples_per_second    =      14.08
10.233.188.88:   train_steps_per_second      =       0.44

10.233.188.88: ***** eval metrics *****
10.233.188.88:   epoch                       =        3.0
10.233.188.88:   eval_accuracy               =     0.5198
10.233.188.88:   eval_loss                   =     2.3358
10.233.188.88:   eval_runtime                = 0:01:41.05
10.233.188.88:   eval_samples                =        241
10.233.188.88:   eval_samples_per_second     =      2.385
10.233.188.88:   eval_steps_per_second       =      0.079
10.233.188.88:   max_memory_allocated (GB)   =      94.22
10.233.188.88:   memory_allocated (GB)       =      64.94
10.233.188.88:   perplexity                  =    10.3375
10.233.188.88:   total_memory_available (GB) =      94.46

**Review by ZhaiFeiyue — APPROVED** [review]
LGTM! 👍

**Comment by mandy-li** [comment]
@regisss , @ZhaiFeiyue , am i missing something here? why disabled fused RoPE for training?

**Comment by regisss** [comment]
@mandy-li That makes GPT-NeoX fine-tuning with DeepSpeed ZeRO-2 crash

**Comment by ZhaiFeiyue** [comment]
@mandy-li there is a crash in @ankurneog side, see issue #403

**Comment by mandy-li** [comment]
@regisss , @ZhaiFeiyue , yes, @schoi-habana further debugged it and filed an internal jira. I will push it fixed soon. Thanks for working around the issue.

**Pull request merged**
