### PR TITLE
fix facebook/hf-seamless-m4t-medium crash

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)
coredump when runing facebook/hf-seamless-m4t-medium 
cd examples/text-to-speech
python3 run_pipeline.py     --model_name_or_path facebook/hf-seamless-m4t-medium     --use_hpu_graphs     --bf16  --text "Hello, my dog is cooler than you!"

Traceback (most recent call last):
  File "/root/github/tmp/optimum-habana/examples/text-to-speech/run_pipeline.py", line 137, in <module>
    main()
  File "/root/github/tmp/optimum-habana/examples/text-to-speech/run_pipeline.py", line 119, in main
    generator(text, batch_size=args.batch_size, forward_params=forward_params, generate_kwargs=generate_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_to_audio.py", line 186, in call
    return super().call(text_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1249, in call
    outputs = list(final_iterator)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/pt_utils.py", line 124, in next
    item = next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/pt_utils.py", line 125, in next
    processed = self.infer(item, **self.params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1175, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_to_audio.py", line 147, in _forward
    output = self.model.generate(**model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/github/tmp/optimum-habana/optimum/habana/transformers/models/seamless_m4t/modeling_seamless_m4t.py", line 805, in gaudi_SeamlessM4TForTextToSpeech_generate    unit_ids = self.t2u_model.generate(inputs_embeds=t2u_input_embeds, **kwargs_speech)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/github/tmp/optimum-habana/optimum/habana/transformers/generation/utils.py", line 1178, in generate
    model_kwargs["token_idx"].item() if "token_idx" in model_kwargs else input_ids_length,
RuntimeError: Graph compile failed. synStatus=synStatus 26 [Generic failure].

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by jiminha** [comment]
@sywangyi  Could you explain why other two models work but not  facebook/hf-seamless-m4t-medium  ?

**Comment by sywangyi** [comment]
facebook/hf-seamless-m4t-medium hit the condition that decode input id length is 2.  and  decoder_start_token_id is not in the decode input id, which cause issue in https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L249

**Comment by jiminha** [comment]
> facebook/hf-seamless-m4t-medium hit the condition that decode input id length is 2. and decoder_start_token_id is not in the decode input id, which cause issue in https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L249

Is this only model that you are aware of which has decode input id length of 2?   What other tests do you recommend us to run to make sure this new code doesn't break any other models run?

**Comment by sywangyi** [comment]
> > facebook/hf-seamless-m4t-medium hit the condition that decode input id length is 2. and decoder_start_token_id is not in the decode input id, which cause issue in https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L249
> 
> Is this only model that you are aware of which has decode input id length of 2? When does below statement return true? Is this model specific, and only happening on this ht-seamless-m4t model? elif (decoder_input_ids[:, 0] != decoder_start_token_id[:, 0]).all().item():
> 
> What other tests do you recommend us to run to make sure this new code in utils.py doesn't break any other models run?

yes. not so much encoder-decoder model are supported by optimum-habana now. this is the only model I am aware of in OH. For the logic I think this is common.

**Comment by jiminha** [comment]
@sywangyi   Could you also change the Readme file to add this model back? We removed it from v.1.14 release due to the error.

**Comment by jiminha** [comment]
Also, please update 
What does this PR do?
Fixes # (issue)

**Review by jiminha — APPROVED** [review]

**Comment by jiminha** [comment]
@regisss  Can we merge this change to main. text generation CI tests were tested without an error.

**Review by regisss — APPROVED** [review]

**Pull request merged**
