### PR TITLE
add no_checks for sub dataset in lvwerra/stack-exchange-paired since …

### PR DESCRIPTION
**Pull request by sywangyi**
…it does not contain test split

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
load dataset error if datasets >= 2.19.0.
error is like
image

**Comment by sywangyi** [comment]
occurred after https://github.com/huggingface/datasets/pull/6714 is merged.

**Comment by regisss** [comment]
@sywangyi Could you try with the latest release of Datasets (v2.19.2) please? It should solve this issue.

**Comment by sywangyi** [comment]
yes. works in 2.19.2

**Comment by regisss** [comment]
> yes. works in 2.19.2

Great! Could you remove `verification_mode="no_checks"` from the examples (`dpo.py` too) and set the requirements `datasets==2.19.2` in `requirements.txt` please?

**Comment by sywangyi** [comment]
ok, I will do it

**Review by regisss — APPROVED** [review]

**Pull request merged**
