### PR TITLE
Update save lora weights for diffusers with text_encoder_2 layers

### PR DESCRIPTION
**Pull request by skavulya**
# What does this PR do?
Fixes saving lora weights for diffuser pipelines which do not support text_encoder_2 layers.

For example,
```
python examples/trl/ddpo.py \
  --num_epochs=200 \
  --train_gradient_accumulation_steps=1 \
  --sample_num_steps=50 \
  --sample_batch_size=6 \
  --train_batch_size=3 \
  --sample_num_batches_per_epoch=4 \
  --per_prompt_stat_tracking=True \
  --per_prompt_stat_tracking_buffer_size=32 \
  --train_learning_rate=1e-05 \
  --tracker_project_name="stable_diffusion_training" \
  --log_with="tensorboard" \
  --use_habana \
  --use_hpu_graphs \
  --bf16 \
  --hf_hub_model_id="ddpo-finetuned-stable-diffusion" \
  --push_to_hub False
```

 File "/root/tf/optimum-habana-new/examples/trl/ddpo.py", line 245, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/ddpo_trainer.py", line 604, in train
    global_step = self.step(epoch, global_step)
  File "/root/tf/optimum-habana-new/optimum/habana/trl/trainer/ddpo_trainer.py", line 315, in step
    self.accelerator.save_state()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2987, in save_state
    hook(self._models, weights, output_dir)
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/ddpo_trainer.py", line 439, in _save_model_hook
    self.sd_pipeline.save_checkpoint(models, weights, output_dir)
  File "/usr/local/lib/python3.10/dist-packages/trl/models/modeling_sd_base.py", line 883, in save_checkpoint
    self.sd_pipeline.save_lora_weights(save_directory=output_dir, unet_lora_layers=state_dict)
  File "/root/tf/optimum-habana-new/optimum/habana/diffusers/pipelines/pipeline_utils.py", line 397, in save_lora_weights
    return super().save_lora_weights(
TypeError: StableDiffusionLoraLoaderMixin.save_lora_weights() takes from 2 to 8 positional arguments but 9 were given

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by jiminha — APPROVED** [review]

**Comment by skavulya** [comment]
@jiminha @sywangyi Please review

**Comment by jiminha** [comment]
@sywangyi  Can you review this? Original save_lora_weights() was added by one of your PR. 
https://github.com/huggingface/optimum-habana/pull/881

**Comment by skavulya** [comment]
Here are the results of diffusers tests. 

`make fast_tests_diffusers`
This PR: ========== 115 passed, 49 skipped, 277 warnings in 1115.73s (0:18:35) ==========
main commit eee2d91d58013393439b1e1f2533ab3203abe607 ========== 115 passed, 49 skipped, 277 warnings in 1171.49s (0:19:31) ==========

` GAUDI2_CI=1  RUN_SLOW=1 make slow_tests_diffusers`
This PR:  ===== 1 failed, 1 passed, 163 deselected, 3 warnings in 423.39s (0:07:03) ======
main commit eee2d91d58013393439b1e1f2533ab3203abe607 ===== 1 failed, 1 passed, 163 deselected, 3 warnings in 450.84s (0:07:30) ======

**Comment by sywangyi** [comment]
https://github.com/huggingface/optimum-habana/pull/1633 also fix it

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
