### PR TITLE
fix gptj incorrect output issue in TGI

### PR DESCRIPTION
**Pull request by sywangyi**
run model EleutherAI/gpt-j-6b in TGI

 curl 127.0.0.1:8080/generate \
     -X POST \
     -d '{"inputs":"What is DeepSpeed?","parameters":{"max_new_tokens":256, "do_sample": false}}' \
     -H 'Content-Type: application/json'
~

{"generated_text":"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ:QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ:QQQQQQQQQQQQQQQQQQQQQQQQQQQQQ:QDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"

### CODE REVIEW

**Comment by sywangyi** [comment]
after the fix the output is
{"generated_text":"Q: What is DeepSpeed?\n\nA: DeepSpeed is a new, revolutionary, and highly effective way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight. It is a revolutionary new way to help you lose weight"}

**Comment by sywangyi** [comment]
this fix is also needed for llama

**Comment by yao-matrix** [comment]
@regisss , could you pls take a look at this? Thx.

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
