### PR TITLE
deciLM support

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
@yao-matrix

**Comment by sywangyi** [comment]
Hi, @regisss  do we have plan to optimize the remote-code model like deci in habana? If yes, could it do like this way?

**Comment by sywangyi** [comment]
|  throught(tokens/s)| A100 | Gaudi2 |
|-------|------|----------|
| BF16 | 43.5 |  121.7|
|FP32 |42.67  | 54.59|

**Comment by imangohari1** [comment]
Hi @sywangyi 
I have the following suggestions for this PR. 
Let me know if you have any questions. 
- Pls. test the deciLM with different in/out token and bs sizes and share the results. 
- Pls. test the enabling with different deciLM model sizes, 6b and 7b and -instruc versions, as well. https://huggingface.co/collections/Deci/decilm-models-65a7fb6a65e4f1a5eb14917a
- Pls made sure to run `make style` (if not already). 
- Can we add a _**fast**_ CI test for this?

**Comment by sywangyi** [comment]
@imangohari1 my question is just to align could we support **remote code** model like this way? there's no remote code model support in the optimum-habana now. If it's yes. I will have a follow-up about your suggestion.

**Comment by imangohari1** [comment]
> @imangohari1 my question is just to align could we support **remote code** model like this way? there's no remote code model support in the optimum-habana now. If it's yes. I will have a follow-up about your suggestion.

I am not sure. Let's get @regisss input.

**Comment by sywangyi** [comment]
> > @imangohari1 my question is just to align could we support **remote code** model like this way? there's no remote code model support in the optimum-habana now. If it's yes. I will have a follow-up about your suggestion.
> 
> I am not sure. Let's get @regisss input. If the implemenation here is unclear, I suggest changing this to draft @sywangyi

I've made the PR open to draw everyone's attention to it which would accelerate the decision making. Thanks for your feedback.

**Comment by regisss** [comment]
Yes, it's fine doing like that. Please specify the exact commit hash your code is based on.
I guess we still need to set trust_remote_code to True when instantiating the model right?

**Comment by sywangyi** [comment]
> trust_remote_code

trust_remote_code is not needed any more in this way. it will use the model implementation in optimum-habana.

**Review by imangohari1 — CHANGES_REQUESTED** [review]
Hi @sywangyi 
I have tested these changes and it works with `DeciLM-7B` and it works, but it does not work with `DeciLM-6b` (below details). 
Please:
-  Revisit/test for `DeciLM-6b`/`DeciLM-6b-instruct` models.  https://huggingface.co/Deci/DeciLM-6b
- Sync/rebase at the top of OH main. 

Thank you. 

## Tests 
deciLM7B, new token 1028, bs 16
```bash 
python run_generation.py --model_name_or_path /datasets/huggingface/hub/models--Deci--DeciLM-7B/snapshots/c3c9f4226801dc0433f32aebffe0aac68ee2f051/ --use_kv_cache --max_new_tokens 1028 --batch_size 16 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"
```
```bash
Stats:
--------------------------------------------------------------------------------------------------------------
Throughput (including tokenization) = 440.5303867789949 tokens/second
Number of HPU graphs                = 14
Memory allocated                    = 17.44 GB
Max memory allocated                = 17.7 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 131.36527838598704 seconds
--------------------------------------------------------------------------------------------------------------

```

deciLM7B, new token 512, bs 32
```bash
python run_generation.py --model_name_or_path /datasets/huggingface/hub/models--Deci--DeciLM-7B/snapshots/c3c9f4226801dc0433f32aebffe0aac68ee2f051/ --use_kv_cache --max_new_tokens 512 --batch_size 32 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"
```
```
Stats:
--------------------------------------------------------------------------------------------------------------
Throughput (including tokenization) = 859.8175255470775 tokens/second
Number of HPU graphs                = 14
Memory allocated                    = 16.68 GB
Max memory allocated                = 17.21 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 78.38171231899469 seconds
--------------------------------------------------------------------------------------------------------------

```

deciLM7B-instuct, new token 256, bs 64
```bash
python run_generation.py --model_name_or_path /datasets/huggingface/hub/models--Deci--DeciLM-7B-instruct/snapshots/4adc7aa9efe61b47b0a98b2cc94527d9c45c3b4f/ --use_kv_cache --max_new_tokens 256 --batch_size 64 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"
```
```
--------------------------------------------------------------------------------------------------------------
Throughput (including tokenization) = 1724.740007723637 tokens/second
Number of HPU graphs                = 14
Memory allocated                    = 16.74 GB
Max memory allocated                = 17.8 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 45.174995980996755 seconds
--------------------------------------------------------------------------------------------------------------

```

deciLM6b, new token 100, bs 1
```bash
 python run_generation.py --model_name_or_path Deci/DeciLM-6b --use_kv_cache --max_new_tokens 100 --batch_size 1 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"

```
```
Traceback (most recent call last):
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/run_generation.py", line 666, in <module>
    main()
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/run_generation.py", line 309, in main
    model, assistant_model, tokenizer, generation_config = initialize_model(args, logger)
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/utils.py", line 509, in initialize_model
    setup_model(args, model_dtype, model_kwargs, logger)
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/utils.py", line 214, in setup_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 931, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 627, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading Deci/DeciLM-6b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

```
deciLM6b-instruct, new token 100, bs 1
```bash
 python run_generation.py --model_name_or_path Deci/DeciLM-6b-instruct --use_kv_cache --max_new_tokens 100 --batch_size 1 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"
```
```
Traceback (most recent call last):
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/run_generation.py", line 666, in <module>
    main()
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/run_generation.py", line 309, in main
    model, assistant_model, tokenizer, generation_config = initialize_model(args, logger)
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/utils.py", line 509, in initialize_model
    setup_model(args, model_dtype, model_kwargs, logger)
  File "/devops/sgohari/tests/codes/pr-reviews/pr-1133/optimum-habana/examples/text-generation/utils.py", line 214, in setup_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 931, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 627, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading Deci/DeciLM-6b-instruct requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

**Comment by sywangyi** [comment]
Hi, Deci/DeciLM-6b-instruct and  DeciLM-6b does not contain model type "deci" in https://huggingface.co/Deci/DeciLM-6b/blob/main/config.json. so it does not support local code model. see logic in transformers. https://github.com/huggingface/transformers/blob/main/src/transformers/models/auto/configuration_auto.py#L973-L974
also the static shape optimization is determined by model type. see https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L634. shall we need to hack the code to support it? the Deci 6B downloads is far behind of Deci 7B serial.

**Comment by imangohari1** [comment]
> Hi, @imangohari1 , Thanks for the benchmark. Deci/DeciLM-6b-instruct and DeciLM-6b does not contain model type "deci" in https://huggingface.co/Deci/DeciLM-6b/blob/main/config.json. so it does not support local code mode. see logic in transformers. https://github.com/huggingface/transformers/blob/main/src/transformers/models/auto/configuration_auto.py#L973-L974 meanwhile the static shape optimization is determined by model type as well. see https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/generation/utils.py#L634. shall we need to hack the code to support it? the Deci 6B downloads is far behind of Deci 7B serial.

@sywangyi 
Thanks. 
I was able to get `DeciLM-6b` running by adding `"model_type": "deci",` in the json file [here](https://huggingface.co/Deci/DeciLM-6b/blob/main/config.json#L13) (below). 
I am not sure what `hack` you were thinking but I think having an option to run that model might be useful.
```
python run_generation.py --model_name_or_path Deci/DeciLM-6b --use_kv_cache --max_new_tokens 1024 --batch_size 16 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"
```
```

Stats:
---------------------------------------------------------------------------------------------------------------
Throughput (including tokenization) = 483.99941399787946 tokens/second
Number of HPU graphs                = 14
Memory allocated                    = 14.61 GB
Max memory allocated                = 14.88 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 120.89111913500528 seconds
---------------------------------------------------------------------------------------------------------------
```
```bash
python run_generation.py --model_name_or_path Deci/DeciLM-6b --use_kv_cache --max_new_tokens 100 --batch_size 1 --bf16 --use_hpu_graphs --prompt "DeepSpeed is a machine learning framework"
```
```

Stats:
---------------------------------------------------------------------------------------------------------------
Throughput (including tokenization) = 140.92129844475383 tokens/second
Number of HPU graphs                = 14
Memory allocated                    = 10.74 GB
Max memory allocated                = 10.75 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 7.28320421501121 seconds
---------------------------------------------------------------------------------------------------------------
```

**Comment by sywangyi** [comment]
@imangohari1  hack is like following.
image
it's only for single card generation case, need to apply to multi-card, peft generation case as well. also need to apply to language modeling example if you need to enable finetune for deci-6B. the problem is "model_type is missing in config.json, and local class could not be called automatically from AutoModelForCausalLM, so it needed to be called manually.

**Comment by sywangyi** [comment]
so, I think the correct solution is to port similar change like https://huggingface.co/Deci/DeciLM-7B/commit/0be2d64c57344399a148a5f9e9129b7d6a07aac0 to deci 6B. @imangohari1 WDYT?

**Comment by imangohari1** [comment]
> so, I think the correct solution is to port similar change like https://huggingface.co/Deci/DeciLM-7B/commit/0be2d64c57344399a148a5f9e9129b7d6a07aac0 to deci 6B. @imangohari1 WDYT? I open a discussion, see https://huggingface.co/Deci/DeciLM-6b/discussions/6

@sywangyi I agree. Let's see what respond we get from the model owners.

**Comment by imangohari1** [comment]
> > so, I think the correct solution is to port similar change like https://huggingface.co/Deci/DeciLM-7B/commit/0be2d64c57344399a148a5f9e9129b7d6a07aac0 to deci 6B. @imangohari1 WDYT? I open a discussion, see https://huggingface.co/Deci/DeciLM-6b/discussions/6
> 
> @sywangyi I agree. Let's see what respond we get from the model owners.

@sywangyi 
the model type was added for the deci-6b. 
I was able to run it after re-downloading the `config.json` file. 
coudl you please confirm the same on your end? Tnx

**Comment by sywangyi** [comment]
yes, deci-6b worked by my side as well

**Review by imangohari1 — APPROVED** [review]
LGTM! 
@regisss for your review when you had a chance.

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
