### PR TITLE
enable Intel/neural-chat-7b-v3-* series models inference.

### PR DESCRIPTION
**Pull request by lkk12014402**
# What does this PR do?

add validated model Intel/neural-chat-7b-v3-* inference
[Intel/neural-chat-7b-v3 · Hugging Face](https://huggingface.co/Intel/neural-chat-7b-v3)
[Intel/neural-chat-7b-v3-1 · Hugging Face](https://huggingface.co/Intel/neural-chat-7b-v3-1)
[Intel/neural-chat-7b-v3-2 · Hugging Face](https://huggingface.co/Intel/neural-chat-7b-v3-2)
[Intel/neural-chat-7b-v3-3 · Hugging Face](https://huggingface.co/Intel/neural-chat-7b-v3-3)
[Intel/neural-chat-7b-v3-3-Slerp · Hugging Face](https://huggingface.co/Intel/neural-chat-7b-v3-3-Slerp)

Intel/neural-chat-7b-v3-* series models are finetuning version of [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1), which have gained a lot of attention like 500+likes and 40k+ downloads on huggingface.co.

### CODE REVIEW

**Comment by lkk12014402** [comment]
single card inference
```python
python run_generation.py --model_name_or_path Intel/neural-chat-7b-v3-3-Slerp --use_kv_cache --max_new_tokens 100 --bf16
```
image

**Comment by libinta** [comment]
@lkk12014402 there are many models that can run on Gaudi, we don't need to put to the validated page. It's based on mistral. If you have any optimization/improvement done for mistral. please submit it. Thanks.

**Comment by lkk12014402** [comment]
> @lkk12014402 there are many models that can run on Gaudi, we don't need to put to the validated page. It's based on mistral. If you have any optimization/improvement done for mistral. please submit it. Thanks.

okay~ Thanks~

**Comment by regisss** [comment]
Let's close this one?

**Comment by lkk12014402** [comment]
> Let's close this one?

yes~

**Pull request closed without merging**
