### PR TITLE
Update the Mistral model naming

### PR DESCRIPTION
**Pull request by yafshar**
- Update the naming as suggested in [PR#716 ](https://github.com/huggingface/optimum-habana/pull/716)
   gaudi_mistral_attn_forward -> gaudi_mistral_attention_forward

### CODE REVIEW

**Comment by yafshar** [comment]
@regisss, This PR fixes the mistral naming discussed in https://github.com/huggingface/optimum-habana/pull/716#discussion_r1494706423

**Comment by regisss** [comment]
@yafshar Thanks for correcting this!
I see there is a merge conflict with main, probably because of https://github.com/huggingface/optimum-habana/pull/653. It should be quick to solve but let me know if you need help on this :slightly_smiling_face:

**Comment by yafshar** [comment]
@regisss, I fixed the conflict, but please do a final check

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
