### PR TITLE
Enhances llama performance by removing the 'cast_f32_to_bf16' operation 

### PR DESCRIPTION
**Pull request by kalyanjk**
Enhances performance by replacing the 'cast_f32_to_bf16' operation with 'multiplication' instead of 'division.' Refines the original graph by streamlining operations: 'add_fwd_bf16, cast_f32_to_bf16, div_bf16, softmax_fwd_bf16,'  to a more optimized version: 'add_fwd_bf16, mult_fwd_bf16, softmax_fwd_bf16.'

### CODE REVIEW

**Review by puneeshkhanna — APPROVED** [review]
Perf improvement with this change is minimal but will be always better and avoids the unnecessary cast too.

**Review by libinta — APPROVED** [review]

**Review by regisss — COMMENTED** [review]
LGTM!

Can you also run the following snippet to have the code style check pass please?
```
pip install --upgrade ruff
make style
```

**Comment by regisss** [comment]
@kalyanjk Weird that it reformatted `test_modeling_t5.py` and `test_modeling_common.py`, can you just remove these changes and just keep the reformatting of `modeling_llama.py` please?

**Review by regisss — APPROVED** [review]
LGTM

**Pull request merged**
