### PR TITLE
fix(test_diffusers): automated the checking for tests without upstream HF

### PR DESCRIPTION
**Pull request by imangohari1**
# What does this PR do?
There are 3 tests in `test_diffusers.py` that don't have an HF upstream. 
This PR automates the `expected_slice` calculation to avoid failures in future. 
- 3 tests are passing CIs.
- No real impact on timing. 

##
```
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_diffusers.py -v -s -k test_stable_diffusion_xl_euler
.
.
=========================================================================================== 2 passed, 143 deselected, 3 warnings in 25.28s ============================================================================================
```
```
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/test_diffusers.py -v -s  -k test_stable_video_diffusion_single_video

.
.
============================================================================================ 1 passed, 144 deselected, 3 warnings in 8.80s ============================================================================================
```

Fixes # (issue)
https://github.com/huggingface/optimum-habana/pull/1163#issuecomment-2261315738

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by imangohari1** [comment]
@dsocek @skavulya FYI. Pls. take a look. Thank you.

**Review by skavulya — APPROVED** [review]
LGTM. Thanks @imangohari1!

**Review by dsocek — APPROVED** [review]
Looks good

**Comment by imangohari1** [comment]
I've pulled this PR in this integration branch for more comprehensive testing. Will update when that test is done. 
https://github.com/huggingface/optimum-habana/compare/main...imangohari1:optimum-habana:ig/ci_20240808?expand=1

**Comment by imangohari1** [comment]
I have tested this PR through the internal CI system, CI#165. 
There was one error introduced,
```
FAILED tests/test_diffusers.py::GaudiStableDiffusionXLPipelineTester::test_stable_diffusion_xl_turbo_euler_ancestral - NameError: name 'sd_pipe' is not defined
```
I pushed a fix for this. 
https://github.com/huggingface/optimum-habana/pull/1232/commits/3f79d4b4eee2e53f3a7f996a78b2765976d8c9e3

Should be all clear now. @regisss

**Comment by imangohari1** [comment]
I have tested this PR through the internal CI system, CI#165, using this fork:
https://github.com/huggingface/optimum-habana/compare/main...imangohari1:optimum-habana:ig/ci_20240813?expand=1

There was one error introduced,
```
FAILED tests/test_diffusers.py::GaudiStableDiffusionXLPipelineTester::test_stable_diffusion_xl_turbo_euler_ancestral - NameError: name 'sd_pipe' is not defined
```
I pushed fixs for this. It should be clear now. @regisss 
```
#  GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/test_diffusers.py -s -v -k test_stable_diffusion_xl_turbo_euler_ancestral
========================================================================================================= test session starts =========================================================================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /devops/sgohari/tests/codes/ig/optimum-habana
configfile: setup.cfg
collected 145 items / 144 deselected / 1 selected

tests/test_diffusers.py::GaudiStableDiffusionXLPipelineTester::test_stable_diffusion_xl_turbo_euler_ancestral ============================= HABANA PT BRIDGE CONFIGURATION ===========================
 PT_HPU_LAZY_MODE = 1
 PT_RECIPE_CACHE_PATH =
 PT_CACHE_FOLDER_DELETE = 0
 PT_HPU_RECIPE_CACHE_CONFIG =
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 1
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0
---------------------------: System Configuration :---------------------------
Num CPU Cores : 160
CPU RAM       : 1056375124 KB
------------------------------------------------------------------------------
[WARNING|pipeline_stable_diffusion_xl.py:542] 2024-08-14 15:37:42,248 >> The first two iterations are slower so it is recommended to feed more batches.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.36s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.35s/it]
PASSED

```

**Review by regisss — APPROVED** [review]

**Pull request merged**
