### PR TITLE
fix ds inference with user prompt for text-generation

### PR DESCRIPTION
**Pull request by ZhaiFeiyue**
# What does this PR do?

as title

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
@ZhaiFeiyue I pushed a commit to handle the case where args are already given in the right format after `gaudi_spawn.py`: `'"..."'`. It's necessary because there are a few places in READMEs where the example command line contains such args (see [here](https://github.com/huggingface/optimum-habana/tree/main/examples/summarization#multi-card-training) for instance).

**Review by regisss — APPROVED** [review]
Nice PR, I should have handle this that way from the beginning!

**Comment by ZhaiFeiyue** [comment]
> @ZhaiFeiyue I pushed a commit to handle the case where args are already given in the right format after `gaudi_spawn.py`: `'"..."'`. It's necessary because there are a few places in READMEs where the example command line contains such args (see [here](https://github.com/huggingface/optimum-habana/tree/main/examples/summarization#multi-card-training) for instance).

it always is '"..."' and won't be "'...'" right?

**Comment by regisss** [comment]
> "

Yep

**Pull request merged**
