### PR TITLE
VideoMAE Model Enabling and Examples

### PR DESCRIPTION
**Pull request by pi314ever**
# What does this PR do?

This PR gives examples and proves compatibility for [VideoMAE](https://huggingface.co/MCG-NJU/videomae-base-finetuned-kinetics) with Gaudi 2 on graph mode and casted to BF16. Tests included ensure compatibility with these and a latency regression test for the graph mode + BF16 model.

No core code changes were made to enable the model.

## Before submitting
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by yao-matrix** [comment]
@pi314ever Daniel, pls list out performance benchmark btw Gaudi 2 and A100.

**Comment by pi314ever** [comment]
| Performance (s) | A100 | Gaudi2 |
|--------|--------|--------|
| BF16 | 0.02548 | 0.01313 |
| FP32 | 0.05736| 0.01962 |

**Comment by mounikamandava** [comment]
can you rebase this?

**Comment by mounikamandava** [comment]
Looks good to me

**Review by mounikamandava — APPROVED** [review]

**Review by imangohari1 — CHANGES_REQUESTED** [review]
Hi @pi314ever 
Thank you for opening this PR. 
I have made some minor changes in the readme file and added Gadui1 CI test as well. 
Please apply these via `git am < 0001*`, test as needed and upstream. 
[0001-fea-Added-G1-ci-test.-updated-readme.patch](https://github.com/user-attachments/files/15915793/0001-fea-Added-G1-ci-test.-updated-readme.patch)


Could you also:
- test this with multiple video path inputs and share the output?
- add the reference code/script that this was adopted from?

**Comment by pi314ever** [comment]
I added the patch. I ran the script with multiple video inputs from [TempoFunk/webvid-10M](https://huggingface.co/datasets/TempoFunk/webvid-10M):
```sh
python run_example.py -bg -w 3 \
    --video_paths https://ak.picdn.net/shutterstock/videos/5629184/preview/stock-footage-senior-couple-looking-through-binoculars-on-sailboat-together-shot-on-red-epic-for-high-quality-k.mp4 \
    https://ak.picdn.net/shutterstock/videos/21179416/preview/stock-footage-aerial-shot-winter-forest.mp4 \
    https://ak.picdn.net/shutterstock/videos/1063125190/preview/stock-footage-a-beautiful-cookie-with-oranges-lies-on-a-green-tablecloth.mp4 \
    https://ak.picdn.net/shutterstock/videos/1039695998/preview/stock-footage-japanese-highrise-office-skyscrapers-tokyo-square.mp4 \
    https://ak.picdn.net/shutterstock/videos/9607838/preview/stock-footage-zrenjanin-serbia-march-fans-watching-live-concert-bokeh-blur-urban-background-x.mp4 
```
Which gave outputs
```
Predicted class for stock-footage-senior-couple-looking-through-binoculars-on-sailboat-together-shot-on-red-epic-for-high-quality-k.mp4 is sailing and took 3.372e-01 seconds
Predicted class for stock-footage-aerial-shot-winter-forest.mp4 is sled dog racing and took 3.360e-01 seconds
Predicted class for stock-footage-a-beautiful-cookie-with-oranges-lies-on-a-green-tablecloth.mp4 is cooking sausages and took 3.349e-01 seconds
Predicted class for stock-footage-japanese-highrise-office-skyscrapers-tokyo-square.mp4 is marching and took 3.362e-01 seconds
Predicted class for stock-footage-zrenjanin-serbia-march-fans-watching-live-concert-bokeh-blur-urban-background-x.mp4 is slacklining and took 3.358e-01 seconds
```

The script was loosely adapted from example from the original [model card](https://huggingface.co/MCG-NJU/videomae-base-finetuned-kinetics) and #783.

**Comment by imangohari1** [comment]
Thank you @pi314ever 
I suggest we adding the example of multiple videos in the README.me file and a note on the adoption strategy. 

@regisss 
Could you kindly provide more review/comments for this?

**Review by regisss — APPROVED** [review]

**Pull request merged**
