### PR TITLE
gptj: fix missing token_idx

### PR DESCRIPTION
**Pull request by envsp**
# What does this PR do?

this PR fixes the following test cases failure
`RUN_SLOW=true  GAUDI2_CI=1 python -m pytest tests/transformers/tests/models/gptj/test_modeling_gptj.py  -v -s -k test_greedy_generate_dict_outputs_use_cache`

`GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/transformers/tests/models/gptj/test_modeling_gptj.py -s -v  -k test_gptj_gradient_checkpointing`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by imangohari1 — CHANGES_REQUESTED** [review]
Thanks! this is moving towards right direction. 
Still have one extra failure. 
```
FAILED tests/transformers/tests/models/gptj/test_modeling_gptj.py::GPTJModelTest::test_gptj_gradient_checkpointing - TypeError: 'NoneType' object is not subscriptable
```
Could you try to debug that too?
```
GAUDI2_CI=1 RUN_SLOW=1 python -m pytest tests/transformers/tests/models/gptj/test_modeling_gptj.py -s -v  -k test_gptj_gradient_checkpointing
```

**Comment by atakaha** [comment]
please change line 164 ~ 168 to
        sin: Optional[torch.Tensor] = None,
        cos: Optional[torch.Tensor] = None,
        output_attentions: Optional[bool] = False,
        token_idx: Optional[torch.Tensor] = None,
       
it looks these are position dependent.

**Comment by envsp** [comment]
fixed test_gptj_gradient_checkpointing

**Comment by imangohari1** [comment]
Thanks! 
The CI tests are passing and the results are the same as `1.16` release. 

I've pulled this PR in this integration branch for more comprehensive testing. Will update when that test is done. 
https://github.com/huggingface/optimum-habana/compare/main...imangohari1:optimum-habana:ig/ci_20240808?expand=1

**Comment by imangohari1** [comment]
I tested this PR for clm and works fine. 
``` 
 python3 ../gaudi_spawn.py   --world_size 8 --use_deepspeed run_clm.py --deepspeed ../../tests/configs/deepspeed_zero_2.json --model_name_or_path 'EleutherAI/gpt-j-6b' --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --num_train_epochs 1 --do_train --output_dir ~/gptj --gaudi_config_name Habana/gpt2 --use_habana --use_lazy_mode --throughput_warmup_steps 3 --overwrite_output_dir --gradient_checkpointing --use_hpu_graphs_for_inference 
```
```
{'train_runtime': 401.9875, 'train_samples_per_second': 3.139, 'train_steps_per_second': 0.025, 'train_loss': 2.2065972222222223, 'epoch': 1.0, 'memory_allocated (GB)': 26.34, 'max_memory_allocated (GB)': 94.08, 'total_memory_available (GB)': 94.62}
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [06:41<00:00, 44.67s/it]
[INFO|trainer.py:1658] 2024-08-09 19:28:41,552 >> Saving model checkpoint to /root/gptj
[INFO|configuration_utils.py:472] 2024-08-09 19:28:41,562 >> Configuration saved in /root/gptj/config.json
[INFO|configuration_utils.py:807] 2024-08-09 19:28:41,568 >> Configuration saved in /root/gptj/generation_config.json
[INFO|modeling_utils.py:2763] 2024-08-09 19:29:03,592 >> The model is bigger than the maximum size per checkpoint (5GB) and is going to be split in 3 checkpoint shards. You can find where each parameters has been saved in the index located at /root/gptj/model.safetensors.index.json.
[INFO|tokenization_utils_base.py:2702] 2024-08-09 19:29:03,601 >> tokenizer config file saved in /root/gptj/tokenizer_config.json
[INFO|tokenization_utils_base.py:2711] 2024-08-09 19:29:03,607 >> Special tokens file saved in /root/gptj/special_tokens_map.json
[INFO|configuration_utils.py:125] 2024-08-09 19:29:03,673 >> Configuration saved in /root/gptj/gaudi_config.json
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =      94.08
  memory_allocated (GB)       =      26.34
  total_flos                  = 77050784GF
  total_memory_available (GB) =      94.62
  train_loss                  =     2.2066
  train_runtime               = 0:06:41.98
  train_samples               =       1150
  train_samples_per_second    =      3.139
  train_steps_per_second      =      0.025
[INFO|modelcard.py:449] 2024-08-09 19:29:04,203 >> Dropping the following result as it does not have all the necessary fields:
{'task': {'name': 'Causal Language Modeling', 'type': 'text-generation'}, 'dataset': {'name': 'wikitext wikitext-2-raw-v1', 'type': 'wikitext', 'args': 'wikitext-2-raw-v1'}}
[2024-08-09 19:29:13,901] [INFO] [launch.py:348:main] Process 850 exits successfully.
[2024-08-09 19:29:13,903] [INFO] [launch.py:348:main] Process 845 exits successfully.
[2024-08-09 19:29:13,905] [INFO] [launch.py:348:main] Process 843 exits successfully.
[2024-08-09 19:29:13,906] [INFO] [launch.py:348:main] Process 847 exits successfully.
[2024-08-09 19:29:14,910] [INFO] [launch.py:348:main] Process 849 exits successfully.
[2024-08-09 19:29:14,912] [INFO] [launch.py:348:main] Process 846 exits successfully.
[2024-08-09 19:29:14,913] [INFO] [launch.py:348:main] Process 848 exits successfully.
[2024-08-09 19:29:14,915] [INFO] [launch.py:348:main] Process 844 exits successfully.

 ```

**Comment by atakaha** [comment]
I compared outputs and throughputs between main and this pr. I didn't see regression. This PR is ready to go.

**Review by atakaha — APPROVED** [review]
LGTM

**Review by jiminha — APPROVED** [review]

**Review by imangohari1 — CHANGES_REQUESTED** [review]
@envsp @atakaha CC @jiminha 
We need to revisit this code and the previous merged code on #1194 
There is a perf regression before and after (below). 
Please use the cmd below to match the expected perfomance. 
thanks. 


```bash
python3 ../gaudi_spawn.py --world_size 8 --use_deepspeed run_clm.py --deepspeed ../../tests/configs/deepspeed_zero_2.json --model_name_or_path 'EleutherAI/gpt-j-6b' --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --num_train_epochs 1 --do_train --output_dir ~/gptj --gaudi_config_name Habana/gpt2 --use_habana --use_lazy_mode --throughput_warmup_steps 3 --overwrite_output_dir --gradient_checkpointing --use_hpu_graphs_for_inference
```
**Current performance**
```
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =      94.04
  memory_allocated (GB)       =      26.34
  total_flos                  = 77050784GF
  total_memory_available (GB) =      94.62
  train_loss                  =     2.2066
  train_runtime               = 0:05:43.85
  train_samples               =       1150
  train_samples_per_second    =      3.782
  train_steps_per_second      =       0.03
```
**expected perf.** 
```
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =      94.16
  memory_allocated (GB)       =      26.49
  total_flos                  = 77050784GF
  total_memory_available (GB) =      94.62
  train_loss                  =     2.2066
  train_runtime               = 0:03:05.33
  train_samples               =       1150
  train_samples_per_second    =     22.067
  train_steps_per_second      =      0.173
```

**Comment by atakaha** [comment]
> @envsp @atakaha CC @jiminha We need to revisit this code and the previous merged code on #1194 There is a perf regression before and after (below). Please use the cmd below to match the expected perfomance. thanks.
> 
> ```shell
> python3 ../gaudi_spawn.py --world_size 8 --use_deepspeed run_clm.py --deepspeed ../../tests/configs/deepspeed_zero_2.json --model_name_or_path 'EleutherAI/gpt-j-6b' --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --num_train_epochs 1 --do_train --output_dir ~/gptj --gaudi_config_name Habana/gpt2 --use_habana --use_lazy_mode --throughput_warmup_steps 3 --overwrite_output_dir --gradient_checkpointing --use_hpu_graphs_for_inference
> ```
> 
> **Current performance**
> 
> ```
> ***** train metrics *****
>   epoch                       =        1.0
>   max_memory_allocated (GB)   =      94.04
>   memory_allocated (GB)       =      26.34
>   total_flos                  = 77050784GF
>   total_memory_available (GB) =      94.62
>   train_loss                  =     2.2066
>   train_runtime               = 0:05:43.85
>   train_samples               =       1150
>   train_samples_per_second    =      3.782
>   train_steps_per_second      =       0.03
> ```
> 
> **expected perf.**
> 
> ```
> ***** train metrics *****
>   epoch                       =        1.0
>   max_memory_allocated (GB)   =      94.16
>   memory_allocated (GB)       =      26.49
>   total_flos                  = 77050784GF
>   total_memory_available (GB) =      94.62
>   train_loss                  =     2.2066
>   train_runtime               = 0:03:05.33
>   train_samples               =       1150
>   train_samples_per_second    =     22.067
>   train_steps_per_second      =      0.173
> ```

@imangohari1, I'll going to work and create another PR for this issue. Could you proceed merging this fix?

**Comment by jiminha** [comment]
@atakaha  Please ignore perf issue, we identified the issue is caused by transformer upgrade itself.  There is additional save_checkpoint during training loop on TF 4.43 upgrade causing the checkitpoint save time added to the training perf.   If you want to confirm you can add ( --save_strategy "no") to command line and check perf.  This PR is good to go.

**Review by regisss — APPROVED** [review]
LGTM!

**Comment by imangohari1** [comment]
I tested this PR with and without `--save_strategy no` and appears that the perf. regression is due to that flag. 
the GPTJ implementation should be fine @atakaha  

```
python3 ../gaudi_spawn.py   --world_size 8 --use_deepspeed run_clm.py --deepspeed ../../tests/configs/deepspeed_zero_2.json --model_name_or_path 'EleutherAI/gpt-j-6b' --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --num_train_epochs 1 --do_train --output_dir ~/gptj --gaudi_config_name Habana/gpt2 --use_habana --use_lazy_mode --throughput_warmup_steps 3 --overwrite_output_dir --gradient_checkpointing --use_hpu_graphs_for_inference --save_strategy no
```
```
***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =       94.0
  memory_allocated (GB)       =      26.34
  total_flos                  = 77050784GF
  total_memory_available (GB) =      94.62
  train_loss                  =     2.2066
  train_runtime               = 0:02:53.65
  train_samples               =       1150
  train_samples_per_second    =     22.768
  train_steps_per_second      =      0.178 
  ```
  
  
  ```
  python3 ../gaudi_spawn.py   --world_size 8 --use_deepspeed run_clm.py --deepspeed ../../tests/configs/deepspeed_zero_2.json --model_name_or_path 'EleutherAI/gpt-j-6b' --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --num_train_epochs 1 --do_train --output_dir ~/gptj --gaudi_config_name Habana/gpt2 --use_habana --use_lazy_mode --throughput_warmup_steps 3 --overwrite_output_dir --gradient_checkpointing --use_hpu_graphs_for_inference 
  ```
  ```
  ***** train metrics *****
  epoch                       =        1.0
  max_memory_allocated (GB)   =       94.0
  memory_allocated (GB)       =      26.34
  total_flos                  = 77050784GF
  total_memory_available (GB) =      94.62
  train_loss                  =     2.2066
  train_runtime               = 0:06:13.29
  train_samples               =       1150
  train_samples_per_second    =      3.334
  train_steps_per_second      =      0.026 
  ```

**Pull request merged**
