### PR TITLE
Fix ZeroDivisionError in constrained beam search with static shapes

### PR DESCRIPTION
**Pull request by skavulya**
# What does this PR do?
Fixes ZeroDivisionError in constrained beam search for models with static shapes

`python examples/text-generation/run_generation.py --model_name_or_path openai-community/gpt2 --use_kv_cache --max_new_tokens 20  --use_hpu_graph --bf16 --no-ignore_eos --prompt "The weather" --force_words "hot " --num_beams 10`

```
Traceback (most recent call last):
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 692, in <module>
    main()
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 461, in main
    generate(None, args.reduce_recompile)
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 432, in generate
    outputs = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/optimum-habana/optimum/habana/transformers/generation/utils.py", line 1443, in generate
    result = self._constrained_beam_search(
  File "/root/optimum-habana/optimum/habana/transformers/generation/utils.py", line 3281, in _constrained_beam_search
    sequence_outputs = constrained_beam_scorer.finalize(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/beam_search.py", line 850, in finalize
    beam_hyp.add(final_tokens, final_score, beam_indices=beam_index, generated_len=generated_len)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/beam_search.py", line 965, in add
    score = sum_logprobs / (generated_len**self.length_penalty)
ZeroDivisionError: float division by zero
```

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by yafshar** [comment]
thanks @skavulya. Nice fix

**Comment by yafshar** [comment]
@skavulya please run `GAUDI2_CI=1 RUN_SLOW=true python -m pytest tests/transformers/tests/models/ -s -v` before and after changes and make sure there is no new one is introduced.

**Comment by skavulya** [comment]
@yafshar No new failures were introduced

**This pr**: = 25 failed, 874 passed, 326 skipped, 1 xpassed, 59 warnings in 1762.54s (0:29:22) =
**Main**: = 26 failed, 873 passed, 326 skipped, 1 xpassed, 59 warnings in 1343.83s (0:22:23) =

The additional failure in main is unrelated to this PR. It might be an intermittent issue.
```
FAILED tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py::Wav2Vec2RobustModelTest::test_ctc_train
FileNotFoundError: [Errno 2] No such file or directory: '/root/optimum-habana/tests/fixtures/tests_samples/COCO/000000039769.png'
```

**Review by yafshar — APPROVED** [review]
LGTM! 

@regisss, would you please check this PR.

**Review by regisss — APPROVED** [review]

**Pull request merged**
